### ISSUE TITLE
Expand Cpu only tasks assignments

### ISSUE THREAD

**Issue by winxp5421** [s3inlc/hashtopolis#105]
#103 In the Future, we should make the CPU only task assignment into general groups that are customizable/manageable by admins or superusers. elevated users can create and assign agents to one or many specific groups that can be deployed to tasks assigned to a group the agent is a part of.

Let say this
An Agent can be set to a group (G1) you can then set tasks to be issued to specific groups ( or all groups including none)
No need to have separate tasks.php
So think of it as a mix of trusted and cpu only
tasks with G1 are only issued to G1 group members
Tasks should be assignable to many groups at the same time IE. (G1,G2,G4 but not G3) 
On task creation, the Default task group should be "global". 
All agents should still follow the global task Que but, only if all group specific assigned work is done first! ( global is lower priority than group specific work )

**Comment by s3inlc** [comment]
This Group stuff is included in the new version, allowing to distribute tasks to agents more fine-grained.
