### ISSUE TITLE
Multiple Supertask creation variations

### ISSUE THREAD

**Issue by s3inlc** [s3inlc/hashtopolis#122]
Instead of creating supertasks from existing pre-conf tasks, it should be possible to create supertasks from hcmask files, input lists of masks or from settings min/max of bruteforce.

(similar to the way hashtopus does this on simple tasks)

**Comment by winxp5421** [comment]
Add features to easily create super-tasks quickly for example.
`#HL# wordlist -r $rulefile`
Where $rulefile is

- best64.rule
- best16.rule

This accelerated way of creating supertasks would output 
`#HL# wordlist -r best64.rule`
`#HL# wordlist -r best16.rule`

**Comment by winxp5421** [comment]
Implemented  https://github.com/s3inlc/hashtopolis/pull/464
