### ISSUE TITLE
Rebuilding Chunk Cache clears green from status indicator and cracked status from tasks page

### ISSUE THREAD

**Issue by soxrok2212** [s3inlc/hashtopolis#157]
Current Server version is 0.3.0, latest everything.

When rebuilding the chunk cache, the green clears from the status indicator and the cracked status is removed.

Example: 
<img width="1143" alt="screen shot 2017-04-04 at 1 18 05 pm" src="https://cloud.githubusercontent.com/assets/6226507/24669657/37bf4c5e-1939-11e7-8700-54f39c8ca1da.png">

The password is still available in the hashlist page, but is gone from the tasks page.

**Comment by winxp5421** [comment]
Not sure what the status is of this issue but its now over a year old without any more information added. I will be closing this issue if you feel this issue was closed in error please re-open and explain why.
