### ISSUE TITLE
Run specific command prior and after cracking

### ISSUE THREAD

**Issue by homm-it** [s3inlc/hashtopolis#163]
Server Version: 0.3.1
Client Version: 0.43.8
Hashcat version: 3.4.0

Hi,

I would like to know if Hashtopussy has an option to run a specific task or command on all client systems, prior and after the cracking is running? If its not possible, I think it would be a nice feature to add, so client systems could be used for other purposes when idling (not cracking).

**Comment by winxp5421** [comment]
Hashtopus had a feature where it would wait for a file to be removed before cracking started and create/ delete a file when not cracking. This could be added to hashtopussy in the future.

However, your idea of executing commands from the HTP server is extremely dangerous and kinda sounds like you want to create a botnet these kinds of things are not welcome here as it gives the community a bad rep. The only safeish way i see of telling other programs on a system is by having the client create files based on its current activity and having the other program you wish to run watch for changes in a specific directory.

**Comment by winxp5421** [comment]
Included in this issue: https://github.com/s3inlc/hashtopolis/issues/268
