### ISSUE TITLE
Crunch was aborted

### ISSUE THREAD

**Issue by pccheck** [s3inlc/hashtopolis#171]
hello,

whtas this error?
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload

1 agent only
[agentproblem.pdf](https://github.com/s3inlc/hashtopussy/files/921905/agentproblem.pdf)
[taskdetails.pdf](https://github.com/s3inlc/hashtopussy/files/921906/taskdetails.pdf)

**Comment by winxp5421** [comment]
Is the file `C:\NVIDIA\hashlists\1.cracked` acutally there?
Is this the only output from `hashtopussy.exe debug'?

**Comment by pccheck** [comment]
yes exist
I deleted and run but not function
appear
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload

**Comment by winxp5421** [comment]
WHY WOULD YOU DELETE IT! I wanted to know what was inside of it!

**Comment by pccheck** [comment]
sorry, I thought it would be some mistake and it excludes

**Comment by winxp5421** [comment]
Does 'hashtopussy.exe debug' give anymore information.

**Comment by pccheck** [comment]
C:\NVIDIA>hashtopussy.exe debug
Client Version 0.43.13
Checking for client updates
{"action":"update","type":"csharp","version":"0.43.13"}
{"action":"update","response":"SUCCESS","version":"OK"}
You are using the latest client version
System is Windows
Existing token found
{"action":"login","token":"naobmWPbBI"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"naobmWPbBI","force":0}
Hashcat version v3.5.0 found
Getting task
{"action":"task","token":"naobmWPbBI"}
{"action":"task","response":"SUCCESS","task":2,"attackcmd":"-a0 #HL# rockyou.txt -r rockyou-30000.rule","cmdpars":" --hash-type=2500
","hashlist":1,"bench":30,"statustimer":5,"files":["rockyou-30000.rule","rockyou.txt"],"benchType":"run","hashlistAlias":"#HL#"}
Downloading hashlist for this task, please wait...
{"action":"hashes","token":"naobmWPbBI","hashlist":1}
{"action":"hashes","response":"SUCCESS","data":"SENQWAQAAAACBlRyb2phbgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAr+JSo3BdE0e49EbzIYs7V54VC7r
YB5rL9GSYOW6jPx4PN9vZceg39ZEklnSht51d3LrKfekS7RSfQ8NybMjtfkiBFqEgimz6WrSS1JwOA3uNn9GXVESy\/d8oZ4\/eQABAwB1AgEKAAAAAAAAAAAACLMjtfkiBF
qEgimz6WrSS1JwOA3uNn9GXVESy\/d8oZ4\/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYwFAEAAA+sAgEAAA+sBAEAAA+sAgAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}
Getting chunk...
{"action":"chunk","token":"naobmWPbBI","taskId":2}
{"action":"chunk","response":"SUCCESS","status":"OK","chunk":21,"skip":897773,"length":860597}
C:\NVIDIA\hashcat\hashcat64.exe   --hash-type=2500 -a0 "C:\NVIDIA\hashlists\1"  rockyou.txt -r rockyou-30000.rule --outfile-check-di
r="C:\NVIDIA\hashlists\zaps1"  --potfile-disable --quiet --restore-disable --session=hashtopussy --status --machine-readable --statu
s-timer=5 --outfile-check-timer=5 --remove --remove-timer=5 --separator=: -s 897773 -l 860597
nvmlDeviceGetFanSpeed(): Not Supported
^C

**Comment by winxp5421** [comment]
you ctl+c before the error showed again plese

**Comment by pccheck** [comment]
run hashtopussy again and create files again
see images
![im2](https://cloud.githubusercontent.com/assets/26559283/25059783/5798c80c-2163-11e7-8181-a5821413520e.PNG)
![im1](https://cloud.githubusercontent.com/assets/26559283/25059784/5799fc54-2163-11e7-84e3-982dd386e314.PNG)

**Comment by winxp5421** [comment]
Whats in 1.cracked?

Please rerun hashtopussy.exe debug you closed the program before the error happened

**Comment by pccheck** [comment]
1.cracked is blank
There's nothing

**Comment by pccheck** [comment]
Agent ran again while running debug

**Comment by winxp5421** [comment]
So running in debug everything works fine.
Running in non debug mode it errors?

**Comment by pccheck** [comment]
after long time error again

ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
{"action":"solve","token":"naobmWPbBI","chunk":21,"keyspaceProgress":897773,"progress":28259521200,"total":52751100000,"speed":57,"s
tate":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
{"action":"solve","token":"naobmWPbBI","chunk":21,"keyspaceProgress":897773,"progress":28259521200,"total":52751100000,"speed":57,"s
tate":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
{"action":"solve","token":"naobmWPbBI","chunk":21,"keyspaceProgress":897773,"progress":28259521200,"total":52751100000,"speed":57,"s
tate":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
{"action":"solve","token":"naobmWPbBI","chunk":21,"keyspaceProgress":897773,"progress":28259521200,"total":52751100000,"speed":57,"s
tate":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
{"action":"solve","token":"naobmWPbBI","chunk":21,"keyspaceProgress":897773,"progress":28259521200,"total":52751100000,"speed":57,"s
tate":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
{"action":"solve","token":"naobmWPbBI","chunk":21,"keyspaceProgress":897773,"progress":28259521200,"total":52751100000,"speed":57,"s
tate":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
{"action":"solve","token":"naobmWPbBI","chunk":21,"keyspaceProgress":897773,"progress":28259521200,"total":52751100000,"speed":57,"s
tate":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
{"action":"solve","token":"naobmWPbBI","chunk":21,"keyspaceProgress":897773,"progress":28259521200,"total":52751100000,"speed":57,"s
tate":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
{"action":"solve","token":"naobmWPbBI","chunk":21,"keyspaceProgress":897773,"progress":28259521200,"total":52751100000,"speed":57,"s
tate":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
{"action":"solve","token":"naobmWPbBI","chunk":21,"keyspaceProgress":897773,"progress":28259521200,"total":52751100000,"speed":57,"s
tate":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
{"action":"solve","token":"naobmWPbBI","chunk":21,"keyspaceProgress":897773,"progress":28259521200,"total":52751100000,"speed":57,"s
tate":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
{"action":"solve","token":"naobmWPbBI","chunk":21,"keyspaceProgress":897773,"progress":28259521200,"total":52751100000,"speed":57,"s
tate":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
{"action":"solve","token":"naobmWPbBI","chunk":21,"keyspaceProgress":897773,"progress":28259521200,"total":52751100000,"speed":57,"s
tate":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\1.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
{"action":"solve","token":"naobmWPbBI","chunk":21,"keyspaceProgress":897773,"progress":28259521200,"total":52751100000,"speed":57,"s
tate":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR

file 1.cracked not have any text, 0kb

**Comment by rarrr** [comment]
I'm getting the same thing, it gets a couple of errors and then just loops over and over.  It was working fine on a GTX670 but I swapped it out for a R9 280X and now this. cracked file is also empty.

Client Version 0.43.13.
Hashtopussy: 0.3.2
Hashcat version v3.5.0 found

{"action":"solve","token":"NnIjII3qQM","chunk":107,"keyspaceProgress":46925824,"progress":752435200,"total":840204288,"speed":142,"state":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR
Chunk was aborted!
Writing any cracks in queue to file D:\hashcat-3.5.0\hashlists\1.cracked
No process is associated with this object.
Error processing packet for upload

**Comment by winxp5421** [comment]
Users that are experiencing this issue  please test with the attached version of the client. report back if fixed or not. Thank you!

[hashtopussy.zip](https://github.com/s3inlc/hashtopussy/files/987008/hashtopussy.zip)

**Comment by rarrr** [comment]
Still getting an error but it doesn't loop now:

"action":"solve","token":"NnIjII3qQM","chunk":297,"keyspaceProgress":1256476672,"progress":20105248768,"total":20123992064,"speed":143,"state":2,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress: 19.38% | Speed:143.00KH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1
STATUS  6       SPEED   148     1       EXEC_RUNTIME    6.679264        CURKU   1256476672      PROGRESS        20106149888     20123992064     RECHASH 0       2       RECSALT    0       1       TEMP    90      REJECTED        0
STATUS  6       SPEED   148     1       EXEC_RUNTIME    6.679264        CURKU   1256476672      PROGRESS        20106149888     20123992064     RECHASH 0       2       RECSALT    0       1       TEMP    88      REJECTED        0
Attack finished
{"action":"solve","token":"NnIjII3qQM","chunk":297,"keyspaceProgress":1256476672,"progress":20106149888,"total":20123992064,"speed":148,"state":6,"cracks":[]}
{"action":"solve","response":"ERROR","message":"Chunk was aborted!"}
ERROR
Chunk was aborted!
Writing any cracks in queue to file D:\hashcat-3.5.0\hashlists\1.cracked
No process is associated with this object.
Error processing packet for upload
Getting chunk...

**Comment by blazer2x** [comment]
Is this not expected behavior? I'm assuming the hashlist contains 1 hash, another agent has cracked the hash so the server aborts the chunk on the other agents?

**Comment by rarrr** [comment]
It hasn't been cracked though.

**Comment by blazer2x** [comment]
Can you please provide a method to replicate this problem exactly, we'll run it on our test setup and debug what is going on.

**Comment by rarrr** [comment]
like, including the handshake capture file?

**Comment by s3inlc** [comment]
As this issue is sitting here for more than half a year and there was a huge code change since, I close this issue now.

If the issue still persists, please reopen.
