### ISSUE TITLE
It crack but stop after that.

### ISSUE THREAD

**Issue by gmartore** [s3inlc/hashtopolis#186]
Hello

Hashtopussy: 0.3.2
Hashcat 3.5.0
Client Version 0.43.13

Progress: 48.99% | Speed:12.62GH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1
STATUS  5       SPEED   4948325 1       3604117 1       4059010 1       EXEC_RUNTIME    12.182125       8.847130        7.821273        CURKU   924188672       PROGRESS        3560534269952   7156947894272   RECHASH 1       1       RECSALT      1       1       TEMP    -1      -1      -1      REJECTED        0
STATUS  5       SPEED   4948325 1       3604117 1       4059010 1       EXEC_RUNTIME    12.182125       8.847130        7.821273        CURKU   924188672       PROGRESS        3560534269952   7156947894272   RECHASH 1       1       RECSALT      1       1       TEMP    -1      -1      -1      REJECTED        0
{"action":"solve","token":"pyNEwFIMks","chunk":1583,"keyspaceProgress":924188672,"progress":3560534269952,"total":7156947894272,"speed":12611452,"state":5,"cracks":["0x0100b3b55d7b8d013dc30df207df832affb2858e56ff4d58a2b8:Thread01"]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress: 49.75% | Speed:12.61GH/s | Cracks:1    | Accepted:0    | Zapped:0    | Queue:2
Finished processing chunk
Attack finished
Getting chunk...
{"action":"chunk","token":"pyNEwFIMks","taskId":103}
{"action":"chunk","response":"SUCCESS","status":"OK","chunk":1584,"skip":1861849088,"length":1861849088}
/root/hg/hashcat/hashcat64.bin   --hash-type=132 -a 3 "/root/hg/hashlists/25"  -1 ?d?u?l ?1?1?1?1?1?1?1?1  --outfile-check-dir="/root/hg/hashlists/zaps25"  --potfile-disable --quiet --restore-disable --session=hashtopussy --status --machine-readable --status-timer=5 --outfile-check-timer=5 --remove --remove-timer=5 --separator=: -s 1861849088 -l 1861849088
clGetDeviceIDs(): CL_DEVICE_NOT_FOUND
clGetDeviceIDs(): CL_DEVICE_NOT_FOUND
hashfile is empty or corrupt.
Attack finished

This job is only one hash, when the hash is cracked the server stop and not report nothing.

![image](https://cloud.githubusercontent.com/assets/28309325/25637118/dc809a6c-2f51-11e7-851f-d83c0aff0728.png)

this problem was report before?

Best regards,
Guillermo.

**Comment by alexlo0612** [comment]
Got similar issues here.
It cracked then it stopped at uploading.

[Start]
Client Version 0.43.13
Checking for client updates
{"action":"update","type":"csharp","version":"0.43.13"}
{"action":"update","response":"SUCCESS","version":"OK"}
You are using the latest client version
System is Linux
Existing token found
{"action":"login","token":"3A5BsFZpDi"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"3A5BsFZpDi","force":0}
Hashcat version  found
Getting task
{"action":"task","token":"3A5BsFZpDi"}
{"action":"task","response":"SUCCESS","task":35,"attackcmd":"-a3 #HL# s28032?d?d ","cmdpars":"-D1,2 -w3 --force --hash-type=7100","hashlist":16,"bench":30,"statustimer":5,"files":[],"benchType":"speed","hashlistAlias":"#HL#"}
Downloading hashlist for this task, please wait...
{"action":"hashes","token":"3A5BsFZpDi","hashlist":16}
{"action":"hashes","response":"SUCCESS","data":"JG1sJDM5NjgyJDM2ZmI0NGRhNmNiYjI4M2FiODY1NTgyMTQwNDA3OTc5NDQ5ZDFlODI0Y2M5MDEwOTRiODk0MzQzOGQwMzMyYzIkMjA1MjZlYWU5MmIzMmU1YzcwM2Y4ZGQ1M2U5MTc2ZWI5NTAwZTMxMzViODhjYmExZTc1MTI1YTJkNzNkMjdlMmZkOTYzNGM5NDYwNDE0YmM1MTE1YmE5YjJmMDlhN2Y3ZjJkYWUyNmU2ZTgxMDI1NzIzNzkzZDBiZTc1OGRlMDM="}
Getting chunk...
{"action":"chunk","token":"3A5BsFZpDi","taskId":35}
{"action":"chunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client to measure the keyspace for this task
{"action":"keyspace","token":"3A5BsFZpDi","taskId":35,"keyspace":100}
Getting chunk...
{"action":"chunk","token":"3A5BsFZpDi","taskId":35}
{"action":"chunk","response":"SUCCESS","status":"benchmark"}
Server has requested the client to perform a speed benchmark
clGetDeviceIDs(): CL_DEVICE_NOT_FOUND
{"action":"bench","token":"3A5BsFZpDi","taskId":35,"type":"speed","result":"100:4099.12"}
{"action":"bench","response":"SUCCESS","benchmark":"OK"}
Getting chunk...
{"action":"chunk","token":"3A5BsFZpDi","taskId":35}
{"action":"chunk","response":"SUCCESS","status":"OK","chunk":26,"skip":0,"length":100}
/home/alex/agent/hashcat/hashcat64.bin  -D1,2 -w3 --force --hash-type=7100 -a3 "/home/alex/agent/hashlists/16"  s28032?d?d  --outfile-check-dir="/home/alex/agent/hashlists/zaps16"  --potfile-disable --quiet --restore-disable --session=hashtopussy --status --machine-readable --status-timer=5 --outfile-check-timer=5 --remove --remove-timer=5 --separator=: -s 0 -l 100
clGetDeviceIDs(): CL_DEVICE_NOT_FOUND
STATUS	2	SPEED	0	1	0	1	0	1	EXEC_RUNTIME	1.050325	0.618065	0.000000	CURKU	0	PROGRESS	4	100	RECHASH	0	1	RECSALT	0	1	TEMP	-1	-1	-1	REJECTED	0	
{"action":"solve","token":"3A5BsFZpDi","chunk":26,"keyspaceProgress":0,"progress":4,"total":100,"speed":0,"state":2,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:  4.00% | Speed:0.00KH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1 
STATUS	2	SPEED	0	1	0	1	0	1	EXEC_RUNTIME	1.020359	0.618065	0.000000	CURKU	0	PROGRESS	4	100	RECHASH	0	1	RECSALT	0	1	TEMP	-1	-1	-1	REJECTED	0	
{"action":"solve","token":"3A5BsFZpDi","chunk":26,"keyspaceProgress":0,"progress":4,"total":100,"speed":0,"state":2,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:  4.00% | Speed:0.00KH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1 
STATUS	2	SPEED	0	1	0	1	0	1	EXEC_RUNTIME	1.009799	0.618065	0.000000	CURKU	0	PROGRESS	4	100	RECHASH	0	1	RECSALT	0	1	TEMP	-1	-1	-1	REJECTED	0	
{"action":"solve","token":"3A5BsFZpDi","chunk":26,"keyspaceProgress":0,"progress":4,"total":100,"speed":0,"state":2,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:  4.00% | Speed:0.00KH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1 
STATUS	2	SPEED	0	1	0	1	0	1	EXEC_RUNTIME	1.005916	0.618065	0.000000	CURKU	0	PROGRESS	4	100	RECHASH	0	1	RECSALT	0	1	TEMP	-1	-1	-1	REJECTED	0	
{"action":"solve","token":"3A5BsFZpDi","chunk":26,"keyspaceProgress":0,"progress":4,"total":100,"speed":0,"state":2,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:  4.00% | Speed:0.00KH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1 
STATUS	2	SPEED	0	1	0	1	0	1	EXEC_RUNTIME	1.017095	0.618065	0.000000	CURKU	0	PROGRESS	4	100	RECHASH	0	1	RECSALT	0	1	TEMP	-1	-1	-1	REJECTED	0	
{"action":"solve","token":"3A5BsFZpDi","chunk":26,"keyspaceProgress":0,"progress":4,"total":100,"speed":0,"state":2,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:  4.00% | Speed:0.00KH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1 
STATUS	2	SPEED	0	1	0	1	0	1	EXEC_RUNTIME	1.027635	0.618065	0.000000	CURKU	0	PROGRESS	4	100	RECHASH	0	1	RECSALT	0	1	TEMP	-1	-1	-1	REJECTED	0	
{"action":"solve","token":"3A5BsFZpDi","chunk":26,"keyspaceProgress":0,"progress":4,"total":100,"speed":0,"state":2,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:  4.00% | Speed:0.00KH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1 
STATUS	2	SPEED	0	1	0	1	0	1	EXEC_RUNTIME	1.015611	0.618065	0.000000	CURKU	0	PROGRESS	4	100	RECHASH	0	1	RECSALT	0	1	TEMP	-1	-1	-1	REJECTED	0	
{"action":"solve","token":"3A5BsFZpDi","chunk":26,"keyspaceProgress":0,"progress":4,"total":100,"speed":0,"state":2,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:  4.00% | Speed:0.00KH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1 
STATUS	2	SPEED	0	1	0	1	0	1	EXEC_RUNTIME	1.044291	0.618065	0.000000	CURKU	0	PROGRESS	4	100	RECHASH	0	1	RECSALT	0	1	TEMP	-1	-1	-1	REJECTED	0	
{"action":"solve","token":"3A5BsFZpDi","chunk":26,"keyspaceProgress":0,"progress":4,"total":100,"speed":0,"state":2,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:  4.00% | Speed:0.00KH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1 
STATUS	2	SPEED	0	1	0	1	0	1	EXEC_RUNTIME	1.012363	0.618065	0.000000	CURKU	0	PROGRESS	4	100	RECHASH	0	1	RECSALT	0	1	TEMP	-1	-1	-1	REJECTED	0	
{"action":"solve","token":"3A5BsFZpDi","chunk":26,"keyspaceProgress":0,"progress":4,"total":100,"speed":0,"state":2,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:  4.00% | Speed:0.00KH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1 
STATUS	5	SPEED	0	1	0	1	0	1	EXEC_RUNTIME	1.023423	0.618065	0.000000	CURKU	0	PROGRESS	100	100	RECHASH	1	1	RECSALT	1	1	TEMP	-1	-1	-1	REJECTED	0	
Attack finished
{"action":"solve","token":"3A5BsFZpDi","chunk":26,"keyspaceProgress":0,"progress":100,"total":100,"speed":0,"state":5,"cracks":["$ml$39682$36fb44da6cbb283ab865582140407979449d1e824cc901094b8943438d0332c2$20526eae92b32e5c703f8dd53e9176eb9500e3135b88cba1e75125a2d73d27e2fd9634c9460414bc5115ba9b2f09a7f7f2dae26e6e81025723793d0be758de03:s2803229"]}
 [The it suck here]

I have tested locally mode 7100 work fine with the same configuration. Other hash type works fine too.
![screenshot at 2017-05-05 11-50-24](https://cloud.githubusercontent.com/assets/11154774/25733179/2d4cb0a0-3189-11e7-80a3-6a5c7a215252.png)

**Comment by alexlo0612** [comment]
So how's this one going? The current version seems to have the same problem.

**Comment by s3inlc** [comment]
As this issue is sitting here for more than half a year and there was a huge code change since, I close this issue now. Most likely this issue is related to the hash length issues 

If the issue still persists with the newest version, please reopen.
