### ISSUE TITLE
Client sometimes gets stuck after completing a task

### ISSUE THREAD

**Issue by soxrok2212** [s3inlc/hashtopolis#193]
**Your current Server version located at the bottom of any hashtopussy webpage.**
0.3.2

**Current Client version.**
0.43.16

**The exact task command you are trying to run.**
```
#HL# -a 6 netgear.txt ?d?d?d
```

**Debug output from the client by running "hashtopussy.exe debug"**
Hard to catch, but this is the loop:
```
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task,
Downloading hashlist for this task, please wait...
Getting chunk...
```

**Describe your problem in as much detail as possible " It's broke " is not a description.**
Has happened a few times recently. When a task reaches 100% (and there are other tasks in the queue) the current task priority does not get set to 0 when completed and agents get stuck in the getting chunk loop until the priority is set to 0 and there is another task for them to be assigned to.

**Comment by winxp5421** [comment]
hey, sox
are you sure this is debugging output? seems strange there is not any JSON data.

**Comment by soxrok2212** [comment]
I wasn't able to catch it that time, I'll see if I can try today.

**Comment by winxp5421** [comment]
If you can that would be awesome. Right now we are unsure if its the client not sending proper information or a server bug.

**Comment by s3inlc** [comment]
As this issue is sitting here for more than half a year and there was a huge code change since, I close this issue now.

If the issue still persists with the newest version, please reopen.
