### ISSUE TITLE
.NET Client does not work with IP6 under linux

### ISSUE THREAD

**Issue by MultiStorm** [s3inlc/hashtopolis#199]
Hello,
i try du make a hashcat cluster whith hashtopussy, but under ubuntu does not work whith the C# Client.
The address is not resolved correctly during the download.
`
System is Linux
{"action":"register","voucher":"XXXXX","name":"XXXXXX","uid":"71cbefb1-1058-4fc4-8db7-b0f10048cb2a","os":0,"gpus":["Intel Corporation Sky Lake Integrated Graphics (rev 07)"]}
{"action":"register","response":"SUCCESS","token":"mDLHNiyMKk"}
Logged in to server
Downloading 7zip binary
{"action":"download","type":"7zr","token":"mDLHNiyMKk"}
{"action":"download","response":"SUCCESS","executable":"http:\/\/[2a02\/static\/7zr.unix"}
Downloading from http://[2a02/static/7zr.unix
`
you can see the IP6 was cuttet:
http:\/\/[2a02\/static\/7zr.unix
This can not work so naturally

Do you see a way to solve the problem?
Can you tell when the JAVA client will be ready? I could also offer help with the development of the JAVA client.

**Comment by MultiStorm** [comment]
i thing the problem is the [] in the URL
maybe you can mask the [] for correctly Download ?

**Comment by MultiStorm** [comment]
for information:
under Win10 Pro the same Problem, it is a ip6 problem on Linux and Windows,
i look later, maybe i can fix the bug, but an answer was nice

**Comment by winxp5421** [comment]
As far as I know non-of the dev's have ipv6. So something tells me this was overlooked. I can setup a test environment and work with our client dev to find a solution. 

Just to be upfront most of the dev's are busy with real life. This will be fixed but, it may be a little while before it is fixed.

**Comment by s3inlc** [comment]
I never actively thought about testing with IPv6, this was overlooked.

To your question about the java client. I have no idea when this will happen, as it's me who started with it and as I even don't have really enough time to cover all the server part stuff with my free time, the java client just has not a high enough priority for the development.
But if you have time, feel free to continue with the java client (or start completely new), we are open to all kind of contributions.

**Comment by winxp5421** [comment]
The .net client is considered depreciated and no longer compatible with the current versions of hashtopolis please switch to the python client.
If issues persist open a new issue.
