### ISSUE TITLE
Feature Request - New User Role: Normal User without manual task creation

### ISSUE THREAD

**Issue by Console** [s3inlc/hashtopolis#219]
It would be nice to have a user role that was essentially a normal user but with the limitation that the user can **only** use pre-configured tasks or supertasks.

Had our entire cluster down for an evening because someone tried "#HL dict1 dict2" as an attack string (no -a argument), the Agent stacktrace'd and the task he'd attempted to create was one I already had pre-configured tasks and supertasks which covered the guy's ask already.

Aside from beating him with a kidney stick whilst chanting "don't do it again", I would really appreciate the ability to limit the amount of damage users can do during the teething process of getting used to hashtopussy.

**Comment by blazer2x** [comment]
I will look into improving the agent to handle the errors better.

**Comment by s3inlc** [comment]
I connect this to issue #347 as this can be included in a permission update where this should be an option to set that users only can create tasks from pre-defined tasks.

**Comment by s3inlc** [comment]
As the complete fine-grained permission feature is included in the newest release now, you can just use the specific permissions to just give a user the possibility to run only pretasks.
I will close this issue now, please reopen if you think you still cannot achieve what you want to.
