### ISSUE TITLE
Client ignores web redirects to https

### ISSUE THREAD

**Issue by winxp5421** [s3inlc/hashtopolis#229]
Running hashtopussy as HTTP behind an HTTPS proxy results in the server passing a bad URL to the client during file downloads.

Hashtopussy server is running under an HTTP environment on the internal network but, all external connections run through an https web proxy. The server thinks "http://domainname.com/API/server.php" is the correct URL but, in reality, it is "https://domainname.com/API/server.php" the client is configured with the https URL and connection with the server is successful, however, when the client checks for need files the server passes an HTTP URL. Client does not respond to https redirects `rewrite     ^   https://$server_name$request_uri? permanent;`

```
Client Version 0.43.13
Checking for client updates
You are using the latest client version
System is Windows
Existing token found
Logged in to server
Downloading 7zip binary
{"action":"download","type":"7zr","token":"Rz2PcNBqEs"}
{"action":"download","response":"SUCCESS","executable":"http:\/\/domainname\/static\/7zr.exe"}
Downloading from http://domainname/static/7zr.exe

Unhandled Exception: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at hashtopussy.downloadClass.DownloadFile(String urlAddress, String location)
   at hashtopussy._7zClass.init7z()
   at hashtopussy.Program.Main(String[] args)
```

**Comment by winxp5421** [comment]
The solution was a bad Proxy Config, my bad.

**Comment by winxp5421** [comment]
The client does not redirect when configured to use http for connections to the server for work but, does follow redirects to https on downloads properly.

**Comment by s3inlc** [comment]
The server is now capable to handle a different base hostname as configurable in the server config. HTTPS forwarding still should be implemented on the client side to avoid crashes if such a case occurs.

**Comment by winxp5421** [comment]
.NET client is not compatible with the new server versions. closing
