### ISSUE TITLE
Feature Request - hashes with usernames

### ISSUE THREAD

**Issue by liquidxploit** [s3inlc/hashtopolis#232]
Can we add the ability to add hashes with usernames in them. 

For instance from a ntds dump, or shadow file. This way we don't have to go back and lookup the usernames associated with the hash.

**Comment by evilmog** [comment]
Hashtopolis isn't a hashlist management service, there is now a user API however which makes this trivial:
```
mkdir scripts
git clone https://github.com/evilmog/htpclientapi.git
```

make a config.json
```
{
        "host":"htphost",
        "port":"htpport",
        "certpath":"path to pem file saved with getcert.py",
        "apikey":"xxxxxxxxxx"
}
```

getcert.py
```
import ssl
import config as cfg
print ssl.get_server_certificate((cfg.data['host'], int(cfg.data['port'])))
```
 move the output of getcert.py to your cert.pem file and update json, then make the following file

for ntlm for example:
```
import config as cfg
from htpclientapi.functions import *


apikey = cfg.data['apikey']
certpath = cfg.data['certpath']

endpoint = cfg.data['host'] + ':' + cfg.data['port'] + '/api/user.php'
data = listhashlists(endpoint, certpath, apikey)

for hashlist in data['hashlists']:
  if hashlist['hashtypeId'] == 1000:
    crackeddata = gethashlistcracked(endpoint, certpath, apikey, hashlist['hashlistId'])
    for crackedhashlist in crackeddata['cracked']:
      print crackedhashlist['plain']
```

modify to suit, ideally when cracking things are faster without the usernames especially in large dumps

**Comment by winxp5421** [comment]
Hashtopolis is a work distributor not a hash management tool. Evilmog was kind enough to supply a nice way to handle this. Closing
