### ISSUE TITLE
distinguish the display of active vs inactive agents on the agents list page

### ISSUE THREAD

**Issue by roycewilliams** [s3inlc/hashtopolis#278]
(Server version 0.4.2)

Feature request: a way to toggle the display of inactive agents in agents list. I find myself scanning the list regularly to determine which agents are active. A way to toggle (hide/show) them might be handy, or maybe a way to visually distinguish them (like green for active, yellow for inactive). 

The definition of "active" is interesting; maybe if the server hasn't heard from them in 10 minutes or so? (Maybe make this a configurable option?) Or is there precedent or relevant clients parameters already in play that would suggest an obvious number?

**Comment by s3inlc** [comment]
With the new datatable feature (currently in the milestone/5 branch) you can order columns on the agent page, so you can order by active status and then it should be easily visible which agents are not active. Would this be enough for you, or do you need an even stronger distinguishment?

**Comment by roycewilliams** [comment]
Yeah, I think that that would do the trick - thanks! I'll reopen if I'm mistaken. :)
