### ISSUE TITLE
Default installation allows unauthenticated access to uploaded wordlist, rules, and mask files

### ISSUE THREAD

**Issue by marcus-brutus** [s3inlc/hashtopolis#297]
Server Version: 0.4.3
Client Version: 0.46.2
Hashcat Version: v4.0.0

Not command specific issue.

Created a default installation (followed the video guide), on Ubuntu Server 16.04.3 LTS, with Apache 2.4.18. After installation, the files directory (containing all wordlists and rules) is both listable and files are accessible through a browser without authentication. Files marked as 'secret' were also available. Since 'password lists' could potentially contain sensitive information, they should not be accessible in this manner. Problem looks to be a default apache installation does not respect .htaccess files, because they are to be avoided (per apache). Issue resolved by changing the line 'AllowOveride None' to 'AllowOveride All' under the directory heading for /var/www, in the main Apache config file (/etc/apache2/apache2.conf on this system). This was acceptable in my case as this is a single purpose testing (non-production) server. Several alternative solutions exist and may want to be considered, but at the least the wiki should be updated.

**Comment by winxp5421** [comment]
During the install phase of htp there is also a prompt I forming users to delete the install folder and suggests to users to check Apache settings for security adjustments. However I don't see harm in adding a suggestion in the wiki and pointing the newer users in the correct direction.

**Comment by marcus-brutus** [comment]
At least mentioning it somewhere would be good; I've found a few public internet facing instances with the files directory fully accessible unauthenticated.  As far as 'out of box configure', .htaccess files are already provided pre-configured with the default installation source, so it looks like the dev was assuming they would be used.  The issue is that apache ignores these files by default.

**Comment by s3inlc** [comment]
I added a textual note which will be shown at the end of the installation mentioning that the apache AllowOverride directive needs to be set to protect the directories and also mentioning which directories should be protected (if another approach is desired, or nginx is used)
We will also adjust the wiki for the new version then stating more clear how and which directories explicitly should be protected.
