### ISSUE TITLE
Blank Password Reset Emails

### ISSUE THREAD

**Issue by marcus-brutus** [s3inlc/hashtopolis#298]
Server Version: 0.4.3
Client Version: 0.46.2
Hashcat Version: v4.0.0

Not command specific issue.

Email is functioning on the server, but password reset email comes through without anything in the body. It looks like the html is either stripped, not sent, or not created.  Same behavior for both O365 and Gmail recipients.  I have not tested email notifications.  

Email appears to be otherwise functional on server from command line tests using both the mail and sendmail commands.  This includes html tests.

Looking for additional steps to help troubleshoot.

**Comment by s3inlc** [comment]
I think I identified the issue, the reason is a wrong template path where the email template is stored. Please replace this line https://github.com/s3inlc/hashtopussy/blob/master/src/forgot.php#L39 with:

```
$tmpl = new Template("email/forgot");
```
(Basically just replace the dot with a slash)

**Comment by s3inlc** [comment]
As the issue is fixed and also included in the upcoming version, I assume this issue can be closed.
