### ISSUE TITLE
Apache2 with Basic AuthType - client test connect failed

### ISSUE THREAD

**Issue by freeroute** [s3inlc/hashtopolis#300]
Server Apache2 with Basic Authentication not working. (when password authentication off, everything works)
hashtopussy server is on 2 virtual hosts: http://webserver and https://webserver. 
RewriteEngine on (http requests redirected to https)
Client downloaded, but when it try to connect to server, it failed.
**Is there an option that the client send username and password to the server?**

I can download the client with the command:
 `wget --user=username --password=password `https://webserver/agents.php?download=1
Next command: mv agents.php\?download\=1 hashtopussy.exe
root@hashcat:~/hashtopussy_client# mono ./hashtopussy.exe 
Client Version 0.46.2
Please enter server connect URL (https will be used unless specified):
https://hashtopussy.sytes.net/api/server.php
Testing connection to https://hashtopussy.sytes.net/api/server.php
**The remote server returned an error: (401) Unauthorized.**
Test connect failed, please enter server connect URL:

Testing connection to https://
Server: Ubuntu OS
Client: Kali OS
Hashtopussy version: 0.4.3 
My client version: 0.46.2
Hashcat version:  v4.0.1

**Comment by winxp5421** [comment]
Why are you using basic auth in the first place?  Arguably the way htp handles users is much better than basic auth could ever do.

On Nov 14, 2017, freeroute <notifications@github.com> wrote:

Server Apache2 with Basic Authentication not working. (when password authentication off, everything works)
hashtopussy server is on 2 virtual hosts: http://webserver and https://webserver.
RewriteEngine on (http requests redirected to https)
Client downloaded, but when it try to connect to server, it failed.
Is there an option that the client send username and password to the server?

I can download the client with the command:
wget --user=username --password=passwordhttps://webserver/agents.php?download=1
Next command: mv agents.php?download=1 hashtopussy.exe
root@hashcat:~/hashtopussy_client# mono ./hashtopussy.exe
Client Version 0.46.2
Please enter server connect URL (https will be used unless specified):
https://hashtopussy.sytes.net/api/server.php
Testing connection to https://hashtopussy.sytes.net/api/server.php
The remote server returned an error: (401) Unauthorized.
Test connect failed, please enter server connect URL:

Testing connection to https://
Server: Ubuntu OS
Client: Kali OS
Hashtopussy version: 0.4.3
My client version: 0.46.2
Hashcat version: v4.0.1

**Comment by roycewilliams** [comment]
The Apache Basic Auth mechanism, while very simple, is also very battle-hardened and robust for what it does. I'm personally in favor of continuing to support it if people find it to be a good match for their threat model.

**Comment by winxp5421** [comment]
Short answer no the client does not support this in it's current state.

**Comment by freeroute** [comment]
OK. Thanks the answer. I switch of Basic Auth for hashtopussy server.

**Comment by freeroute** [comment]
Can I close this issue?

**Comment by winxp5421** [comment]
Meh leave it open as a reminder for later development

**Comment by freeroute** [comment]
Great. It should be great if you implement this function.

**Comment by hops** [comment]
This has been implemented in the feature/proxies branch https://github.com/s3inlc/hashtopolis-agent/tree/feature/proxies
To use it set `auth-user` and `auth-password` in your config.json of the python client e.g.
```
  "auth-user": "john",
  "auth-password": "hunter2"
```
