### ISSUE TITLE
Error adding new hashtype

### ISSUE THREAD

**Issue by BaptisteFortin** [s3inlc/hashtopolis#301]
Server version : __0.4.3__
Client version : __0.46.2__
Hashcat version : __4.0.1__

I'm trying to add a new hashtype for a custom hashcat kernel : 
- Hashtype : 16000
- Description : new_kernel
- Salted : No

I get the Error __` Failed to add new hash type! `__ but the hashtype is added into the list.
Same problem with any other hashtype name, description or with salted option "yes".

I tried to use it with an agent. The agent reports the password cracked but hashtopussy says it is not.

**Comment by BaptisteFortin** [comment]
Adding a new hashtype works fine now, thank you.

I still have a problem when I try to use this new kernel I added.

My agent sends this report : 
{"action":"solve","token":"LND5oXkJMi","chunk":18,"keyspaceProgress":0,"progress":1000,"total":10000,"speed":8756,"state":5,"cracks":["FzRwXvJr2cS2AnZyNmO7lw==:YBhAKIzlvbPYi8fzqm6WKx0zwtbn4KDMe0E4Pvs5Eco=:1234"]}

The server responds like that : 
{"action":"solve","response":"SUCCESS",**"cracked":0**,"skipped":0,"zaps":[]}

**Comment by s3inlc** [comment]
Is the hash saved to the database in the same format as it's printed when cracked? As there is a : separator there, is it a salted hash? 
Check in the `Hash` table if the hash was parsed correctly and the hash is in the hash column and the salt in the salt column.

**Comment by BaptisteFortin** [comment]
I fixed my problem thank you.
The problem can from the fact that I did not check **`Salted hashes, separator`** in the hashlist creation form.

Why do you split hash and salt ? In hashcat everything is done in the parse function.

**Comment by BaptisteFortin** [comment]
Problem solved thanks, the hashtype was not defined as salted.
Why do you split salt and hash ?

The kernels 1710, 5500, 5600, 8300, 8400, 8900, 10100, 10900, 11000, 11900, 12000, 12100, 12600, 13500, 13800, 15000 are not defined as salted, I think they should be.

All people using these kernels with hashtopussy might get **false negative result**.

**Comment by winxp5421** [comment]
It's a rather large misconception that a salt should be part of the hash and I understand why most would think this. Both salt and hash are usually stored together in close proximity. However, the salt is part of the password and I think some people loose sight of this.

Anyways, hashcat handles salted hashes as a matched pair and we have to handle them the same way. That does not mean we should match cracked hashes by both salt and hash. The same code that matches unsalted hashes can be used to matched salted hashes as we are comparing only the hash ( which is what you should be doing anyway. )

Also splitting hash from salt on import we do not have to worry about separator problems later on ie multiple : in the salt causing confusion on where the salt starts and ends. This also enables you to upload your salt and hash paired lists with any separator you choose.  List 1 can be delimited with | and list 2 can be uploaded with ° as a delimiter. So again splitting hash and salt on import normalizes this data so we do not have to worry about delimiter type after import.


I will take a look at salted hashtypes again and make modifications to the default DB table. Feel free to Pull Request what you would like changed to salted algo's by default if you would like this done sooner.

**Comment by BaptisteFortin** [comment]
> The same code that matches unsalted hashes can be used to matched salted hashes as we are comparing only the hash

So if I well understood, you split hash and salt to be able to use the same code ?

---
With the fixed I pulled it is possible to use kernel n°12000.
If I test it with `sha1:1000:MzU4NTA4MzIzNzA1MDQ=:19ofiY+ahBXhvkDsp0j2ww==` which is hashcat example, it's works correctly : The agent and the server both report a cracked hash.

But in the database the values are not correct : 

| hash | salt |
| - | - |
| sha1 | 1000:MzU4NTA4MzIzNzA1MDQ=:19ofiY+ahBXhvkDsp0j2ww== |

I guess the splitting failed because there are multiples ':' but I don't understand why it works despite what you said.
I think that splitting in the database the hash and the salt is not useful.

**Comment by winxp5421** [comment]
In a real basic sense Yes but, you shouldn't handle salted hashes different from unsalted anyway as there is no need to do so. Splitting salts in a database sense is the right move. You don't see applications in the wild combining hashes and salts in one field why should HTP handle this differently?  I guess what I'm trying to say is matching solutions of hashes coming from hashcat to the proper uncracked hashes only requires matching the hash and nothing to do with the salt. As the salt is part of the password not the hash. Having the salt and hash separated allows us to keep our hashes salts and passwords separated. The common delimiter ':' is found in salts and passwords  if we did not separate hashes from salts it's very difficult to tell what is the salt and what is the password coming from hashcat. This also enables you the end user to import export and use any delimiter you wish at any time.

**Comment by winxp5421** [comment]
What exactly are you importing into HTP as the hash list 
The entire string 'sha1:1000:MzU4NTA4MzIzNzA1MDQ=:19ofiY+ahBXhvkDsp0j2ww==' ?

**Comment by BaptisteFortin** [comment]
It makes sense that you only need the hash to check if the result is correct. Thank you for these explanations
> The entire string 'sha1:1000:MzU4NTA4MzIzNzA1MDQ=:19ofiY+ahBXhvkDsp0j2ww==' ?    

Yes, like that, otherwise hashcat does not recognize the hash as being a PBKDF2-HMAC-SHA1. It returns **`No hashes loaded.`**

**Comment by winxp5421** [comment]
I think the best way to handle these is to change the delimiter between hash and salt from : to something else this way htp can determine what is what on import.

**Comment by BaptisteFortin** [comment]
If we do `sha1$1000$MzU4NTA4MzIzNzA1MDQ=:19ofiY+ahBXhvkDsp0j2ww==` for example, we will have : 

| hash | salt |
| - | - |
| sha1$1000$MzU4NTA4MzIzNzA1MDQ= | 19ofiY+ahBXhvkDsp0j2ww== |

What we want is : 

| hash | salt |
| - | - |
| 19ofiY+ahBXhvkDsp0j2ww== | MzU4NTA4MzIzNzA1MDQ= |

The PBKDF2-HMAC-SHA1 format is `sha1:<rounds>:<salt>:<hash>`

I think the only way is to do a specific parsing for these kind of hashtype.
But again, it is working with standard splitting.

**Comment by winxp5421** [comment]
Hmm yeah if that's the case we would need special code to handle this particular case. I'll tag this issue appropriately.

**Comment by BaptisteFortin** [comment]
And by the way, I forgot to mention that it is not possible to choose another separator than ':'. Hashcat is looking for that to split the input.

If you know where the parsing have to be done, I can have a look if you want.

**Comment by winxp5421** [comment]
Hashcat is not looking for : we supply our own separator

**Comment by BaptisteFortin** [comment]
I tested changing ':' for '$', '°' or '*' with the kernel n°10 (md5($pass.$salt)), I get a **`No hashes loaded.`** error. May be I'm doing something wrong, tell me if it works for you. With the ':' it is working.
I agree with you that it should be possible to change the separator : https://github.com/hashcat/hashcat/blob/master/src/interface.c#L3954
We can see on this line that the separator is in the **`hashconfig->separator`** so it can be initialized differently.

With the n°12000 kernel I think that it can not work because the separator is ':' in the hashcat code. You can check that in the parsing function : https://github.com/hashcat/hashcat/blob/master/src/interface.c#L12523

**Comment by s3inlc** [comment]
Sorry that I couldn't investigate this earlier. But the solution is pretty simple. 

I assume you selected that the hash is salted when you added the hashlist, right? But this is not good in this case, because this hashtype is more like a bcrypt hash where the salt is included in the hash and it should not be separated like e.g. with md5 and salts.

So basically it should just work when you don't tick the salted checkbox and add the hash. The whole hash then should be put into the hash column in the table and hashcat should be able to read the hash

**Comment by s3inlc** [comment]
I'll close this issue now as it's most likely to be resolved and the salt separator solution should work.

Please reopen if any problem still persists.
