### ISSUE TITLE
Supertask not marked as finished & not hidden in hashlists' show

### ISSUE THREAD

**Issue by TheWorkingDeveloper** [s3inlc/hashtopolis#303]
When running a supertask it's never marked as finished, even though the parts of it have finished.

![image](https://user-images.githubusercontent.com/33965786/33530387-0bcd0b4e-d87f-11e7-8422-53e859f2cd3f.png)
![image](https://user-images.githubusercontent.com/33965786/33530389-0e84a590-d87f-11e7-8a33-11223af3244d.png)

In the second  image you can also see that the hidden files are displayed, might be an idea to collapse these under the super and make the super list be % of progress depending on the subtasks.

**Comment by s3inlc** [comment]
This issue will be fixed in the upcoming 0.5.0 version. 
The case with the HIDDEN tasks also is improved and they won't be shown anymore, except on the supertask where they belong to.

**Comment by winxp5421** [comment]
I will be closing this issue if you feel this issue was closed in error please re-open and explain why.
