### ISSUE TITLE
no result with binary Superhashlist

### ISSUE THREAD

**Issue by paule965** [s3inlc/hashtopolis#306]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage.
0.4.3
Current Client version
0.46.2
Your current Hashcat version
4.0.1
The exact task command you are trying to run.
not important
Debug output from the client by running "hashtopussy.exe debug"

Describe your problem in as much detail as possible " It's broke " is not a description.
I create a superhashlist from some luks-hashlists and run this task without a result. When i run it seperatly as a normal hashlist i get the results. There is no Problem with a text-hash (SHA1), but the same with TrueCrypt (binary input problem?) ...

**Comment by s3inlc** [comment]
I'm not completely sure, but if I'm right, Hashcat is not designed to run multiple LUKS files at once. Can you please test when you just run Hashcat with the file having all LUKS files concatenated and look if it works as expected?

**Comment by paule965** [comment]
Sorry for the late answer, but i was some month away and had to try somethings
before. 
At first it is not possible to run hashcat with concatenated binaries. It is imho a option for truecrypt, but it make no sense for luks or veracrypt. There are to many Options inside Luks(different Keys,  iterations and Payloads) and so it is to slow. Imho need it  different attacks for every single-file.

**Comment by winxp5421** [comment]
I will be closing this issue if you feel this issue was closed in error please re-open and explain why.
