### ISSUE TITLE
Agents not receiving tasks

### ISSUE THREAD

**Issue by watson0x90** [s3inlc/hashtopolis#315]
Server Version:
0.4.3

Current Client version:
0.4.62 (csharp)

Your current Hashcat version:
4.0.1

The exact task command you are trying to run.
-a 0 #HL# rockyou.txt -r hob064.rule -w 3
(Confirmed all files do exist on the server)

Debug output:

Client Version 0.46.2
Connecting to server https://hashtopussy/api/server.php
Checking for client updates
{"action":"update","type":"csharp","version":"0.46.2"}
{"action":"update","response":"SUCCESS","version":"OK"}
You are using the latest client version
System is Windows
Existing token found
{"action":"login","token":"tpIIUm79xw"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"tpIIUm79xw","force":0}
Hashcat version v4.0.1 found
Using new STATUS codes
Getting task
{"action":"task","token":"tpIIUm79xw"}
{"action":"task","response":"SUCCESS","task":"NONE"}
No new task assigned to agent
Getting task
{"action":"task","token":"tpIIUm79xw"}
{"action":"task","response":"SUCCESS","task":"NONE"}
No new task assigned to agent

Details:
This is a new installation of Hashtopussy, with a clone of the project as of Jan 23, 2018. I have confirmed that the agents are successfully checking in. However when the agents check in, the task becomes unassigned. I have watched the assignment table in the database populate with the task, but then the row disappears.

**Comment by blazer2x** [comment]
have you set a priority to the task and are you using a trusted agent? 
Trusted agent is needed for hashlist/tasks which contains trusted data.
