### ISSUE TITLE
NetNTLMv2 Data too long for column 'salt'

### ISSUE THREAD

**Issue by recrudesce** [s3inlc/hashtopolis#322]
## Your current Server version located at the bottom of any hashtopussy webpage.
0.5.0 alpha

## Current Client version
0.50.2

## Your current Hashcat version
4.0.1

## Issue Description:
When creating a hash list, if you select `5600 - NetNTLMv2` from the list, it automatically checks the `Salt Separator` check box.  However, when you then attempt to save the hash list, the server will HTTP 500 and throw the following Apache2 error

```
[Wed Jan 31 10:03:51.361040 2018] [:error] [pid 16248] [client 10.35.3.86:34992] PHP Fatal error:  Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'salt' at row 1 in /var/www/html/dba/AbstractModelFactory.class.php:267\nStack trace:\n#0 /var/www/html/dba/AbstractModelFactory.class.php(267): PDOStatement->execute(Array)\n#1 /var/www/html/inc/handlers/HashlistHandler.class.php(322): DBA\\AbstractModelFactory->massSave(Array)\n#2 /var/www/html/inc/handlers/HashlistHandler.class.php(95): HashlistHandler->create()\n#3 /var/www/html/hashlists.php(36): HashlistHandler->handle('createHashlist')\n#4 {main}\n  thrown in /var/www/html/dba/AbstractModelFactory.class.php on line 267, referer: http://x.x.x.x/hashlists.php?new=true
```
You then end up with a hash list, but with no hashes.
If you untick the `Salt Separator` checkbox the hashes import fine, and subsequently crack fine.

**Comment by s3inlc** [comment]
Thanks for describing the issue this detailed. The salt flag for the NetNTLM hashes is set wrong. As there are many separators inside the hash, it should be just take the full hash as hash only.  

I guess your other issue #323 is related with this one, as it does not accept the cracks when the hashes are imported as salted? Or does the verification not work when they were just imported as non-salted hashes?

**Comment by recrudesce** [comment]
The only way to get it to store them is to import as unsalted.
Once you've imported them as unsalted and then run the crack, any cracked hashes aren't stored as per #323

**Comment by winxp5421** [comment]
Closing this issue. If you are still having issues please re-open
