### ISSUE TITLE
Hashtype 13100 too long for column 'hash'

### ISSUE THREAD

**Issue by recrudesce** [s3inlc/hashtopolis#324]
Your current Server version located at the bottom of any hashtopussy webpage.
0.5.0 Alpha

Current Client version
0.50.2

Your current Hashcat version
4.0.1

## Issue Description
Me again (sorry !).  When trying to save a hash for type 13100, the length exceeds the column size in the MySQL database.

Currently the `hash` column is set to `varchar(1024)`, but the 13100 hash I have (and most if not all of them will be a length of similar size) is 2178 characters long.  This is just a column size issue, but it won't allow me to edit it in MySQL.  It might make sense to define the column as `TEXT` rather than `VARCHAR` ?

```
[Wed Jan 31 11:23:40.184203 2018] [:error] [pid 30247] [client 10.35.3.86:36232] PHP Fatal error:  Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'hash' at row 1 in /var/www/html/dba/AbstractModelFactory.class.php:267\nStack trace:\n#0 /var/www/html/dba/AbstractModelFactory.class.php(267): PDOStatement->execute(Array)\n#1 /var/www/html/inc/handlers/HashlistHandler.class.php(322): DBA\\AbstractModelFactory->massSave(Array)\n#2 /var/www/html/inc/handlers/HashlistHandler.class.php(95): HashlistHandler->create()\n#3 /var/www/html/hashlists.php(36): HashlistHandler->handle('createHashlist')\n#4 {main}\n  thrown in /var/www/html/dba/AbstractModelFactory.class.php on line 267, referer: http://x.x.x.x/hashlists.php?new=true
```

**Comment by s3inlc** [comment]
No problem, we are happy when people are testing stuff and report if there are problems.

On the config page on section Finetuning you can increase the max length of the hash column. Basically it should also work when you change it to TEXT, but I guess the performance will not be as good as with VARCHAR because of the indexes.

**Comment by s3inlc** [comment]
Hmm ok, this seems to be a mysql server config dependent issue. I have a server where I can set it to length 4000 without any problems, but I was not able to find out what exactly needs to be configured to allow more than 1024 bytes on the server.

**Comment by recrudesce** [comment]
I just installed MySQL through `apt`.

Might be related to MySQL version ?  I have MySQL 5.7 installed.

**Comment by s3inlc** [comment]
I think it's not a version issue, but configuration related. But the server where I can extend it to more than length 2014, is not managed by myself, so I don't know which configuration all were changed from the installation default.

**Comment by recrudesce** [comment]
What's the collation and type set to ?
Mine's utf8_unicode_ci and InnoDB respectively.

**Comment by s3inlc** [comment]
Yes, same here.

**Comment by recrudesce** [comment]
Very weird, it just throws `Query error: #1071 - Specified key was too long; max key length is 3072 bytes` if I try and set it to anything above 1024.

**Comment by s3inlc** [comment]
This is because 1024 length does not necessarily mean 1024 Bytes as it's utf8.

**Comment by recrudesce** [comment]
yeah, that's what I've worked out.  You'd think I'd be able to change 1024 to 1025, but it throws the same error.  Bleh - MySQL, it makes no sense :P

**Comment by s3inlc** [comment]
Haha yeah. Unfortunately googleing for the error does not help much as just everyone tells it cannot be larger.
As long as you don't want to run Hashtopussy with millions of hashes, I think it should not be a problem using TEXT instead of VARCHAR. I never tried it out, but it should be able to run without any change when you just change this column

**Comment by recrudesce** [comment]
If I drop the `hash` column then re-add it as `text()` it accepts the hash.  But when the job runs the agent does this

```
Getting task
Server has assigned client with Task:16, Cracker:1 and Hashlist:14
Downloading hashlist for this task, please wait...
Downloading from http://localhost/getHashlist.php?hashlists=14&token=T5xLuJSyPy
Downloading 100% @ 1.23 MB/s
Finished downloading file
Client already exists, skipping download
Getting chunk...
Server has requested the client measure the keyspace for this task
Getting chunk...
Server requested the client benchmark this task for 15 seconds
**No hashes loaded.**
Benchmark error, perhaps hashlist is empty
```

So it isn't able to crack it when the column is set to `text()` because it seems the agent doesn't get any hashes sent to it.

**Comment by s3inlc** [comment]
That is strange. I just tested with setting the column to TEXT and running the example NetNTLM hash again. And it still worked.

Have you checked that the hash isn't cracked in the hashlist yet?
To check if any error occured, please manually call `http://localhost/getHashlist.php?hashlists=14&token=T5xLuJSyPy` and look what the server sends.

**Comment by recrudesce** [comment]
That URL gets the hash, I wonder why the agent doesn't.

Lemme drop the database, reinstall HTP and change the column before adding any data.

**Comment by recrudesce** [comment]
OK, reinstalled.  If the column type is set to `text()` the agent always throws a `No hashes loaded` when a task is assigned to it.

**Comment by s3inlc** [comment]
Ok, maybe this is a client issue then, when the hash already got cracked and it removes it already then (--potfile-disable should be set on the on hashcat).
It would help when you can run the agent with the debug flag, we get more information then.

**Comment by recrudesce** [comment]
OK, so it seems the "No hashes loaded" error only appears when the hashtype is 13100.  If I set the `hash` column to `text` and crack an NetNTLMv2 hash 5600 it runs fine.

The debug output for 13100 is as follows (does not work):
```
Client Version 0.50.2
Connecting to server http://localhost/api/server.php
System is Linux
Existing token found
{"action":"login","clientSignature":"generic-csharp","token":"596ILdu7JS"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Sending server client information
System is Linux
{"action":"updateInformation","token":"596ILdu7JS","uid":"a48f19d4-2815-4fd1-959c-cd3d506a75d2","os":0,"devices":["NVIDIA Corporation Device 1b06 (rev a1)","NVIDIA Corporation Device 1b06 (rev a1)"]}
{"action":"updateInformation","response":"SUCCESS"}
Logged in to server
Checking for client updates
{"action":"checkClientVersion","type":"csharp","version":"0.50.2","token":"596ILdu7JS"}
{"action":"checkClientVersion","response":"SUCCESS","version":"OK"}
You are using the latest client version
Using new STATUS codes
Getting task
{"action":"getTask","token":"596ILdu7JS"}
{"action":"getTask","response":"SUCCESS","taskId":6,"attackcmd":"#HL# rockyou.txt -O -p ] --hash-type=13100 ","cmdpars":"","hashlistId":5,"bench":30,"statustimer":5,"files":["rockyou.txt"],"crackerId":"1","benchType":"run","hashlistAlias":"#HL#","keyspace":"14344384"}
Server has assigned client with Task:6, Cracker:1 and Hashlist:5
Downloading hashlist for this task, please wait...
{"action":"getHashlist","token":"596ILdu7JS","hashlistId":5}
{"action":"getHashlist","response":"SUCCESS","url":"getHashlist.php?hashlists=5&token=596ILdu7JS"}
Downloading from http://localhost/getHashlist.php?hashlists=5&token=596ILdu7JS
Downloading 100% @ 451.66 KB/s
Finished downloading file
{"action":"downloadBinary","type":"cracker","token":"596ILdu7JS","binaryVersionId":1,"force":0}
{"action":"downloadBinary","response":"SUCCESS","url":"https:\/\/hashcat.net\/files\/hashcat-4.0.1.7z","name":"hashcat","executable":"hashcat64.bin"}
Client already exists, skipping download
Getting chunk...
{"action":"getChunk","token":"596ILdu7JS","taskId":6}
{"action":"getChunk","response":"SUCCESS","status":"benchmark"}
Using /opt/htp/files/ as working directory
/opt/htp/hashcat/1/hashcat64.bin  "/opt/htp/hashlists/5" "/opt/htp/files/rockyou.txt" -O -p ] --hash-type=13100  --runtime=30 --restore-disable --potfile-disable  --machine-readable --session=hashtopussy
Server requested the client benchmark this task for 30 seconds
No hashes loaded.
Benchmark error, perhaps hashlist is empty
{"action":"clientError","token":"596ILdu7JS","taskId":6,"message":"Client received an invalid hashlist for benchmark"}
Getting task
{"action":"getTask","token":"596ILdu7JS"}
{"action":"getTask","response":"SUCCESS","taskId":6,"attackcmd":"#HL# rockyou.txt -O -p ] --hash-type=13100 ","cmdpars":"","hashlistId":5,"bench":30,"statustimer":5,"files":["rockyou.txt"],"crackerId":"1","benchType":"run","hashlistAlias":"#HL#","keyspace":"14344384"}
Server has assigned client with Task:6, Cracker:1 and Hashlist:5
Downloading hashlist for this task, please wait...
{"action":"getHashlist","token":"596ILdu7JS","hashlistId":5}
{"action":"getHashlist","response":"SUCCESS","url":"getHashlist.php?hashlists=5&token=596ILdu7JS"}
Downloading from http://localhost/getHashlist.php?hashlists=5&token=596ILdu7JS
Downloading 100% @ 1.10 MB/s
Finished downloading file
{"action":"downloadBinary","type":"cracker","token":"596ILdu7JS","binaryVersionId":1,"force":0}
{"action":"downloadBinary","response":"SUCCESS","url":"https:\/\/hashcat.net\/files\/hashcat-4.0.1.7z","name":"hashcat","executable":"hashcat64.bin"}
Client already exists, skipping download
Getting chunk...
{"action":"getChunk","token":"596ILdu7JS","taskId":6}
{"action":"getChunk","response":"SUCCESS","status":"benchmark"}
Using /opt/htp/files/ as working directory
/opt/htp/hashcat/1/hashcat64.bin  "/opt/htp/hashlists/5" "/opt/htp/files/rockyou.txt" -O -p ] --hash-type=13100  --runtime=30 --restore-disable --potfile-disable  --machine-readable --session=hashtopussy
Server requested the client benchmark this task for 30 seconds
No hashes loaded.
```

And the debug output for 5600 is as follows (does crack, but as per #323 doesn't record it as cracked.):
```
Getting task
{"action":"getTask","token":"596ILdu7JS"}
{"action":"getTask","response":"SUCCESS","taskId":7,"attackcmd":"#HL# rockyou.txt -p ] --hash-type=5600 ","cmdpars":"","hashlistId":4,"bench":30,"statustimer
":5,"files":["rockyou.txt"],"crackerId":"1","benchType":"run","hashlistAlias":"#HL#","keyspace":"0"}
Server has assigned client with Task:7, Cracker:1 and Hashlist:4
Downloading hashlist for this task, please wait...
{"action":"getHashlist","token":"596ILdu7JS","hashlistId":4}
{"action":"getHashlist","response":"SUCCESS","url":"getHashlist.php?hashlists=4&token=596ILdu7JS"}
Downloading from http://localhost/getHashlist.php?hashlists=4&token=596ILdu7JS
Downloading 100% @ 373.71 KB/s
Finished downloading file
{"action":"downloadBinary","type":"cracker","token":"596ILdu7JS","binaryVersionId":1,"force":0}
{"action":"downloadBinary","response":"SUCCESS","url":"https:\/\/hashcat.net\/files\/hashcat-4.0.1.7z","name":"hashcat","executable":"hashcat64.bin"}
Client already exists, skipping download
Getting chunk...
{"action":"getChunk","token":"596ILdu7JS","taskId":7}
{"action":"getChunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client measure the keyspace for this task
Using /opt/htp/files/ as working directory
/opt/htp/hashcat/1/hashcat64.bin    "/opt/htp/files/rockyou.txt" -p ] --hash-type=5600  --session=hashtopussy --keyspace --quiet
{"action":"sendKeyspace","token":"596ILdu7JS","taskId":7,"keyspace":14344384}
Getting chunk...
{"action":"getChunk","token":"596ILdu7JS","taskId":7}
{"action":"getChunk","response":"SUCCESS","status":"benchmark"}
Using /opt/htp/files/ as working directory
/opt/htp/hashcat/1/hashcat64.bin  "/opt/htp/hashlists/4" "/opt/htp/files/rockyou.txt" -p ] --hash-type=5600  --runtime=30 --restore-disable --potfile-disable
  --machine-readable --session=hashtopussy
Server requested the client benchmark this task for 30 seconds
STATUS  6       SPEED   140419957       1000    0       1000    EXEC_RUNTIME    6.460416        0.000000        CURKU   0       PROGRESS        1835008 14344
384     RECHASH 1       1       RECSALT 1       1       TEMP    48      59      REJECTED        0
hashcat (v4.0.1) starting...

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Not-Iterated
* Single-Hash
* Single-Salt

Password length minimum: 0
Password length maximum: 256

ATTENTION! Pure (unoptimized) OpenCL kernels selected.
This enables cracking passwords and salts > length 32 but for the price of drastical reduced performance.
If you want to switch to optimized OpenCL kernels, append -O to your commandline.

Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger disabled.



Dictionary cache hit:
* Filename..: /opt/htp/files/rockyou.txt
* Passwords.: 14344384
* Bytes.....: 139921497
* Keyspace..: 14344384

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit =>

PHUONG.NGUYEN::DEACONS:fd222d6ef53b47b4:6d05b273d8e18f155e38c345cf254de5:0101000000000000c0653150de09d201e41c1a2df1157ad9000000000200080053004d004200330001001e00570049004e002d00500052004800340039003200520051004100460056000400140053004d00420033002e006c006f00630061006c0003003400570049004e002d00500052004800340039003200520051004100460056002e0053004d00420033002e006c006f00630061006c000500140053004d00420033002e006c006f00630061006c0007000800c0653150de09d20106000400020000000800300030000000000000000000000000200000ffb668cd8e4501c19b5d9f12d638918443e045e23f2257c6e10cced1d6f30ade0a0010000000000000000000000000000000000009001e0063006900660073002f00730079007300740065006d0072006f006f007400000000000000000000000000]Welcome123


STATUS  6       SPEED   140419957       1000    0       1000    EXEC_RUNTIME    6.460416        0.000000        CURKU   0       PROGRESS        1835008 14344384     RECHASH 1       1       RECSALT 1       1       TEMP    48      59      REJECTED        0
Started: Wed Jan 31 13:34:53 2018

Stopped: Wed Jan 31 13:34:58 2018

{"action":"sendBenchmark","token":"596ILdu7JS","taskId":7,"type":"run","result":"0.127925186609617"}
{"action":"sendBenchmark","response":"SUCCESS","benchmark":"OK"}
Getting chunk...
{"action":"getChunk","token":"596ILdu7JS","taskId":7}
{"action":"getChunk","response":"SUCCESS","status":"OK","chunkId":3,"skip":0,"length":14344384}
/opt/htp/hashcat/1/hashcat64.bin   "/opt/htp/hashlists/4"  "/opt/htp/files/rockyou.txt" -p ] --hash-type=5600  --outfile-check-dir="/opt/htp/hashlists/zaps4"  --potfile-disable --quiet --restore-disable --session=hashtopussy --status --machine-readable --status-timer=5 --outfile-check-timer=5 --remove --remove-timer=5 --separator=: -s 0 -l 14344384
STATUS  6       SPEED   140291131       1000    0       1000    EXEC_RUNTIME    6.452224        0.000000        CURKU   0       PROGRESS        1835008 14344384     RECHASH 1       1       RECSALT 1       1       TEMP    49      60      REJECTED        0
{"action":"sendProgress","token":"596ILdu7JS","chunkId":3,"keyspaceProgress":0,"relativeProgress":1279.0000000000002,"speed":140291131,"state":5,"cracks":["PHUONG.NGUYEN::DEACONS:fd222d6ef53b47b4:6d05b273d8e18f155e38c345cf254de5:0101000000000000c0653150de09d201e41c1a2df1157ad9000000000200080053004d004200330001001e00570049004e002d00500052004800340039003200520051004100460056000400140053004d00420033002e006c006f00630061006c0003003400570049004e002d00500052004800340039003200520051004100460056002e0053004d00420033002e006c006f00630061006c000500140053004d00420033002e006c006f00630061006c0007000800c0653150de09d20106000400020000000800300030000000000000000000000000200000ffb668cd8e4501c19b5d9f12d638918443e045e23f2257c6e10cced1d6f30ade0a0010000000000000000000000000000000000009001e0063006900660073002f00730079007300740065006d0072006f006f007400000000000000000000000000:Welcome123"]}
{"action":"sendProgress","response":"SUCCESS","cracked":0,"skipped":1,"zaps":[]}
Progress: 12.79% | Speed:140.29MH/s | Cracks:1    | Accepted:0    | Zapped:0    | Queue:1 
Finished processing chunk
Attack finished
Getting chunk...
{"action":"getChunk","token":"596ILdu7JS","taskId":7}
{"action":"getChunk","response":"ERROR","message":"You are not assigned to this task!"}
ERROR
You are not assigned to this task!
```

**Comment by s3inlc** [comment]
Ok, I'll test with a Kerberos hash too on my system, maybe this is another issue then.

Would it be possible for you to test the NetNTLM crack problem with the Python client, if the hash also gets skipped there?

**Comment by s3inlc** [comment]
Too bad, on my laptop the kerberos kernel build fails, so I cannot test it directly. When you check the hashlist download (getHashlist.php?hashlists=5&token=596ILdu7JS) the kerberos hash is given in correct format?

**Comment by recrudesce** [comment]
I'll test with the Python agent, leave that with me.

Regarding the hash, it is returned correctly.  The hash format is the same as that shown on https://hashcat.net/wiki/doku.php?id=example_hashes

**Comment by s3inlc** [comment]
Ok great. Let me know if it works with the Python agent. If yes, I know what the bug on the C# client must be.

**Comment by s3inlc** [comment]
Ah, I just realized what the problem with the C# client is. I'll inform blazer to fix this. The C# client sets : as separator always and therefore the server still can't validate the crack.

**Comment by recrudesce** [comment]
So that potentially fixes #323, but hash type 13100 doesn't have any `:` characters in it.  I'll test with the Python agent and get back to you ASAP.

**Comment by recrudesce** [comment]
OK, the Python agent does the same error when presented with a 13100 hash

```
Starting new HTTP connection (1): 10.35.3.125
"POST /api/server.php HTTP/1.1" 200 268
b'{"action":"getTask","response":"SUCCESS","taskId":6,"attackcmd":"#HL# rockyou.txt -O -p ] --hash-type=13100 ","cmdpars":"","hashlistId":5,"bench":30,"statustimer":5,"files":["rockyou.txt"],"crackerId":"1","benchType":"run","hashlistAlias":"#HL#","keyspace":"14344384"}'
Got task with id: 6
{'type': 'cracker', 'binaryVersionId': '1', 'action': 'downloadBinary', 'token': 'mGjaUGSytu'}
Starting new HTTP connection (1): 10.35.3.125
"POST /api/server.php HTTP/1.1" 200 149
b'{"action":"downloadBinary","response":"SUCCESS","url":"https:\\/\\/hashcat.net\\/files\\/hashcat-4.0.1.7z","name":"hashcat","executable":"hashcat64.bin"}'
{'hashlistId': 5, 'action': 'getHashlist', 'token': 'mGjaUGSytu'}
Starting new HTTP connection (1): 10.35.3.125
"POST /api/server.php HTTP/1.1" 200 98
b'{"action":"getHashlist","response":"SUCCESS","url":"getHashlist.php?hashlists=5&token=mGjaUGSytu"}'
Starting new HTTP connection (1): 10.35.3.125
"GET /getHashlist.php?hashlists=5&token=mGjaUGSytu HTTP/1.1" 200 1294
Downloading: [====================================================================================]
Got cracker binary type hashcat
{'taskId': 6, 'action': 'getChunk', 'token': 'mGjaUGSytu'}
Starting new HTTP connection (1): 10.35.3.125
"POST /api/server.php HTTP/1.1" 200 63
b'{"action":"getChunk","response":"SUCCESS","status":"benchmark"}'
Benchmark task...
CALL: ../crackers/1/hashcat64.bin --machine-readable --quiet --runtime=30 --restore-disable --potfile-disable --session=hashtopussy ../hashlists/5 rockyou.txt -O -p ] --hash-type=13100 
started benchmark
{'message': '\x1b[31mNo hashes loaded.\x1b[0m', 'taskId': 6, 'action': 'clientError', 'token': 'mGjaUGSytu'}
```

**Comment by s3inlc** [comment]
Ok, regarding the problem with the C# client, yes the 13100 does not have `:` inside the hash, but when he sends `hash:plain` and the server is expecting `hash]plain` as the separator is different, it won't work.

Can you run the hashcat command manually once, inside the `files` directory of the Python client:
```
../crackers/1/hashcat64.bin --machine-readable --quiet --runtime=30 --restore-disable --potfile-disable --session=hashtopussy ../hashlists/5 rockyou.txt -O -p ] --hash-type=13100 
```

**Comment by recrudesce** [comment]
OK, that showed that hashcat was throwing an error that wasn't being logged or displayed by the agent.

```
Hashfile '../hashlists/5' on line 1 ($krb5tgs$MSSQLSvc/COMPUTER.domain.com:1210:F39D628791B89935620269AC99ED0C5C$30B5DBDBFFD3A2A6C248B424178E8
****SNIP****
09FF2D096F87772A000B569360BB563EBBCB7526D5C5AA431745F9B334E51C79B56B9EB9D505E1E3E
CC): Signature unmatched
No hashes loaded.
```

I tried another 13100 hash and it cracked it fine, but as with #323 it didn't store the plaintext in the database.

**Comment by s3inlc** [comment]
Ok, so we broke it down now to one remaining issue where the cracks are not submitted correctly?

So can you make sure that you test it with the Python Client (the C# client will not be fixed before the weekend) and make sure that you have the version included which I pushed some minutes ago.

**Comment by recrudesce** [comment]
The Python client cracked it but didn't store it either.

Can you link me to the correct Python client to ensure we're working off the same code base.

**Comment by s3inlc** [comment]
It should be this one: https://github.com/s3inlc/hashtopussy/blob/dev/src/bin/hashtopussy.zip

**Comment by s3inlc** [comment]
Oh and note that you need to place the zip on the client manually. There is currently no auto-update function on the python client

**Comment by recrudesce** [comment]
Latest Python agent fails to store the plain text

```
Starting new HTTP connection (1): 10.35.3.125
"POST /api/server.php HTTP/1.1" 500 0
Status code from server: 500
Failed to send solve!
Sending 1 cracks...
{'action': 'sendProgress', 'speed': 27574921, 'token': 'P47pEZe4Ib', 'cracks': ['$krb5tgs$23$*USER$domain.com$MSSQLSvc/COMPUTER.domain.com:1210*$f39d628791b89935620269ac99ed0c5c$30b5dbdbffd3a2a6c248b424178e80b73f7053c241fdf3ce68452d765399c933b098e26***SNIP***
5f9b334e51c79b56b9eb9d505e1e3ecc]Welcome123'], 'state': 5, 'chunkId': 8, 'relativeProgress': 10000, 'keyspaceProgress': 11012172}
Starting new HTTP connection (1): 10.35.3.125
"POST /api/server.php HTTP/1.1" 200 80
b'{"action":"sendProgress","response":"SUCCESS","cracked":0,"skipped":1,"zaps":[]}'
Progress:100.00% Speed:  26.30MH/s Cracks: 1 Accepted: 0 Skips: 1 Zaps: 0
finished chunk
{'action': 'downloadBinary', 'type': 'cracker', 'binaryVersionId': '1', 'token': 'P47pEZe4Ib'}
Starting new HTTP connection (1): 10.35.3.125
"POST /api/server.php HTTP/1.1" 200 149
b'{"action":"downloadBinary","response":"SUCCESS","url":"https:\\/\\/hashcat.net\\/files\\/hashcat-4.0.1.7z","name":"hashcat","executable":"hashcat64.bin"}'
{'action': 'getChunk', 'taskId': 14, 'token': 'P47pEZe4Ib'}
Starting new HTTP connection (1): 10.35.3.125
"POST /api/server.php HTTP/1.1" 200 87
b'{"action":"getChunk","response":"ERROR","message":"You are not assigned to this task!"}'
Getting of chunk failed: {'action': 'getChunk', 'response': 'ERROR', 'message': 'You are not assigned to this task!'}
```

I guess there's something problematic with the characters in the hash, more than likely the `/` character in it.

It seems to attempt the submission, but fails
```
"POST /api/server.php HTTP/1.1" 500 0
Status code from server: 500
Failed to send solve!
```

**Comment by s3inlc** [comment]
Oh, can you maybe set the `display_errors` to 1 in the `inc/load` file and see what the error message is on sending the crack?

**Comment by recrudesce** [comment]
Ah, it's our old friend again.

```
"POST /api/server.php HTTP/1.1" 200 581
b"<br />\n<b>Fatal error</b>:  Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'hash' at row 1 in /var/www/html/dba/AbstractModelFactory.class.php:267\nStack trace:\n#0 /var/www/html/dba/AbstractModelFactory.class.php(267): PDOStatement-&gt;execute(Array)\n#1 /var/www/html/inc/api/APISendProgress.class.php(206): DBA\\AbstractModelFactory-&gt;massSave(Array)\n#2 /var/www/html/api/server.php(109): APISendProgress-&gt;execute(Array)\n#3 {main}\n  thrown in <b>/var/www/html/dba/AbstractModelFactory.class.php</b> on line <b>267</b><br />\n"
Error occurred: Expecting value: line 1 column 1 (char 0)
Failed to send solve!
Sending 1 cracks...
```

Which is weird, cos the `hash` column type in the `hash` table is `text`.  
Also, it actually DOES put the plaintext entry into the table, marks it as `isCracked = 1`, but when you view the hash list through the web interface it still shows it as 0/1 cracked.  If you subsequently go into the hash list through the web interface, the hash shows as cracked, and only shows up when you filter on `Cracked`.

Is cracked in the database
![image](https://user-images.githubusercontent.com/6450799/35632031-6bcf362e-069d-11e8-80d0-3f7cc0e10c4a.png)

Showing as not cracked in the hash list table:
![image](https://user-images.githubusercontent.com/6450799/35632003-53dd307a-069d-11e8-8c27-f61ba53415f4.png)

Showing as not cracked in the hash list:
![image](https://user-images.githubusercontent.com/6450799/35632079-9374f52e-069d-11e8-8ff9-ca93ac817876.png)

Filtering the list on Uncracked returns 0 entries:
![image](https://user-images.githubusercontent.com/6450799/35632136-b9aec01c-069d-11e8-96ef-a245afd98079.png)

Filtering the list on Cracked returns 1 entries:
![image](https://user-images.githubusercontent.com/6450799/35632153-cd7dc3b8-069d-11e8-84b1-e6b90e5b42d3.png)

**Comment by s3inlc** [comment]
Ahh, I know where it fails. It's not the Hash table, it's the Zap table. As there the hash gets stored to eventually notify other agents about the cracked hash to remove it from their left list.
I need to update the length update to also adjust it there. When you set the column hash to TEXT on the Hash table, you also need to do this on the Zap table to get it running correctly.

And because it crashed before saving the updated values for cracked/uncracked on the hashlist, the crack itself is stored, but the values are not updated. This can be fixed with rebuilding chunk cache on the server config.

**Comment by recrudesce** [comment]
OK, I'll edit my `ZAP` table to match the `hash` table and give it another go.

**Comment by s3inlc** [comment]
Just if you're interested to maybe still keep VARCHAR instead of TEXT, I think I found out which config variables are responsible for the limit.

It's the InnoDB file format: https://dev.mysql.com/doc/refman/5.7/en/innodb-file-format.html
The server where I could go over 1024 chars, was using Antelope instead of Barracuda (which is the default format on new installations). Also `innodb_large_prefix` should be set to ON.

**Comment by recrudesce** [comment]
So I guess the options here are to
* Instruct the user how to reconfigure their MySQL installation, which might break other things they're running on it
* Change the 2 `hash` column types to `text()` and accept the potential performance and storage hit

**Comment by s3inlc** [comment]
Yeah, I think we should put this on a wiki page for the users which need to run large hashes.

**Comment by recrudesce** [comment]
Totally makes sense.  I'll work out what needs to be changed for the first option and give it a test out.  I'll do that in the next couple of days (too much work to do !).  Thanks for all your quick responses today, it's been greatly appreciated :)

**Comment by s3inlc** [comment]
Ok, that would be great if you could report back if the MySQL configuration changes are also solving the problem. If it works I can include this then as solution.
Thanks for your feedback and testing ;)

**Comment by recrudesce** [comment]
I feel I should update this - changing the field to TEXT() has worked wonders and with no ill effects.

**Comment by winxp5421** [comment]
Closing this issue. If you are still having issues please re-open
