### ISSUE TITLE
Can I limit assigning Agent number 

### ISSUE THREAD

**Issue by agentlimit** [s3inlc/hashtopolis#326]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage.
 hashtopussy 0.5.0 alpha
Current Client version
 hashtopussy 0.1.0(python version)
Your current Hashcat version
 4.0.1
The exact task command you are trying to run.
 nothing
Debug output from the client by running "hashtopussy.exe debug"
 Nope.
Describe your problem in as much detail as possible " It's broke " is not a description.
 - My question is very simple. How can I limit agent number for one task? 
   If I have ten agent , I want to assign 5 agent to  one task and the others to second task for working at the same time. 
  Is it possible ? 
  Thanks.

**Comment by s3inlc** [comment]
Currently you only can set that a task will get completed by one agent maximum (this is the `is small` setting. But currently there is no way to set a dynamic number to limit the number of agents for a task.

**Comment by agentlimit** [comment]
Hi s3inlc~
Thanks for fast reply. 
Ok. then I've another  question .  If a task set  the small task, then how hastopussy does work? 
where is the code "one agent maximun" for small task ?
 Thanks.

**Comment by s3inlc** [comment]
When an agent is requesting tasks, the server goes through all tasks ordered be descending priority and do some checks, if any of the checks fails, it skips the task and goes to the next. This is done until a task was found where all the checks matched or there is no task remaining.

Checks done:
- is agent trusted (in case the hashlist or files are secret)?
- is it a cpu only task and the agent has the same cpu only flag?
- if the task is small, is there already another agent assigned? <-- here maybe it should be checked if there should be another limit by the number of agents
- is the task already fully dispatched?
- etc.

**Comment by agentlimit** [comment]
Ok.  Thank to  your reply.
I tried to  change  sime codes to assign agent 1number  as you mention it.
For  limitting assign agents I tried to modify 
some code. But hashtopussy is not working   correctly.  What do you  think that   i missed?

1. changed it to input variable from select to line editor in php & html(pretask  and normal  task).
2. Checked IsSmall  field  in DB changed.  It changed.
3. Removed keyspace code if it is small  task because of treating as  normal task.
4.  Changed  getIsSmall() check code  in TaskUtils.

**Comment by s3inlc** [comment]
Hmm that's difficult to say what you missed. There are quite some places where the isSmall value is checked or used. Currently I cannot help you a lot with it, if it's not very urgent we can keep this issue open and I can add it at a later point.

**Comment by agentlimit** [comment]
Thanks.  :-)
Anyway  I try to. 
 Thanks  again your  reply.
