### ISSUE TITLE
The latest Hashcat(4.1.0) does not work with Hashtopolis on Windows

### ISSUE THREAD

**Issue by Matthijz98** [s3inlc/hashtopolis#329]
The latest Hashcat does not work with Hashtopussy
When i try to do anything i get "./hashcat.hctune: No such file or directory" i looked bu the file is in the hashcat directory. And when i run hashcat with the options Hashtoppussy wants to use it works just fine.

**Current Client version:**  0.4.3

**Your current Hashcat version:** 4.1.0

**The exact task command you are trying to run**
-a3 #HL# -1 ?l?u?d ?1?1?1?1?1?1?1?1

**Debug output from the client by running "hashtopussy.exe debug"**
{"action":"chunk","response":"SUCCESS","status":"OK","chunk":2621,"skip":49070080,"length":1794048}
C:\Users\mzond\Downloads\hashtopussy\hashcat\hashcat64.exe   --hash-type=1000 -a3 "C:\Users\mzond\Downloads\hashtopussy\hashlists\2"  -1 ?l?u?d ?1?1?1?1?1?1?1?1 --outfile-check-dir="C:\Users\mzond\Downloads\hashtopussy\hashlists\zaps2"  --potfile-disable --quiet --restore-disable --session=hashtopussy --status --machine-readable --status-timer=5 --outfile-check-timer=5 --remove --remove-timer=5 --separator=: -s 49070080 -l 1794048
./hashcat.hctune: No such file or directory
Attack finished

**Describe your problem in as much detail as possible " It's broke " is not a description.**
![error](https://user-images.githubusercontent.com/17087153/36490714-339570f6-1729-11e8-9774-263d73b29cf7.png)

**Comment by winxp5421** [comment]
Thank you for informing us! we will look into this as soon as we can.

**Comment by chadgough** [comment]
any idea how to downgrade temporarily?

**Comment by winxp5421** [comment]
Delete hashcat folder on client machines and remove the hashcat4.1 entry from the server. This should force your clients to redownload 4.0.1

**Comment by chadgough** [comment]
hmm.  the old URL no longer seems to work:  https://hashcat.net/files/hashcat-4.0.1.7z

**Comment by chadgough** [comment]
never mind.  i'm slow today.  https://hashcat.net/files_legacy/hashcat-4.0.1.7z

**Comment by winxp5421** [comment]
Old versions of hashcat get pushed to hashcat.net/legacy_files

**Comment by chadgough** [comment]
all fixed.  be nice to be able to edit the url in web-ui.  seems you can't delete entries from the server if a client is registered with that version.  had to delete and re-add client with new token.

**Comment by s3inlc** [comment]
It's definitely a windows only issue as Hashcat changed the way the determine the paths and this does not work when calling Hashcat from outside the Hashcat directory itself. On Linux and OS X there should be no such problems with using Hashcat 4.1.0.
I will take care to find a solution for this.

**Comment by Matthijz98** [comment]
Thanks for the update.
Would using the absolute path be a option?

**Comment by s3inlc** [comment]
I didn't try yet, but I doubt that this will make a difference.

**Comment by Matthijz98** [comment]
Oke I though because all the other files(hash and wordlists) use the absolute path.

**Comment by s3inlc** [comment]
Just to be sure I checked, but it does not matter if you call it by relative or absolute path. Hashcat does not like to be executed with another working directory than the hashcat folder itself.

**Comment by s3inlc** [comment]
The python agent should now support also hashcat 4.1.0, the code is available in this branch: https://github.com/s3inlc/hashtopolis-agent/tree/python-fixes

Please test with it and report back.

**Comment by s3inlc** [comment]
As both clients are suporting hashcat 4.1.0 and there was no problem reported so far when running the fixed clients with version 4.1.0 I assume this issue can be closed.

Please re-open if there is still a problem with this exact hashcat version.
