### ISSUE TITLE
[question] What happen when finished job??

### ISSUE THREAD

**Issue by agentlimit** [s3inlc/hashtopolis#334]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage.
0.5.0alpha
Current Client version
Python client
Your current Hashcat version
4.0.1
The exact task command you are trying to run.
.
Debug output from the client by running "hashtopussy.exe debug"

Describe your problem in as much detail as possible " It's broke " is not a description.

I am doing  chage  some  codes  in  htp based alpha ver.
I faced strange thing that is whether the supertask job  finished  the  agents which assigned that  taskid  try to get same task.
 Agents cannot  get  chunk data  because of finishing  that  task . So  HTP looks like hang or stop.  But  that  supertask  is deleted  then  HTP continue  working.
Why  does it  happend? When  a  task finished  what does HTP do working??

Always  thanks.

**Comment by s3inlc** [comment]
To clarify, the task is fully completed (all chunks are 100% done) or do you talk about the case when only one chunk is remaining and all agents except the one which works on this one should move on to the next task?

**Comment by agentlimit** [comment]
The  task is  fully. Of course, server say  the task  is  done. But all  agents  try to get same task id.
That  is, server said  task having  110 id  is done but all  agents assigned that task try to get  110 task job and  print err message.
But  I dont know clearly  that  is  bug or due to midify I do. 
So  I wonder  what server acts for next task when finished  job.

**Comment by s3inlc** [comment]
What priority does this task have (and what priority does the corresponding supertask have?)

Normally when a task is finished, the agent will either get the next task (if there is any matching one with priority higher than 0) or just idle and waiting for new tasks.

**Comment by agentlimit** [comment]
Super task has 2 priority and sub tasks (pre configured task) included the  super task have  1 to 10. 
When sub task having 8 finished it is appeared the error(looks like ?).
The sub job is removed or deleted then continue as corrcetly. The status isn't always appeared. So i confused :(

**Comment by silvanheller** [comment]
> I am doing chage some codes in htp based alpha ver.
Did you modify the Sourcecode of Hashtopussy? If so, can you link to the github fork with your modifications?

**Comment by agentlimit** [comment]
Because I posted it on my phone so making many mistakes. 
The code mofied is too small to fork and , of course, it will be  done  i  will do. 
 Always thanks.

**Comment by agentlimit** [comment]
My god

**Comment by agentlimit** [comment]
I found why the status which request  finished task included  supertask does occurred.
When a agent requests task or chunk then server  does check  the  task completed or dispatched using checkTask () in server.php.
Then it calls TaskUtils::checktask() for checking whether finished or  not.
chechtask () in taskutils do check complete and dispatch variable is same task->keyspace.  In this time  it`s checking error.
So  i  changed  158  and 169 line in taskutils.class.php  . 
if ( $completed == $task->keyspace )  to
if ( $completed >= $task->keyspace ) and
if ( $dispatch == $task->keyspace ) to
if ( $dispatch >= $task->keyspace )
then it works well and return null task.
( the code as above is on my memory so it isnt correct)

Thanks.
