### ISSUE TITLE
pause task?

### ISSUE THREAD

**Issue by zl9801** [s3inlc/hashtopolis#335]
A new task, loading the combination rule, can it pause the task?

**Comment by s3inlc** [comment]
Can you please describe your question more detailed. Which task and at which point would you like to pause it?

**Comment by zl9801** [comment]
Yes,i  want pause the task.
Pause the task instead of suspending one of the rules in the composite rule.

**Comment by zl9801** [comment]
Yes,i want zhe task to pause.
Pause the task, not pause the superhashlist.

**Comment by winxp5421** [comment]
Change the priority to zero and unassign all of the agents. 

If you are unwilling to give us a better description I'm unwilling to give you a better answer.
The more effort you give us the more effort you will get in return.

**Comment by s3inlc** [comment]
Currently there is no functionality to do this in one click. I can keep it as a feature request here.

**Comment by zl9801** [comment]
Thank you for your reference.
One button cancels  a task for all agents .
Can you talk a little bit about the process? Maybe I can do this on my own.

**Comment by s3inlc** [comment]
There is a `unassignAllAgents()` method in the TaskUtils which unassigns all agents working on tasks of a specific hashlist. You can create a method to unassign all agents of a task based on this method and then you just have to call it from a handler.

**Comment by zl9801** [comment]
Thanks
