### ISSUE TITLE
Usually  how do you  run hashtopolis agent??

### ISSUE THREAD

**Issue by agentlimit** [s3inlc/hashtopolis#338]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any Hashtopolis webpage.
0.5.0
Current Client version
Python 
Your current Hashcat version
4.0.1
The exact task command you are trying to run.
.
Debug output from the client by running "hashtopolis.exe -d"
Python3 hashtopolis debug

Describe your problem in as much detail as possible " It's broke " is not a description.

During running on normal task,  it found key then  server send "stop" to agent then die agent due to os.killpg() in hashcat.py inside python agent.

I think it occurred howto run it.
Usually  I run " screen -dmS hashtopolis hashtopolos.zip" on  linux system. 
The  function os.killpg for stopping  child process kills  SCREEN process. For this  any  idea or how to run agent??

Thanks.

**Comment by s3inlc** [comment]
Can you please test if the fix on this branch solves the problem: https://github.com/s3inlc/hashtopolis-agent/tree/bug/killpg

**Comment by agentlimit** [comment]
Thanks  i will  test  and  report it  at  next week.
Have a good  weekend

**Comment by agentlimit** [comment]
I tested it  and  good  work.

Thanks

**Comment by s3inlc** [comment]
thanks for reporting back, I'll merge the branch into master soon.

**Comment by pccheck** [comment]
I'm not understanding how it works.
my server recognizes the agent but does not perform any tasks
I execute at the prompt
python hashtopolis.zip
and this only appears:
Starting client 's3-python-0.4.0.1' ...
Collecting agent data ...
Login successful!
Hashtopolis Server version: 0.10.1
Client is up-to-date!

**Comment by winxp5421** [comment]
This is not where you get support for this project github issues are for bugs.

**Comment by pccheck** [comment]
sorry, ok
