### ISSUE TITLE
Hashtopolis will not compute available keyspace (linux, csharp)

### ISSUE THREAD

**Issue by satcom886** [s3inlc/hashtopolis#342]
Using the latest client (0.51.9) and server (0.5.0-rc1). When assigned a task, that has does not have the keyspace computed to a Linux client, the client will begin with a benchmark using /home/satcom886/apps/hashtopolis/hashcat/2/hashcat64.bin. When the benchmark finishes, it seems that hashcat32.bin is being called to compute the available keyspace, that results in this error:

I also tried changing hashcat binary name (on server - crackers) to hashcat64, but then, the benchmark will not start, because it calls the file hashcat6464.bin.

STATUS 11 SPEED 3488 1000 EXEC_RUNTIME 410.221999 CURKU 0 PROGRESS 131072 218340105584896 RECHASH 0 1 RECSALT 0 1 TEMP -1 REJECTED 0
hashcat (v4.0.1) starting...
Hashes: 2 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Applicable optimizers:

Zero-Byte
Single-Hash
Single-Salt
Brute-Force
Slow-Hash-SIMD-LOOP
Password length minimum: 8
Password length maximum: 63
Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.
Watchdog: Temperature retain trigger disabled.
[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit =>
Runtime limit reached, aborting...
Runtime limit reached, aborting...
Runtime limit reached, aborting...
Runtime limit reached, aborting...
Runtime limit reached, aborting...
Runtime limit reached, aborting...

Runtime limit reached, aborting...

Runtime limit reached, aborting...

STATUS 11 SPEED 3488 1000 EXEC_RUNTIME 410.221999 CURKU 0 PROGRESS 131072 218340105584896 RECHASH 0 1 RECSALT 0 1 TEMP -1 REJECTED 0

Runtime limit reached, aborting...
Started: Fri Mar 9 20:50:12 2018

Stopped: Fri Mar 9 20:52:10 2018

**Comment by s3inlc** [comment]
You wrote that the client first does a benchmark and then calculates the keyspace? Is that really executed in this order?

**Comment by satcom886** [comment]
Yes, I think it is...
Give me a moment, I will send the full output.

**Comment by satcom886** [comment]
[output.log](https://github.com/s3inlc/hashtopolis/files/1800235/output.log)
After the benchmark is sent to the server (last line of the log I sent you), the client gets reassigned to a different task.

**Comment by satcom886** [comment]
IKNOWWHATTHEPROBLEMIS!!!!!
It appears, that hashcat has a minimum password length of 8 characters, but my passwords are just 6 characters. Still, there should be some simple error message like: "Your attack command has only %number% characters. Minimum is 8."

**Comment by s3inlc** [comment]
But on the benchmark on your log you sent the length of the bruteforce task was length 8?

**Comment by satcom886** [comment]
That is weird...my attack command was -a3 #HL# ?uld?uld?uld?uld?uld?uld

**Comment by s3inlc** [comment]
just to be sure, keep in mind that you cannot write ?uld directly. You need to do -1 ?u?l?d ?1?1?1?1?1 etc.

**Comment by satcom886** [comment]
Ok, I probably used -1 ?u?l?d ...

**Comment by s3inlc** [comment]
Ok, so back to the original problem. If it failed because you only had passwords with length 6, you sent the wrong output.log.
Hashtopolis has no way to test if the passwords do not match for the hash type, hashcat just rejects the values which do not match the minimum requirements.

**Comment by satcom886** [comment]
I don't even know what is happening...
I just created a new hashlist and task (8 characters) and everything works...

**Comment by satcom886** [comment]
Ok, so I tried with many different hashlists and everything seems to work just fine...
I even tried 6 characters and it works!
So It was probably a mistake on my side, sorry I will do more research next time.
Pleasure to work with you! Closing the issue...

**Comment by s3inlc** [comment]
Thanks for the feedback.
