### ISSUE TITLE
Agent "stuck" with "Got task with id: xx"

### ISSUE THREAD

**Issue by hops** [s3inlc/hashtopolis#343]
Server version: commit c0d7196 branch master
Python client version: commit a177fbc branch master

An agent can get stuck in a loop when trying to get a new chunk.
The message is always: "Got task with id: xx".
This happens if a task dispatched 100% of it's keyspace but not all dispatched chunks are finished yet.
As soon as 100% of the keyspace has been searched the agent picks up the next task in the queue.

**Comment by s3inlc** [comment]
Issue is fixed in the newest master commit da8fc2fe861d1ad18983bceeea8905b484aadde9
