### ISSUE TITLE
Question: Hashtopolis on ARM?

### ISSUE THREAD

**Issue by satcom886** [s3inlc/hashtopolis#344]
Hey, I would like to ask a basic question. IF Hashcat was ported to ARM (to run for example on a Raspberry Pi), would it be too big of an effort to modify the hashtopolis agent to run on ARM?

**Comment by s3inlc** [comment]
I'm pretty sure that Hashcat will not be ported to ARM (at least not officially). But the hashtopolis client should run on an ARM architecture without any problems. The clients also supports generic hash crackers (e.g. self-written) which you then can also let run on ARM computers.

You can look here for an example of a generic cracker: https://github.com/s3inlc/hashtopolis-generic-cracker
And take a look here for more informations on generic crackers: https://github.com/s3inlc/hashtopolis/blob/master/doc/README.md#generic-crackers

I hope this helps you.

**Comment by satcom886** [comment]
Ok, thanks for your info!
