### ISSUE TITLE
keySpace ,How to set the best?

### ISSUE THREAD

**Issue by zl9801** [s3inlc/hashtopolis#346]
GPU  GTX980,GTX1080.
RAR,MD5 For example.
I'm very confused about this.

**Comment by winxp5421** [comment]
I have absolutely no idea how to help without more information. 
What exactly is your question because the current question "How to set the best keyspace?" does not make sense to me. 

If you are having issues please describe what the problem is in as much detail as possible.

**Comment by zl9801** [comment]
Sorry, task details -> Chunk size , How to set the best?
It feels like the GPU can't be the most efficient.

**Comment by winxp5421** [comment]
This depends on what benchmark mode you are using. and the task you are running. 

There is a reason we have an issue template to fill out when you first open an issue.

**Comment by zl9801** [comment]
Your current Server version located at the bottom of any Hashtopolis webpage.
0.5.0-rc1

Current Client version
Windows 0.52.1 csharp

Your current Hashcat version
 v4.1.0

The exact task command you are trying to run.
rar type
-a0 #HL# password.txt
-a3 #HL# ?l?l?l?l?l?l?l?l?l?l
md5 type
-a3 #HL# ?l?l?l?l?l?l?l?l?l?l

Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

Describe your problem in as much detail as possible " It's broke " is not a description.
