### ISSUE TITLE
New User Permissions Request

### ISSUE THREAD

**Issue by marcus-brutus** [s3inlc/hashtopolis#347]
SERVER:        Hashtopolis: 0.5.0-rc1
CLIENT:         Windows 0.52.1 csharp
HASHCAT:     v4.1.0

Not command specific issue/request.

I really like the improvements with the new version!  I have had some minor bumps, and will submit them as issues once I'm sure they are not a factor due in my environment or something I'm otherwise doing wrong.  Great work!

I think I have a use-case for a new User Group, kind of between a 'Read Only User' and a 'Normal User'.  It might be easier to just slightly adjust existing groups. I'm also open to the possibility that I just don't clearly know how to configure Users and Groups, in which case pointing me in the right direction would be helpful.  Apologies if I'm missing something obvious.  Basically, I have a server shared with a couple of 'hacker' friends, where trust and anonymity are a bit of an issue.   Right now, I just have all accounts locked to 'Read Only' as a temporary solution to prevent the type of nonsense detailed below.

Currently, 'Normal Users' can see all Agents, including their public IP address connection information.  One user on my system used this information to DDOS another user, and in another instance, someone staged a 'penetration test' and actually managed to get in due to the target user having very poor security posture (his router was accessible remotely, and had default credentials... yep).  'Normal Users' can also make agents they don't own active or inactive, and assign them to tasks. This has also been used 'inconveniently' by users on my system.  

Lower priority things: 'Read Only' users can see all hashlists and files.  There does not appear to be a way to hide certain sensitive hashlists from other users.  Basically, giving someone 'Read Only' access is giving them total access to all hashlists on the system. This is an issue because if I'm using the server for something potentially sensitive (i.e. work) I need to basically just deactivate all other accounts temporarily while the project runs as I haven't found any other way yet to restrict users.

Ideally, the perfect group would allow:
* Create new agents owned only by their account.
* Be unable to see, change, or start any agents not owned by their account.
* Be able to create new tasks, but not see tasks created by other users
* Be able to add hashlists, but not able to see hashlists created by other users.

Thanks in advance!

**Comment by s3inlc** [comment]
Thanks for your detailed descriptions. I'll try to give you some more details which might solve parts of your problems.

* **IPs**: In the server config (section UI) you can select to hide IP information, this way no users see the IPs of any agent. 
* **Hashlists**: With the new access groups you can have hashlists in different access groups so certain users only see some of the hashlists. Please read here some details about access groups: https://github.com/s3inlc/hashtopolis/wiki/Detailed-Explanation:-Groups

With files you are right. There is currently no possibility to hide files from certain users. That might be something to change in the future, that files also belong to access groups and therefore also can only be seen by certain users.

But I can keep this issue open and when I have some time I could try to create such a user group.

**Comment by winxp5421** [comment]
Ultimately in the big project picture in my head. I would like to move away from statically assigned permissions to groups and only ship HtP with an admin group. Pushing users to create their own groups as they see fit. This would allow for a much more customizable and granular control over the "platform". 


  | View Hashlists | Create hashlists | Create Agents | Agent Admin | Vew files dir | View Secret files
-- | -- | -- | -- | -- | -- | --
Group1 | Yes | No | Yes |   |   |  
Group2 |   | Yes |   |   | Yes |  
Group3 |   |   |   |   |   | No


However, S3in!c is a one-man band. I just don't see this kind of group management as a high priority. There is not enough functionality gain to spend the time on it. I feel the time should be spent on other more important things. In the future, this is how I would like to see groups handled. There is simply just many more important things that require attention.

**Comment by marcus-brutus** [comment]
Oh wow.  Thanks!  You can go ahead and close this, between the 'hiding IP addresses' setting and the new groups, this solves my current use case and issues.

Thanks for pointing out what I missed, and also appreciated that you didn't rub my nose in it.

Do you guys need any help with documentation?   I should have some time over the next week weeks to fill in some gaps if that would be helpful.

**Comment by marcus-brutus** [comment]
Forgot that I can close the issue myself... apologies, I'm new with github.  

Also plus one to an eventual modular 'groups' approach as winxp5421 suggested.

**Comment by winxp5421** [comment]
Yes Please feel free to add or modify documentation. Make your modifications and submit a Pull request I will review and commit. We welcome any and all help no matter how small you think the contribution is. 

@marcus-brutus No, thank you for taking the time to write your issue / request in detail. That not a thing we see very often and we appreciate that you took the time to make your problem very clear and well written!

**Comment by s3inlc** [comment]
I would like to reopen this issue and discuss about the approach for the modular groups. I think this is the right solution and I would like to collect the actions which should be configurable.

My starting list:

* View Hashlists/Superhashlists
* Create Hashlists
* Create Superhashlists
* View Agents
* Create Agents
* View Tasks
* Create Tasks
* Create Preconfigured Tasks
* Create Supertasks
* View Files
* Add Files
* Cracker Binaries Access
* Server Config Access
* User Config Access

The reason why I think this has some priority to be added is because I have plans to create a client API for managing stuff via the API and for this it would be good to have a good access management first.

**Comment by s3inlc** [comment]
Permission feature is included in the newest release, so I guess I can close this issue now.
