### ISSUE TITLE
BTC Integration

### ISSUE THREAD

**Issue by sphereict** [s3inlc/hashtopolis#349]
Hi Team
Is it possible to use a payment gateway for BTC that will allow a user to create a task only after BTC payment has been made. 

I would appreciate it if you can assist with this in the event that it is possible. 

You can mail me directly on gmohr01@gmail.com

Looking forward to your reply.

Sincerely.
G

**Comment by winxp5421** [comment]
No. Not in a million years. Just no.

**Comment by sphereict** [comment]
Ok understood, thought It would be a nice service to give to others who could not afford to own systems.

thank you for the reply.

**Comment by winxp5421** [comment]
While i understand where you are coming from. Seriously i do.

I only see a service like this being used by people with nefarious intent. No decent person with good intent is going to hand over legitimate hashes to "some website" on the internet to crack. I just don't see that happening.

The business model I see here is Bad people paying to do bad things. There might be a legitimate person here or there but, an overwhelming percent is going to be people using the service for illegal activity. This "model" or implementation is only going to further drag the people trying to do good in the password community through the mud. 

This is why I say no. hell no. There will not be any kind of payment processor built into Hashtopolis.. EVER. Period.
