### ISSUE TITLE
WPA2 Convert to HCCAPX problem

### ISSUE THREAD

**Issue by sphereict** [s3inlc/hashtopolis#351]
Hi

I keep on getting invalid hccapx when trying to perform a crack on WPA2 handshake.

I used the captured handshake and ued hashcat utils to convert to hccapx and when start to crack the system shows invalid hccapx .

am I doing something wrong ?

Please asisst.

Sincerely.
Gerhard

**Comment by s3inlc** [comment]
It's hard to see where the problem appears with that less information.
Are you running hashcat directly? Where is the error printed? Did you check that you have the full handshake captured?

**Comment by sphereict** [comment]
Doing a new test and recapture handshake to make sure will provide results in a few

**Comment by sphereict** [comment]
HI
I checked the handshake with Wireshark and the complete handshake was not captured. Also there was allot of rubbish in between.
I re-captured the file and cleaned it up and now its working as it should.
Sincerely.
G
