### ISSUE TITLE
Can the generic cracker run on Linux?

### ISSUE THREAD

**Issue by satcom886** [s3inlc/hashtopolis#352]
I have tried to run the generic cracker on my Ubuntu rig and a Raspberry Pi. Both have the same output:

mono cracker.exe
Cannot open assembly 'cracker.exe': File does not contain a valid CIL image.

I would like to try and run the generic cracker on Windows PCs without OpenCL support, a few Raspberry PIs and Android phones/tablets (using Linux Deploy). Also, I would like to ask if there is a way to distribute WPA2 cracking with hashtopolis without using hashcat.

**Comment by s3inlc** [comment]
You should compile the cracker for the system you would like it to run. 

It's possible to implement WPA2 yourself, but I think it will be a lot of work. If you really want to go that way, I recommend that you first try to get it running with the example (with MD5) and if it works then you can implement your own cracker.

**Comment by satcom886** [comment]
Ok, so I have to compile it myself on the platform I want to run it on. Are there any dependencies? To build it, I just download the source and type "make"?

**Comment by s3inlc** [comment]
You need the qt5 libraries (minimum the core one) and then you need to run `qmake cracker.pro` and then `make`.

**Comment by satcom886** [comment]
I ran into an issue when running make:

runthread.cpp: In member function ‘virtual void RunThread::run()’:
runthread.cpp:87:85: error: ‘floor’ was not declared in this scope
             cout << "STATUS " << (int)floor((double)lengthCounter/this->length*10000) << " " << (int)(((double)(lengthCounter - lastCounter))/(time(NULL) - lastUpdate)) << endl;
                                                                                     ^
runthread.cpp:97:85: error: ‘floor’ was not declared in this scope
             cout << "STATUS " << (int)floor((double)lengthCounter/this->length*10000) << " " << (int)(((double)(lengthCounter - lastCounter))/(time(NULL) - lastUpdate)) << endl;
                                                                                     ^

**Comment by s3inlc** [comment]
This is when compiling on LInux?

**Comment by satcom886** [comment]
Yes.

**Comment by s3inlc** [comment]
In runthread.h add this include `#include <cmath>` and try again.

**Comment by satcom886** [comment]
It has now compiled successfully. I have tried to run the cracker file, but I got Illegal memory access (SIGSEGV). Any Idea? Also, If I need to compile for each device, how do I add this cracker to hashtopolis cracker list? Do I just put in the link to the source and manually install the dependencies on the client before running hashtopolis?

**Comment by s3inlc** [comment]
Did you just run it without any arguments? The cracker is programmed really simple and if you don't provide the right arguments it often just crashes. You can take a look at the generic cracker description https://github.com/s3inlc/hashtopolis/tree/master/doc

You don't need to compile it for every device as long they have the same OS and architecture. You just need to install the dependencies and then you can pack the binary into a 7z which you can then provide on a link and this link you have to enter as cracker binary on the Hashtopolis server.

**Comment by satcom886** [comment]
Thanks! This was very helpful!

**Comment by s3inlc** [comment]
You're welcome. Just remember that the mask attack is not implemented, so this won't work .
