### ISSUE TITLE
Feature Request - Add option to task to store crack position in database

### ISSUE THREAD

**Issue by evilmog** [s3inlc/hashtopolis#353]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any Hashtopolis webpage:
0.5.0

Current Client version:
csharp 0.52.1

Your current Hashcat version:
4.1.0

The exact task command you are trying to run:
any task

Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client:
N/A

Describe your problem in as much detail as possible " It's broke " is not a description:

In the database there is a field called "timeCracked" it is normally empty or 0 when completed, example db schema is below

mysql> describe Hash;
+-------------+---------------+------+-----+---------+----------------+
| Field       | Type          | Null | Key | Default | Extra          |
+-------------+---------------+------+-----+---------+----------------+
| hashId      | int(11)       | NO   | PRI | NULL    | auto_increment |
| hashlistId  | int(11)       | NO   | MUL | NULL    |                |
| hash        | varchar(1024) | NO   | MUL | NULL    |                |
| salt        | varchar(256)  | YES  |     | NULL    |                |
| plaintext   | varchar(256)  | YES  |     | NULL    |                |
| timeCracked | int(11)       | YES  |     | NULL    |                |
| chunkId     | int(11)       | YES  | MUL | NULL    |                |
| isCracked   | tinyint(4)    | NO   | MUL | NULL    |                |
+-------------+---------------+------+-----+---------+----------------+
8 rows in set (0.00 sec)

--outfile-format has an option for outputting crack position

hash[:salt]:crack_pos
 10 | plain:crack_pos
 11 | hash[:salt]:plain:crack_pos
 12 | hex_plain:crack_pos
 13 | hash[:salt]:hex_plain:crack_pos
 14 | plain:hex_plain:crack_pos
 15 | hash[:salt]:plain:hex_plain:crack_pos

mode 10 or 11 should give usable data, if that could be stored on a per hash database, it doesn't have to be in the GUI but if it could be stored it would allow for statistics to be collected in the backend and relative password strengths calculated

**Comment by s3inlc** [comment]
This is a good feature to add, I agree with you that the outfile format can be adjusted so the crack position can be read.

Using the timeCracked would be possible, but I would like to have it well implemented, so when I implement it I will add a new column for this, and as statistics are a wish also from other users anyway, this could be included also in a GUI way then.

**Comment by s3inlc** [comment]
The client is now getting the full output from hashcat (mode 15) and sends it to the server, where it can now store the crackpos which also can be viewed in the hashes view if necessary.
Both client and server currently include this in the current-dev branch.
