### ISSUE TITLE
Preconfigured tasks not assigning files

### ISSUE THREAD

**Issue by evilmog** [s3inlc/hashtopolis#354]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any Hashtopolis webpage.
Hashtopolis 0.5.0
Current Client version
N/A
Your current Hashcat version
4.1.0
The exact task command you are trying to run.
#HL# -a 0 dict.dict -r rule.rule
Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.
N/A
Describe your problem in as much detail as possible " It's broke " is not a description.

Creation of a preconfigured task works fine, assigns files etc, but when clicking on a superhashlist and trying to assign a preconfigured task the assigned files come out blank on the new created task

**Comment by s3inlc** [comment]
Please test again with the newest commits in the master branch, issue should be fixed.

**Comment by winxp5421** [comment]
I will be closing this issue if you feel this issue was closed in error please re-open and explain why.
