### ISSUE TITLE
Feature Request - Bulk Wordlist and Rule addition

### ISSUE THREAD

**Issue by evilmog** [s3inlc/hashtopolis#355]
I'd like to request a new feature for hastopolis.  If we could do a bulk wordlist and rule addition that would be great.

Theory would be you select a checkbox to specify mode -a 0 (or any other attack mode that supports rules), then you select the wordlists and then select your rules as well as the hashlist to apply it to and it would create individual tasks for each rule and wordlist.

Example: wordlist1, wordlist2, rule1, rule2, checkbox for -a 0, it would create -a 0 wordlist 1 -r rule 1, -a 0 wordlist1 -r rule2, -a 0 wordlist2 -r rule1, -a 0 wordlist2 -r rule2 and each would be named hashlist wordlist1 -r rule1 etc.

This would allow rapid creation of tasks, ideally these could become a supertask if that option was checked.

**Comment by s3inlc** [comment]
I agree, that would be a good option to create a larger bulk of tasks. 

Ideally as you wrote this would be good to be implemented as supertask creation, which then can be applied. I think that's the most convenient way to handle this.

**Comment by winxp5421** [comment]
#122

**Comment by s3inlc** [comment]
The bulk supertask creation is now implemented and available in the current development branch. It will be included in the next release.

**Comment by winxp5421** [comment]
Implemented https://github.com/s3inlc/hashtopolis/pull/464
