### ISSUE TITLE
I am not able to upload a wordlist for a new installation.

### ISSUE THREAD

**Issue by rye2016** [s3inlc/hashtopolis#358]
Greetings!  I am familiar with Hashcat, but am new to Hashtopolis.  I followed the instructions the following video:
 
https://www.youtube.com/watch?v=u1ZDQLFV0Bo&feature=youtu.be
 
The only thing I did differently, was use the latest version.  Below is what I have:
 
Hashtopolis: 0.5.1
Ubuntu: 17.1
Apache: 2.4.27
 
I had no issues with the installation process - so it seems.  After completing the setup and adding a client I decided to add a word list.  I have been doing the following:
•	Click on the "Files" menu.
•	Clicked the "Add file" button.
•	Clicked the "Browse…" button and selected my wordlist (rockyou.txt).
•	Clicked the "Upload files" button.
 
I then get the message "Successfully added 0 files!".  Below I have provided a screenshot.
 
I have tried multiple browsers.  I also logged into the server directly to try the upload, I ended up getting the same message.  My first thought is this is a permissions issue, but I am not sure how to check that.
 
Please let me know if any additional detail is needed. 

Any direction would be greatly appreciated.

Many thanks!

![screenshot](https://user-images.githubusercontent.com/16514005/38396236-9bfed0ea-38eb-11e8-8e16-bbf93b33673a.jpg)

**Comment by rye2016** [comment]
winxp5421,

Thank you so much for your fast response.    I changed the following parameters to 1024 in php.ini and it worked:

-	memory_limit
-	upload_max_filesize
-	post_max_size

I have had no issues with Ubuntu 17.1, however, please let me know if I should refrain from using it – I do see that the documentation specifically says 16.1.

Thanks again!

**Comment by winxp5421** [comment]
There shouldn't be any major issues with 17.10. we specifically say 16.04 because that's what we test on. Glad you got it working please close the issue if your problems are resolved.
