### ISSUE TITLE
Task.php

### ISSUE THREAD

**Issue by Maxiz80** [s3inlc/hashtopolis#361]
Hi.
I use the latest version 0.5.1.
When I click on "Show Tasks" the page start to load but doesen't show anything

**Comment by winxp5421** [comment]
In ./Inc/load.php Please set 'ini_set("display_errors", "0");' to 'ini_set("display_errors", "1");' and try to load the page again. Report any errors you may see.

**Comment by Maxiz80** [comment]
Out of memory (allocated 2097152) (tried to allocate 19387780 bytes) in C:\xampp\htdocs\dba\AbstractModelFactory.class.php on line 521

**Comment by winxp5421** [comment]
That error message kinda says it all. You don't have enough ram or your phone settings are incorrect.

**Comment by Maxiz80** [comment]
I've 8Gb of ram.. Which PHP settings should I check?

**Comment by winxp5421** [comment]
Memory_limiy would be a decent starting place. ( I hate xampp btw)

**Comment by Maxiz80** [comment]
Thanks a lot.
Solved

**Comment by winxp5421** [comment]
Before this comes up in a future issue xammp in a windows environment does not run a 64 bit environment. Running large tasks with keyspaces above 32 bit integers will simply not function.
