### ISSUE TITLE
probleme with new version 0.5.1

### ISSUE THREAD

**Issue by EgoETEK** [s3inlc/hashtopolis#363]
hello here , 

my problem is : when i select dictionary , my agent never start .
when im using :  #HL# -a ?l?l?l?l?l <-- all work
when im using : #HL# rockyou.txt <-- never start , Dispatched : Keyspace unknown
i have try #HL# -a 3 rockyou.txt or -a 1 .

i have over 50 dicitonnary . try with many of them .

and secondary . i have hashcat 3.30 . 3.60  4.0.0 4.0.1  4.1.0 ( i have selected all )

my file are .hccap ( for 3.30 try this one )
and .hccapx for other version

i have try 4 different hcccapx too

thanks , sorry for my bad english , good work :)

**Comment by winxp5421** [comment]
Please verify that you have added the hccapx files as "hcappx format". They are not plain text file format. Hashtopolis does not support hccap file format they must be hcappx

**Comment by s3inlc** [comment]
Keep in mind that when cracking WPA that the minimal length is 8 chars, so all masks below this length will not work and also when using wordlists, it is better to have only length 8 and longer words in there.

Do you have some log output of an agent and some sort of chronological events for such a case where it does not work?

**Comment by EgoETEK** [comment]
[https://imgur.com/a/B6jsq](https://imgur.com/a/B6jsql)

here a screenshot . 
Format: | HCCAPX ( 2500 )

**Comment by s3inlc** [comment]
Ok, first guesses, either your agent is not activated or not trusted. In both cases it would cause the server to not give this task to the agent.

**Comment by EgoETEK** [comment]
my list is 8 lenght char

https://imgur.com/a/Rh7pd

**Comment by EgoETEK** [comment]
have any discord group or something for help ? ^^,

**Comment by winxp5421** [comment]
Your agents are not "Trusted" please change this in the agent details page. by clicking on the Agents name and enabling "trusted".

I am closing this issue. If you feel this issue has been closed in error please reopen and explain why.
