### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Maxiz80** [s3inlc/hashtopolis#364]
Hi.
Would it be possible to add in task.php page a button to reassign all agents to a single task?

**Comment by winxp5421** [comment]
You can effectively do the same thing by setting a task to a priority higher than all the other tasks. Once the client finishes the current chunk it will move to the highest priority task. ( Force moving clients is not recommend )

**Comment by Maxiz80** [comment]
I don't want to open another ticket..
Can you help me to understand the difference between dispatched and searched?
On my task I've 42/78%

**Comment by winxp5421** [comment]
Dispatched= keyspaces allocated to your agents
Searched= keyspaces your agents have reported complete. ( Or searched)

**Comment by winxp5421** [comment]
I will be closing this issue if you feel this issue was closed in error please re-open and explain why.
