### ISSUE TITLE
Consequential characters

### ISSUE THREAD

**Issue by Maxiz80** [s3inlc/hashtopolis#365]
Hi.
Is it possible to use https://github.com/hashcat/maskprocessor/releases/ in order to perform special mask?

**Comment by s3inlc** [comment]
Can you explain more detailed what you would like to do?

Why not just set the mask attack for the task?

**Comment by Maxiz80** [comment]
You're right.
I can use mask but I can't set two good parameters.
Max consequential and recurrence characters that I don't find in hashcat

**Comment by winxp5421** [comment]
Closing this issue. If you feel this has been done in error please reopen and explain why.
