### ISSUE TITLE
PHP 5.5.21 appears not work with hashtopolis

### ISSUE THREAD

**Issue by jforsec** [s3inlc/hashtopolis#366]
Hello.

I try to install hashtopolis with PHP 5.5 as recomended by wiki without of luck.

OS : CentOS 7.0
Nginx : 1.12.2
PHP (PHP-FPM) : 5.5.21

Message in log

[23-Apr-2018 18:42:38 UTC] PHP Fatal error:  Arrays are not allowed in class constants in /usr/share/nginx/html/h/inc/defines/deviceCompress.php on line 12

For fix problem i move to PHP 5.6.25 and now work.

Please fix wiki.

Thanks.

**Comment by s3inlc** [comment]
Thanks for the notification, I changed it on the wiki. 
But please note, we do NOT recommend to use 5.6 (or 5.5) before, we recommend to use PHP 7.0.
