### ISSUE TITLE
hashtopolis.exe can not download hashcat from my ubuntu server

### ISSUE THREAD

**Issue by justbluesky** [s3inlc/hashtopolis#371]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any Hashtopolis webpage.
Hashtopolis: 0.5.1

Current Client version
Client Version 0.52.1

Your current Hashcat version
Hashcat 4.1.0

The exact task command you are trying to run.
#HL# -a 3 ?l?l?l?l?l?l

Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.
user@ubuntu:~/hashtopolis$ sudo mono ./hashtopoli.exe -d
Client Version 0.52.1
Connecting to server http://192.168.0.202/api/server.php
System is Linux 64-bit
Existing token found
{"action":"login","clientSignature":"generic-csharp","token":"DcftbLDKcX"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Sending server client information
System is Linux 64-bit
{"action":"updateInformation","token":"DcftbLDKcX","uid":"7e83275a-6aca-4864-a9cf-a603ab18ba7f","os":0,"devices":["NVIDIA Corporation GM200 [GeForce GTX 980 Ti] (rev a1)","Matrox Electronics Systems Ltd. MGA G200eW WPCM450 (rev 0a)","NVIDIA Corporation GM200 [GeForce GTX 980 Ti] (rev a1)"]}
{"action":"updateInformation","response":"SUCCESS"}
Logged in to server
Checking for client updates
{"action":"checkClientVersion","type":"csharp","version":"0.52.1","token":"DcftbLDKcX"}
{"action":"checkClientVersion","response":"SUCCESS","version":"OK"}
You are using the latest client version
Using new STATUS codes
Getting task
{"action":"getTask","token":"DcftbLDKcX"}
{"action":"getTask","response":"SUCCESS","taskId":null,"reason":"No suitable task available!"}
No new task assigned to agent

Describe your problem in as much detail as possible " It's broke " is not a description.
1.web on server is OK.I can add hashlist,add task,add agent and add cracker binaries.
2.when i run "sudo mono ./hashtopolis.exe" in ubuntu client,it can download 7rz but cannot download hashcat from server.
how can i fix this problem?

**Comment by winxp5421** [comment]
How is your cracker binaries setup? can I get a screenshot of your config?

**Comment by s3inlc** [comment]
Based on the client log it looks like the client didn't pick up a task, so basically it does not get that far where it needs to download hashcat, as it has no task assigned. 

Make sure that if the hashlist is marked as secret, the agent is trusted and that either the priority of the task is higher than 0 (so the agent gets automatically assigned) or the agent is assigned to this task manually.

**Comment by winxp5421** [comment]
Its been 12 days without a response. If you are still experiencing problems please reopen the issue
