### ISSUE TITLE
mcrypt deprecated in php7.1 and missing from php7.2

### ISSUE THREAD

**Issue by roycewilliams** [s3inlc/hashtopolis#373]
Looks like [mcrypt is deprecated](https://secure.php.net/manual/en/migration71.deprecated.php#migration71.deprecated.ext-mcrypt) in PHP 7.1 and removed in PHP 7.2, yielding:

```
$ PHP Fatal error:  Uncaught Error:
Call to undefined function mcrypt_encrypt() in /var/www/hashtopolis/inc/Encryption.class.php:25
Stack trace:
#0 /var/www/hashtopolis/inc/Login.class.php(177): Encryption::sessionHash('7', 1525755898, 'email@example.net')
#1 /var/www/hashtopolis/login.php(25): Login->login('joeuser', '[redacted]', '')
#2 {main}
thrown in /var/www/hashtopolis/inc/Encryption.class.php on line 25, referer: https://servername.example.net/hashtopolis/index.php
```

 and the recommendation is to move to OpenSSL.

PHP 7.2 is the default in the recently-released Ubuntu 18.04, and mcrypt has been removed. (Guess how I found out ;) )

Workaround is to install via PECL. On Ubuntu 18.04:
```
sudo apt install libmcrypt-dev php7.2-dev
sudo pecl install mcrypt-1.0.1
```
... and then add `extension=mcrypt.so` to your `php.ini` and then restart Apache.

**Comment by s3inlc** [comment]
Yes, it's already prepared to change in the current milestone for the next minor update (branch `milestone/5`).

**Comment by s3inlc** [comment]
In the current release (0.6.0) mcrypt is not used anymore, so this shouldn't be a problem anymore.
