### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by Maxiz80** [s3inlc/hashtopolis#375]
Hello.
If I create a task with this configuration:
#HL#  -a 3 -m 2500 -1 ?l?d ?1?1?1?1?1?1?1?1?1?1?1?1?1
I get integer overflow on keyspace calculation..

**Comment by winxp5421** [comment]
Are you sure you are running in a 64-bit environment? 
https://github.com/s3inlc/hashtopolis/wiki/Frequent-Problems

**Comment by winxp5421** [comment]
Also 13 char ?l?d on wpa... This will never finish in a reasonable time.

**Comment by Maxiz80** [comment]
I've tried to make some filter..
My goal would be a filter with no more than 2 equal consecutive char in the password...

**Comment by winxp5421** [comment]
One of two things is your problem here. 
1. You are not running in a 64-bit environment (client OS, PHP, etc)
2. Hashcat is sending an overflow error because the keyspace is out of possibility.

In any case a 13 Char ?l?d is just a ridiculous run for WPA

**Comment by winxp5421** [comment]
On another note, I specifically warned you back in issue https://github.com/s3inlc/hashtopolis/issues/361 that xammp is not 64bit out of the box.

**Comment by Maxiz80** [comment]
In fact I'm using wamp64 now

**Comment by winxp5421** [comment]
Can you confirm that by running 
```
<?php
switch(PHP_INT_SIZE) {
    case 4:
        echo '32-bit version of PHP';
        break;
    case 8:
        echo '64-bit version of PHP';
        break;
    default:
        echo 'PHP_INT_SIZE is ' . PHP_INT_SIZE;
}
?>
```
If this script returns "64-bit version of PHP" Then try to run the same command directly with hashcat.

**Comment by Maxiz80** [comment]
In any case I need a filter for password

**Comment by winxp5421** [comment]
I have no idea what a "filter" for a password is can you elaborate?

**Comment by Maxiz80** [comment]
I mean a mask.. No triple character..

**Comment by winxp5421** [comment]
Ok, So. Im trying not to come off in a negitive way but, seriously you need to be more discriptive in your posts. There is a reason we have an issue template. We cannot just guess your working environment, what versions you are running, etc. That text in that box you decided to delete before posting a new issue helps us out a lot. 

This respository is for hashtopolis and in turn the issues section is for issues related to hashtopolis and not for "how to use hashcat" but, reguardless i will still give you an answer. 

From what i can gather from the 3 word statement of "No triple character". You are looking to do a Bruteforce without 3 characters repeating right next to each other eg. abcdddefg you are trying to avoid generating repeating characters like "ddd" in a single word.  To my knowlege you cannot do with directly with hashcat easily. It would involve creating thousands of masks or using 3rd party tools not supported by Hashtopolis. 

I would highly reccomend that you check for 64 bit php using the above script and moving away from Xampp.

**Comment by winxp5421** [comment]
Closing this as the task Keyspace is simply too large to calculate within a 64bit integer
