### ISSUE TITLE
Server Policy Issues？

### ISSUE THREAD

**Issue by zl9801** [s3inlc/hashtopolis#376]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any Hashtopolis webpage.

Current Client version
0.4.3
Your current Hashcat version
3.6
The exact task command you are trying to run.

Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

Describe your problem in as much detail as possible " It's broke " is not a description.

What is the server assignment client policy? 
Multiple clients running 8-bit character policy will there be duplicates?
-

**Comment by winxp5421** [comment]
I am not sure I understand your questions. 
What is the server assignment client policy? Do you mean how are clients assigned to a task?  This depends on how you have groups setup. 

Multiple clients running 8-bit character policy will there be duplicates? i have no idea what you mean by 8-bit char policy. Do you mean a brute-force attack 8 char long?

Hashtopolis does not issue duplicate work to clients unless something bad happens with the client.
