### ISSUE TITLE
outdated JS components (Bootstrap, jQuery)

### ISSUE THREAD

**Issue by roycewilliams** [s3inlc/hashtopolis#378]
Chrome's Lighthouse audit framework reports Bootstrap 3.3.6 and jQuery 1.11.3 both have some medium-level vulns.

Naively, i grabbed latest each, minor where I could (Bootstrap 4.1.1, jQuery 1.11.4). Both jQuery 1.11.4 and 1.12.4 are detected as insecure. UI wonkiness (centering) appears to be due to Bootstrap changes.

**Comment by s3inlc** [comment]
As the new version (0.6.0) includes an upgrade of Bootstrap an jQuery, I assume I can close this issue now.

**Comment by roycewilliams** [comment]
Yep. Lighthouse no longer complains. Thanks!
