### ISSUE TITLE
I want to add 100 dictionaries, what should I do?

### ISSUE THREAD

**Issue by zl9801** [s3inlc/hashtopolis#380]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any Hashtopolis webpage.
0.5
Current Client version
0.3
Your current Hashcat version
3.6
The exact task command you are trying to run.
#HL# -a 0  dic.txt
Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

Describe your problem in as much detail as possible " It's broke " is not a description.
I want to add 100 dictionaries, what should I do?

**Comment by winxp5421** [comment]
Copy the files into the ./import directory and add them via the gui.

**Comment by zl9801** [comment]
For example：#HL# -a 0 dic*.txt   ？？？

**Comment by winxp5421** [comment]
Ah, ok. I assumed you were talking about adding dictionaries to HtP not creating tasks using 100 dictionaries. 

Right at the moment, you have to create each task manually. So yes that means you have to create 100 tasks by hand. 

A more user-friendly way of creating tasks is already an issue and in the works for a future release. 

https://github.com/s3inlc/hashtopolis/issues/122

**Comment by zl9801** [comment]
Thanks,I'll keep an eye on you.
