### ISSUE TITLE
Ignoring Client Errors = TRUE, still sends notifiactions

### ISSUE THREAD

**Issue by winxp5421** [s3inlc/hashtopolis#382]
While a client is in the "Ignore errors" state and a basic nondestructive error comes along eg. no protocol specified. Notifications that the client is "erroring" are still being sent each time a chunk is issued to the client. IMO, Ignore should mean IGNORE and client notifications should be silenced if Ignore=TRUE

**Comment by s3inlc** [comment]
Included in the current milestone/5 branch, you can now set for every agent, if you want to completely ignore errors, if it should just save the error, but not stop him, or if he should be deactivated. (This also includes notifications, if no error is saved, also no notification is issued).
So I guess we are done here, please reopen if still something is missing.
