### ISSUE TITLE
Client is not assigned to task

### ISSUE THREAD

**Issue by zl9801** [s3inlc/hashtopolis#383]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any Hashtopolis webpage.
0.5.0
Current Client version
0.5.30
Your current Hashcat version
4.1.0
The exact task command you are trying to run.
#HL -a 0  1.txt
Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

Describe your problem in as much detail as possible " It's broke " is not a description.
agent  is not assigned to task.

**Comment by s3inlc** [comment]
There is no way I can help you here when not sticking to issue creation guidelines. Please read the issue template carefully and provide appropriate information.
Also check here: https://github.com/s3inlc/hashtopolis/wiki/Frequent-Problems#an-agent-doesnt-get-assigned-to-a-task-even-if-he-has-the-highest-priority as this might help solve a lot of problems.
