### ISSUE TITLE
Not assigned to a task.Dictionary attack.

### ISSUE THREAD

**Issue by zl9801** [s3inlc/hashtopolis#385]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any Hashtopolis webpage.
0.5.0
Current Client version
0.5.3
Your current Hashcat version

The exact task command you are trying to run.
#HL -a 0 wordlist.txt
Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.
normal
Describe your problem in as much detail as possible " It's broke " is not a description.
Agent is not assigned to task.
The same hashlist
task:
#HL -a 0 wordlist.txt    (Agent is not assigned to task.)
task:
#HL -a 3 -1 ?d?l ?1?1?1?1?1?1   (normal)
Brute-Force is OK.
Dictionary attack ,not assigned to a task.
"hashtopolis.exe -d  "  no error.

**Comment by s3inlc** [comment]
have you read the FAQ entry about tasks not getting assigned?

**Comment by winxp5421** [comment]
Your agent is not trusted. Please read the FAQ and WIKI

**Comment by zl9801** [comment]
@winxp5421  Thanks,so sorry.
