### ISSUE TITLE
Hashtopolis crack speed ?

### ISSUE THREAD

**Issue by zl9801** [s3inlc/hashtopolis#386]
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage.
0.4.1
- Current Client version
0.4.31
- Your current Hashcat version
3.6.0
- The exact task command you are trying to run.
#HL -a 3 -1 ?d?l ?1?1?1?1?1?1?1?1
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

**Describe your problem in as much detail as possible " It's broke " is not a description.**
task command : -a 3 -1 ?l?d ?1?1?1?1?1?1
A 8-card GPU 1080TI server, Hashcat 3.6.0 cracked office2013 type (office2016), a card speed 4700h/s,
8 card speed 37600h/s.
Hashtopolis assigned to GPU 1080 TI server, 8 card speed 16000h/s-24000h/s. 
How to set up to be able to close Hashcat single machine crack speed?

**Comment by zl9801** [comment]
Is it related to chunk time, please?

**Comment by zl9801** [comment]
Hashcat 3.6.0, command: test.hash -a 3 -1 ?l?d ?1?1?1?1?1?1
office2013 type (office2016), a card speed 4700h/s,8 card speed 37600h/s.GTX1080TI.

Hashtopolis 0.4.1,hashcat 3.6.0 ,command:#HL  -a 3 -1 ?l?d ?1?1?1?1?1?1
office2013 type (office2016), 8 card speed 16000h/s-24000h/s.GTX1080TI.

Hashtopolis  0.4.1 chunk default:600,i don't know how to set.

Local server.Titan 8 card server.

**Comment by Lannert** [comment]
I am using up to 4x GTX980 or 2x GTX1080 in each machine. I set the chunk size to 250000 and the total speed scaling is correct. One card 4700h/s, two cards 9400h/s and so on. Try with a chunk size gt 200000

**Comment by zl9801** [comment]
Thanks
