### ISSUE TITLE
Support for optimized kernels in SuperTasks via hcmask import

### ISSUE THREAD

**Issue by 64nickel** [s3inlc/hashtopolis#388]
Using hashtopolis 0.5.1 and hashcat 4.1, client versions 0.52.1.  Using the imported hcmask functionality.  We created SuperTask just fine using this method, and the supertask runs as expected.  

However, I noticed that each of the individual tasks within the supertask doesn't leverage hashcat 4.1's new -O option (optimized kernels).  I can't find a way to force the supertask to implement the -O switch when it builds out the individual sub-tasks that comprise the supertask.  

Example:  Instead of it having "#HL# -a 3 ?u?l?l?l?d?d?d?d", I'm trying to get it to be "#HL# -O -a 3 ?u?l?l?l?d?d?d?d".

**Comment by winxp5421** [comment]
For now a quick fix would be to add -O to the client specific parameters section but, this would enable -O for anything and everything.

As for the future I think this would be an easy feature to add to tasks. As something that can be toggled on or off.

**Comment by 64nickel** [comment]
"... add -O to the client specific parameters section..."
 
Are you referring to the "Extra Parameters" section in the agent configuration?

**Comment by winxp5421** [comment]
Correct.

**Comment by 64nickel** [comment]
Doesn't appear to be honoring the -O extra parameter.  Added it to all agents and re-ran our supertask.  Individual sub-tasks isn't showing the -O switch.  Deleted and re-created the import hcmask supertask and still not showing -O.  Cracking speeds are comparable to not using the -O switch from our previous benchmarks.  Does something need to be restarted?

**Comment by s3inlc** [comment]
Which agent type are you using?

**Comment by 64nickel** [comment]
csharp for Windows

**Comment by s3inlc** [comment]
Any chance that you can run the python agent and test if it works with this one? Maybe it's an agent issue.

**Comment by s3inlc** [comment]
I assume you are already running the agent with debug so you could see that the -O flag is not in the command which is executed. Can you check if the agent extra parameters are passed to the agent in the JSON element which is sent on the getChunk request?

**Comment by 64nickel** [comment]
I did not run the agent with debug.  I just fired it up.  Mea culpa.  The -O switch is being passed to the agent and running without error.  This is not reflected in the task attack command on the server, but debug shows it launching on the agent.

**Comment by s3inlc** [comment]
Yes, because when you set it agent specific, this belongs not to the task, but to the agent and is just applied to the command when this agent runs a command. Agent extra parameters are never shown in the task command on the server.

**Comment by 64nickel** [comment]
Understood.  Thanks.  I guess then, this turns back to what you originally proposed as a feature where optimized kernels can be a checkbox for either on or off per task/supertask.  All other functionality seems to be golden.

**Comment by s3inlc** [comment]
That's good. I will keep this open until there is the selection to add the -O flag for all subtasks on supertask creation. Thanks for the input.

**Comment by s3inlc** [comment]
Note for me: also implement the selection for the benchmark type on mask import.

**Comment by s3inlc** [comment]
For mask imports it can now be selected which benchmark type should be used and if the tasks should have the -O flag or not. Changes are currently in the development branch and will be included in the next release.

**Comment by winxp5421** [comment]
Closing this issue. If you are still having issues please re-open
