### ISSUE TITLE
hashcat4.1.0

### ISSUE THREAD

**Issue by zl9801** [s3inlc/hashtopolis#389]
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage.
0.3.2
- Current Client version
0.43.13  C#
- Your current Hashcat version
4.1.0
- The exact task command you are trying to run.
#HL# -a3 -1 ?u?l?d  ?1?1?1?1?1?1?1?1 
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.
```
{"action":"chunk","token":"PZc5WeOcCO","taskId":417}
----------------------------------
Register jsonSend...  connectURL:http://192.168.0.58:8090/api/server.php
----------------------------------
----------------------------------
Register jsonSend...  result:{"action":"chunk","response":"SUCCESS","status":"ke
yspace_required"}
----------------------------------
{"action":"chunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client to measure the keyspace for this task
./OpenCL/: No such file or directory
Something went wrong with keyspace measuring

Unhandled Exception: System.FormatException: Input string was not in a correct f
ormat.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffe
r& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatI
nfo numfmt)
   at System.Convert.ToInt64(String value)
   at hashtopussy.hashcatClass.parseKeyspace(String line, Int64& keySpace)
   at hashtopussy.hashcatClass.runKeyspace(Int64& keySpace)
   at hashtopussy.taskClass.getChunk(Int32 inTask)
   at hashtopussy.taskClass.getTask()
   at hashtopussy.Program.Main(String[] args)
```

**Describe your problem in as much detail as possible " It's broke " is not a description.**
How to modify C # to avoid this error.

```
keySpace = Convert.ToInt64(line);
```

Modified as follows:

```
if (!long.TryParse(line, out keySpace))
 {
       Console.WriteLine("There was an error parsing the keyspace, setting keyspace to 0. Please review attack cmd");
        keySpace = 0; //Return 0 which will throw error
}
```

Is that all you got?

**Comment by s3inlc** [comment]
Are you running this on windows or with mono?

**Comment by zl9801** [comment]
Windows 7 X64.

**Comment by s3inlc** [comment]
The problem is that you are running a pretty old version of Hashtopolis. Starting from version 4.1.0 Hashcat enforces hashcat to be run in the hashcat folder and is not allowed to call it with a relative path on windows (due to some constraints with special chars, see here https://github.com/s3inlc/hashtopolis/issues/329).

So the error on the client is not caused by the keyspace directly, but just because hashcat cannot find its required files (as shown OpenCL/ in the error). The correct parsing with the if statement already is included in the newest client. I suggest you update to the newest version of Hashtopolis.

**Comment by zl9801** [comment]
Thanks.
I read this #329.
C # newest client, in that class to judge hashcat4.1.0 path problem, can you tell me?

**Comment by s3inlc** [comment]
To use the newest client you also should upgrade the server, the new client is not compatible to such an old server version as there were large changes from 0.4.x to 0.5.0.

**Comment by zl9801** [comment]
Thanks.

**Comment by zl9801** [comment]
hashcat4.1.0 problems on the Windows directory, can you solve them completely on the C # client?
 If you can please tell me what classes are involved?

**Comment by s3inlc** [comment]
I don't actually understand what you mean. What needs to be fixed?
The newest csharp agent is able to run with hashcat 4.1.0.

**Comment by zl9801** [comment]
The newest csharp agent is able to run with hashcat 4.1.0.
Server version as there were large changes from 0.4.x to 0.5.0.
--------------------------------------------------------------------
I want to use hashcat4.1.0 on the basis of not changing the server version.

**Comment by s3inlc** [comment]
There would be a lot of changes to be made to the csharp client to run with  server 0.3.x. Either you would have to start with the latest one compatible with this server version and apply the changes for hashcat 4.1.0 or you need to change back the newest client to make it working with the old server.
I cannot assist you in details of the client as I'm not the one who programmed the csharp client.

**Comment by zl9801** [comment]
Thank you for your help.
