### ISSUE TITLE
End of install redirects to start of install

### ISSUE THREAD

**Issue by aosti** [s3inlc/hashtopolis#390]
- Your current Server version located at the bottom of any Hashtopolis webpage.
0.5.1
- Current Client version
Doesn't apply
- Your current Hashcat version
Doesn't apply
- The exact task command you are trying to run.
At the end of installation, there is a message display "Your installation is complete" and a button that redirects to the index.php page. When I click at that button, it simply redirects me to the beggining of the installation. If I open a new tab and access the same link, it works right. I'm using the latest version of the chrome browser. I'm not sure if this is related, but I can't login in hashtopolis.

- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.
Doesn't apply

**Comment by s3inlc** [comment]
In such a case, the link after the installation redirects to the main page, but most likely something with the installation went not correctly and therefore it forwards again to the installation.

Can you check if in `src/inc/load.php` the MySQL credentials and the `$INSTALL` variable are set correctly?

**Comment by aosti** [comment]
@s3inlc The credentials are ok and the `$INSTALL` variable is set to true.
