### ISSUE TITLE
does not find server api. (System.Collections.ListDictionaryInternal)

### ISSUE THREAD

**Issue by kolet** [s3inlc/hashtopolis#400]
https://imgur.com/a/f1s0NUP

using the latest github release (V6)
using xamp

either 127.0.0.1 or localip does not work.

**Comment by s3inlc** [comment]
Can you run the agent with the debug flag set to get more output please: `hashtopolis.exe -d`

**Comment by s3inlc** [comment]
And also please set the `display_errors` flag to `1` in `src/inc/load.php` to see if there is any error on the server. Alternatively you also could check the error log of xampp.

**Comment by kolet** [comment]
Client Version 0.52.2
Please enter server connect URL (https will be used unless specified):
http://10.0.0.8/api/server.php
Testing connection to http://10.0.0.8/api/server.php
{"action":"testConnection"}
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1'  in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
{"action":"testConnection","response":"SUCCESS"}
System.Collections.ListDictionaryInternal
Empty string for success check
@s3inlc

**Comment by s3inlc** [comment]
Thanks for the details. Which PHP version is your xampp installation running?

**Comment by kolet** [comment]
Strict Standards: Static function PQuery::isValid() should not be abstract in C:\xampp\htdocs\inc\protocol.php on line 20

with display_errors 1
@s3inlc

**Comment by kolet** [comment]
version 5.6.28 @s3inlc

**Comment by s3inlc** [comment]
The best solution for this would be to use one of the newer PHP versions (7.1 or 7.2) because using 5.6 is not recommended. Also you are not using the most up-to-date 5.6 version.

**Comment by kolet** [comment]
well i guess that worked..
can be closed :)
