### ISSUE TITLE
after downloading the "binary" (hashcat) cant run (Keyspace measuring was unsuccessful, check all files are present)

### ISSUE THREAD

**Issue by kolet** [s3inlc/hashtopolis#401]
https://imgur.com/a/2eRhGhU

hashcat is been successfully downloaded but does not run.
Keyspace measuring was unsuccessful, check all files are present

**Comment by s3inlc** [comment]
Again can you please run it with the debug flag please.
And also please provide some informations about the task you are trying to run.

**Comment by kolet** [comment]
@s3inlc  sorry

trying to run a supertask.
(first i imported manual couple of masks.)
?a?a?a?a?a?a
?a?a?a?a?a?a?a
?d?d?d?d?d?d?d?d
?d?d?d?d?d?d?d?d?d
?d?d?d?d?d?d?d?d?d?d
?d?d?d?d?d?d?d?d?d?d?d
?d?d?d?d?d?d?d?d?d?d?d?d
?a?a?a?a?a?a?a?a

> Getting task
{"action":"getTask","token":"gZ02BFns1r"}
{"action":"getTask","response":"SUCCESS","taskId":1,"attackcmd":"#HL# -a 3  ?a?a?a?a?a?a -p : --hash-type=100 -w 4 -O","cmdpars":"","hashlistId":1,"bench":30,"statustimer":5,"files":[],"crackerId":"1"
,"benchType":"run","hashlistAlias":"#HL#","keyspace":"0"}
Server has assigned client with Task:1, Cracker:1 and Hashlist:1
Downloading hashlist for this task, please wait...
{"action":"getHashlist","token":"gZ02BFns1r","hashlistId":1}
{"action":"getHashlist","response":"SUCCESS","url":"getHashlist.php?hashlists=1&token=gZ02BFns1r"}
Downloading from http://10.0.0.8/getHashlist.php?hashlists=1&token=gZ02BFns1r
Downloading 100% @ 5.13 KB/s
Finished downloading file
{"action":"downloadBinary","type":"cracker","token":"gZ02BFns1r","binaryVersionId":1,"force":0}
{"action":"downloadBinary","response":"SUCCESS","url":"https:\/\/hashcat.net\/files\/hashcat-4.1.0.7z","name":"hashcat","executable":"hashcatV411.exe"}
Client already exists, skipping download
Getting chunk...
{"action":"getChunk","token":"gZ02BFns1r","taskId":1}
{"action":"getChunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client measure the keyspace for this task
Could not locate C:\Users\GPGPU\Documents\hashto\hashcat\1\hashcatV41164.exe
Keyspace measuring was unsuccessful, check all files are present

**Comment by s3inlc** [comment]
I suspect that you configured your cracker the wrong way, similar to this one: #395
The base name for the cracker should only be `hashcat` without any version number.

**Comment by kolet** [comment]
@s3inlc  seems to work.

then why allow user input there if only hashcat is working :) (or at least something should be mention that only names/chars with out numbers are working).
and have one already exist in the source code. (one binary)

btw question no related to that problem.
is there any guide on how to configure telegram bot ?

**Comment by s3inlc** [comment]
There is not much information around about the telegram configuration. It was added in PR #259, what is special in this notification type is that you have to put the bot token (which you get from the telegram botfather) into the source code `src/inc/notifications/NotificationTelegram.class.php`.
