### ISSUE TITLE
WPA2 Wordlist attack - Invalid benchmark result!

### ISSUE THREAD

**Issue by satcom886** [s3inlc/hashtopolis#406]
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Hashtopolis server - 0.6.0
- Hashtopolis csharp - 0.52.2
- Hashcat 4.1.0
- Attack cmd: -a0 #HL# 8dig5milup.txt
- Debug output is attached
[output.txt](https://github.com/s3inlc/hashtopolis/files/2244243/output.txt)

**Describe your problem in as much detail as possible " It's broke " is not a description.**
I tried many different wordlists (smaller, bigger, less characters, more characters), but I always end up with "Invalid benchmark result!". For some reason this happens only on Ubuntu. Windows clients work perfectly fine...

**Comment by s3inlc** [comment]
Can you please run the benchmark command manually and look what hashcat gives as output?

```
/home/satcom886/apps/hashtopolis/hashcat/1/hashcat64.bin  -a0 "/home/satcom886/apps/hashtopolis/hashlists/1" "/home/satcom886/apps/hashtopolis/files/8dig5milup.txt" -p : --hash-type=2500 -D 1,2 -d 1,2,3 -w 4  --runtime=120 --restore-disable --potfile-disable  --machine-readable --session=hashtopolis  --progress-only
```

**Comment by s3inlc** [comment]
Hmm that's a strange error. Just to be sure, could you try the same command as above except removing the --runtime=120 flag and see if this makes any difference?

If the error still persists then, you could test with just using the GPUs without the CPUs as they often are more prone to OpenCL errors.

**Comment by satcom886** [comment]
Removing --runtime=120 made no difference.

It seems, that it really is the CPU. Running with only the GPUs works.
If it helps, this is the info about the CPU platform (from hashcat -I):

Platform ID #2
  Vendor  : Advanced Micro Devices, Inc.
  Name    : AMD Accelerated Parallel Processing
  Version : OpenCL 2.0 AMD-APP (1800.8)

  Device ID #3
    Type           : CPU
    Vendor ID      : 1
    Vendor         : AuthenticAMD
    Name           : AMD FX(tm)-8320 Eight-Core Processor
    Version        : OpenCL 1.2 AMD-APP (1800.8)
    Processor(s)   : 8
    Clock          : 1403
    Memory         : 4017/16069 MB allocatable
    OpenCL Version : OpenCL C 1.2 
    Driver Version : 1800.8 (sse2,avx,fma4)

**Comment by s3inlc** [comment]
Did you also test to just run with the CPUs and without any GPUs?
Afaik it's not really recommended to let CPUs and GPUs work together. 

If there is just the problem with the CPUs I recommend that you ask for help on the Hashcat forums, because then it's more likely a driver/hashcat issue.

**Comment by satcom886** [comment]
Yes, running with CPU only produces the "Neoprávněný přístup do paměti (SIGSEGV) (core dumped [obraz paměti uložen])"
I also tried this on a different PC (also running the AMD APP SDK 3.0), with the same results.
Also I forgot to mention, that I ran these commands on Ubuntu 18.04.

**Comment by s3inlc** [comment]
Ok, the only thing I just see, is that the OpenCL version of the CPU driver is only 1.2, so far I've also never used AMD processors with Hashcat, I cannot really say what is recommended there.  In this case I suggest to ask for help on the Hashcat forum to solve this.

**Comment by s3inlc** [comment]
Just a note about this issue I got from @hops:
`I think AMD App SDK isn't officially supported. However you can use the Intel OpenCL runtime with AMD CPUs`

**Comment by satcom886** [comment]
OMG! The Intel OCL runtime WORKS! Even on AMD CPUs! I had NO IDEA!

**Comment by s3inlc** [comment]
Hehe nice, thanks @hops :)
Let me know if there still is a problem with the benchmark then, otherwise please close the issue afterwards.

**Comment by satcom886** [comment]
When using the Intel runtime, the benchmark finishes without any issue.
