### ISSUE TITLE
[WIKI REQUEST] Python client on Linux - subprocess.CalledProcessError: Command 'lscpu | grep 'Model name'' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by satcom886** [s3inlc/hashtopolis#407]
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Hashtopolis server - 0.6.0
- Hashtopolis python - 0.1.4
- Hashcat 4.1.0
- *ANY ATTACK COMMAND*

**Describe your problem in as much detail as possible " It's broke " is not a description.**
This should be added to the "Frequent Problems" section of the wiki:
The output of lscpu is localised, so when the python client executes "lscpu | grep 'Model name'", grep will never find anything (unless the OS language is set to English), because the output of lscpu is different in every language. 

SOLUTION: Edit initialize.py (located in htpclient). Find a line, where it says "output = subprocess.check_output("lscpu | grep 'Model name'", shell=True)" and replace "Model name" with your 
language variant of "Model name" (you can find it in lscpu).

**Comment by s3inlc** [comment]
Thanks.

If you also have some GPUs in your computer, could you test if we have the same problem with lspci?
(`lspci | grep -E 'VGA compatible controller|3D controller'`)

**Comment by satcom886** [comment]
No, lspci only outputs in English:
01:00.0 VGA compatible controller: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1)
05:00.0 VGA compatible controller: NVIDIA Corporation GM206 [GeForce GTX 960] (rev a1)

**Comment by s3inlc** [comment]
Ok perfect, thanks for testing.
I'll keep this issue open until I updated the client to use the other way to retrieve the CPUs.

**Comment by satcom886** [comment]
No problem, you are the best! If I find any more stuff, I will be back.

**Comment by s3inlc** [comment]
The agent now uses the above mentioned way to get a non-localized output for the CPUs, therefore I assume this issue can be closed. Please reopen if there are still problems.
