### ISSUE TITLE
V0.6.0 running problems

### ISSUE THREAD

**Issue by zl9801** [s3inlc/hashtopolis#410]
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage.
0.6.0
- Current Client version
0.52.2
- Your current Hashcat version
hashcat-4.0.1
- The exact task command you are trying to run.
-a 0 #HL# 001.txt
-a 0 #HL# 002.txt
-a 0 #HL# 003.txt
-a 3 #HL# -1 ?u?l ?1?1?1?1?1?1?1?1
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

**Describe your problem in as much detail as possible " It's broke " is not a description.**
Supertask assign tasks, the client does not download Hashcat-4.0.1,hashcat directory is empty, always show getting task ... no new task ..., please have detailed setup and operation steps?

**Comment by s3inlc** [comment]
Can I please have the debug log of the client?

**Comment by zl9801** [comment]
C:\Users\Administrator\Desktop\xad_hash\4.0.1\v06\192.168.0.66>hashtopolis.exe -
debug
Client Version 0.52.2
Connecting to server http://192.168.0.66/xad/api/server.php
System is Windows 64-bit
Existing token found
{"action":"login","clientSignature":"generic-csharp","token":"iw7afeMKwq"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Sending server client information
System is Windows 64-bit
{"action":"updateInformation","token":"iw7afeMKwq","uid":"75a2ed9c-d9ed-433a-8f4f-a55afeec2335"
,"os":1,"devices":["AMD Radeon R9 200 Series","AMD Radeon R9 200 Series","Intel(R) Core(TM) i7-
4770K CPU @ 3.50GHz"]}
{"action":"updateInformation","response":"SUCCESS"}
Logged in to server
Checking for client updates
{"action":"checkClientVersion","type":"csharp","version":"0.52.2","token":"iw7afeMKwq"}
{"action":"checkClientVersion","response":"SUCCESS","version":"OK"}
You are using the latest client version
Using new STATUS codes
Getting task
{"action":"getTask","token":"iw7afeMKwq"}
{"action":"getTask","response":"SUCCESS","taskId":null,"reason":"No suitable task available!"}
No new task assigned to agent
Getting task
{"action":"getTask","token":"iw7afeMKwq"}
{"action":"getTask","response":"SUCCESS","taskId":null,"reason":"No suitable task available!"}
No new task assigned to agent

**Comment by s3inlc** [comment]
Ok, so far this looks good. At this point the hashcat directory will be empty, because the client did not receive a task yet, so he does not know which hashcat to use.
I assume that there is just a reason why it does not receive the task. Both the supertask and subtasks have a priority larger than 0? Is the agent trusted in case the files or hashlist is secret?

**Comment by zl9801** [comment]
C:\Users\Administrator\Desktop\xad_hash\4.0.1\v06\192.168.0.66>hashtopolis.exe -d
Client Version 0.52.2
Please enter server connect URL (https will be used unless specified):
http://192.168.0.66/xad/api.server.php
Testing connection to http://192.168.0.66/xad/api.server.php
{"action":"testConnection"}
The remote server returned an error: (404) Not Found.
Test connect failed, please enter server connect URL:
http://192.168.0.66/xad/api/server.php
Testing connection to http://192.168.0.66/xad/api/server.php
{"action":"testConnection"}
{"action":"testConnection","response":"SUCCESS"}
Connecting to server http://192.168.0.66/xad/api/server.php
Creating files directory
Creating hashlists directory
Creating tasks directory
Creating hashcat directory
Unable to find existing token, please enter voucher
0
System is Windows 64-bit
{"action":"register","voucher":"0","name":"WIN-V7DN19274O2"}
{"action":"register","response":"SUCCESS","token":"Jk3k1uLB0h"}
Sending server client information
System is Windows 64-bit
{"action":"updateInformation","token":"Jk3k1uLB0h","uid":"8b107a33-d977-4051-8c38-ddbf889c7105
,"os":1,"devices":["AMD Radeon R9 200 Series","AMD Radeon R9 200 Series","Intel(R) Core(TM) i7
4770K CPU @ 3.50GHz"]}
{"action":"updateInformation","response":"SUCCESS"}
Logged in to server
Checking for client updates
{"action":"checkClientVersion","type":"csharp","version":"0.52.2","token":"Jk3k1uLB0h"}
{"action":"checkClientVersion","response":"SUCCESS","version":"OK"}
You are using the latest client version
Downloading 7zip binary
{"action":"downloadBinary","type":"7zr","token":"Jk3k1uLB0h"}
{"action":"downloadBinary","response":"SUCCESS","executable":"http:\/\/192.168.0.66\/xad\/stat
c\/7zr.exe"}
Downloading from http://192.168.0.66/xad/static/7zr.exe
Downloading 91% @ 62.86 MB/ss
Finished downloading file
Using new STATUS codes
Getting task
{"action":"getTask","token":"Jk3k1uLB0h"}
{"action":"getTask","response":"SUCCESS","taskId":24,"attackcmd":"-a 3 #HL#  -1 ?u?l  ?1?1?1?1
1?1?1?1 -p : --hash-type=0 ","cmdpars":"","hashlistId":5,"bench":30,"statustimer":5,"files":[]
"crackerId":"2","benchType":"run","hashlistAlias":"#HL#","keyspace":"0"}
Server has assigned client with Task:24, Cracker:2 and Hashlist:5
Downloading hashlist for this task, please wait...
{"action":"getHashlist","token":"Jk3k1uLB0h","hashlistId":5}
{"action":"getHashlist","response":"SUCCESS","url":"getHashlist.php?hashlists=5&token=Jk3k1uLB
h"}
Downloading from http://192.168.0.66/xad/getHashlist.php?hashlists=5&token=Jk3k1uLB0h
Downloading 100% @ 0.36 KB/s
Finished downloading file
{"action":"downloadBinary","type":"cracker","token":"Jk3k1uLB0h","binaryVersionId":2,"force":0

{"action":"downloadBinary","response":"SUCCESS","url":"http:\/\/192.168.0.66\/xad\/xad\/xad-4.
.0.7z","name":"hashcat","executable":"hashcat-4.1.0.exe"}
Client doesn't have required cracker...
Downloading from http://192.168.0.66/xad/xad/xad-4.1.0.7z
Downloading 56% @ 81.55 MB/ss
C:\Users\Administrator\Desktop\xad_hash\4.0.1\v06\192.168.0.66\7zr.exe x -y -o"C:\Users\Admini
trator\Desktop\xad_hash\4.0.1\v06\192.168.0.66\tmp" "C:\Users\Administrator\Desktop\xad_hash\4
0.1\v06\192.168.0.66\crackerClient.7z"
Extracting archive C:\Users\Administrator\Desktop\xad_hash\4.0.1\v06\192.168.0.66\crackerClien
.7z...
Getting chunk...
{"action":"getChunk","token":"Jk3k1uLB0h","taskId":24}
{"action":"getChunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client measure the keyspace for this task
Could not locate C:\Users\Administrator\Desktop\xad_hash\4.0.1\v06\192.168.0.66\hashcat\2\hash
at-464.164.064.exe
Keyspace measuring was unsuccessful, check all files are present

------------------------
hashat-464.164.064.exe   
Need to modify file name?

**Comment by s3inlc** [comment]
You configured the cracker in a wrong way. For the cracker name you enter you only need to write `hashcat` into the field without any version number.

**Comment by zl9801** [comment]
Thanks.
