### ISSUE TITLE
hashcat 3.6.0 or 4.0.0 or 4.0.1

### ISSUE THREAD

**Issue by zl9801** [s3inlc/hashtopolis#416]
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage.
0.3.2
- Current Client version
0.46.2
- Your current Hashcat version
3.6.0
4.0.0
4.0.1
- The exact task command you are trying to run.
#HL# -a 3 ?a?a?a?a?a?a
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

**Describe your problem in as much detail as possible " It's broke " is not a description.**
The same hardware environment, the same MD5, why 3.6.0 faster than 4.0.0 and 4.0.1 speed?
---------------------------------------------------------------------------------------
3.6.0 
Progress: 25.06% | Speed:2.06GH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1

4.0.0
Progress: 35.16% | Speed:1.16GH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1

4.0.1
Progress: 28.32% | Speed:1.17GH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1

**Comment by s3inlc** [comment]
This is something you have to ask in the Hashcat forum, as this is the speed which Hashcat is reporting, Hashtopolis just takes this and gives is as information.

**Comment by blazer2x** [comment]
It could be to -O param is needed to use the optimized kernels for 4.0.1, otherwise you will see a speed drop. Please try and add this switch to your command

**Comment by s3inlc** [comment]
Oh yeah good point, didn't thought at that.
