### ISSUE TITLE
feature: hovertext help for icons

### ISSUE THREAD

**Issue by roycewilliams** [s3inlc/hashtopolis#419]
Server: latest GitHub

It would be good if the functionality behind action icons were more discoverable. For example, the Action column icons on the Tasks list page could have underlying hover text of 'Copy this task', 'Archive this task', and 'Delete this task', and the disk icon could have have hovertext "Save this field now", etc.

**Comment by s3inlc** [comment]
I added tooltips to all icon buttons now, so this should help to understand what the button is meant to do. The changes are already merged into master now.

**Comment by roycewilliams** [comment]
A nice UX discoverability improvement - thanks!
