### ISSUE TITLE
Feature Request: override benchmark values

### ISSUE THREAD

**Issue by evilmog** [s3inlc/hashtopolis#429]
hashtopolis currently uses a benchmark value before it starts a task by using --progress only, this will determine --limit

please make an option to override the computed --limit and set benchmark values manually

**Comment by s3inlc** [comment]
This feature is now included in the 0.8.0 release as you can set a static chunk size (either by specifying the --length of the chunk or by setting a fixed number of chunks for a task).
If you still need something additional regarding this issue, please reopen.
