### ISSUE TITLE
Cannot download file via generated url using user API (getFile.php)

### ISSUE THREAD

**Issue by hcuser12** [s3inlc/hashtopolis#430]
**Hashtopolis release:** 0.7.0 

I'm trying to create user API client that downloads list of cracked hashes after completing task. 

In my client script I call:
```
{
    "section": "hashlist",
    "request": "exportCracked",
    "accessKey": "..."
}
```  
and having `fileId` in response I do call:
```
{
    "section": "file",
    "request": "getFile",
    "fileId": 1,
    "accessKey": "..."
}
```
Now having `url` in response I try to download file which produces error HTTP 500.

After further testing i did find error in file `/getFile.php` in line 44:
```
else if (!$this->hasPermission(USection::FILE, USectionFile::GET_FILE, $apiKey)) {
```
^ in this line `$this` is called out of context.

Please fix. I cannot download cracked hashes.

**Comment by s3inlc** [comment]
Can you please check if the fix in this branch solves your issue?
https://github.com/s3inlc/hashtopolis/tree/issue/430

**Comment by s3inlc** [comment]
I tested the exact described procedure and had the same behavior. The provided changes fix the issue, so I merged it into master.

**Comment by hcuser12** [comment]
It's working now. Thx. :+1:
