### ISSUE TITLE
File uploading not working

### ISSUE THREAD

**Issue by dennislwy** [s3inlc/hashtopolis#449]
- Your current Server version located at the bottom of any Hashtopolis webpage.
**0.7.1**

- Current Client version
Not Applicable

- Your current Hashcat version
Not Applicable

- The exact task command you are trying to run.
**Trying to upload wordlist file** 

- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

**Describe your problem in as much detail as possible " It's broke " is not a description.**
Was trying to upload wordlist file (tested .7z and .txt file extensions) using latest Google Chrome and Internet Explorer in Windows 10 but failed. After clicked "Upload files", at the end of upload process, page refreshes and no new file was shown in the page. I checked 'File' table in mysql db, there was no new entry as well.

Here is my screenshot when uploading
![image](https://user-images.githubusercontent.com/5407099/44565281-d75f9300-a799-11e8-8a44-17723c4a27c9.png)

**Comment by s3inlc** [comment]
You need to make sure that your apache2 allows uploading that large files. Read the server prerequisites to see which config variables you need to change: https://github.com/s3inlc/hashtopolis/wiki/Server-Prerequisites

**Comment by dennislwy** [comment]
@s3inlc thanks for the suggestion, issue solved after i set `upload_max_filesize = 250M`
thanks
