### ISSUE TITLE
Feature Request: Support for mode 16800

### ISSUE THREAD

**Issue by emzeta76** [s3inlc/hashtopolis#450]
Hashtopolis: 0.7.1+dev
Hashcat: V4.2.1-25

The new hashcat version brings new modes:
hash-mode 16700 = FileVault 2
hash-mode 16800 = WPA-PMKID-PBKDF2
 hash-mode 16801 = WPA-PMKID-PMK
hash-mode 16900 = Ansible Vault

It"s not possible to choose them during adding new Hashlist:
![image](https://user-images.githubusercontent.com/42700309/44620656-897d8480-a898-11e8-835b-2ce7d6d21941.png)

**Comment by winxp5421** [comment]
The list of "supported" or "Selectable" hashlists is easily editable from the http UI.

Regardless, i will add the new hashtypes here soon

**Comment by winxp5421** [comment]
PR made. Closing this
