### ISSUE TITLE
(un)ticking contains secret data not registering

### ISSUE THREAD

**Issue by cryptolovi** [s3inlc/hashtopolis#452]
- Current Server version: 0.7.1+dev
- Current Client version: s3-python-0.1.8
- Your current Hashcat version: 4.2.1

When selecting "hashlist contains secret data on hashtopolis/hashlists.php?id=**" => apache2.log;
PHP Notice:  Undefined index: hashlistId in /srv/hashtopolis/inc/handlers/HashlistHandler.class.php on line 40, referer: http://localhost/hashtopolis/hashlists.php?id=**

Partial fix (IsSecret in DB gets correctly flipped on hashlist after fix)
Line 40;
  HashlistUtils::setSecret($_POST['hashlistId'], $_POST['secret'], AccessControl::getInstance()->getUser());
I changed line 40 into;
  HashlistUtils::setSecret($_POST['hashlist'], $_POST['secret'], AccessControl::getInstance()->getUser());

Partial: When unticking the contains secret data -> apache2.log
PHP Notice:  Undefined index: secret in /srv/hashtopolis/inc/handlers/HashlistHandler.class.php on line 40, referer: http://localhost/hashtopolis/hashlists.php?id=**

(un)ticking works with the partial fix, just the above notice about the secret index

**Comment by s3inlc** [comment]
Thanks for the report, the fix is pushed to master and will be included in the next release.

**Comment by cryptolovi** [comment]
Can be closed, works as intended in hashtopolis 0.8.0.
