### ISSUE TITLE
add proxy settings to Telegram with UI eventually

### ISSUE THREAD

**Issue by cryptolovi** [s3inlc/hashtopolis#453]
Would be nice to have some more control about the chatbot settings amd also parse bot token from UI,

For telegram I added in NotificationsTelegram.php after 
$ch = curl_init("https://api.telegram.org/bot{$botToken}/sendmessage");
to get proxies working

curl_setopt($ch, CURLOPT_PROXY, "a proxy name");
curl_setopt($ch, CURLOPT_PROXYPORT, "a proxy port");
curl_setopt($ch, CURLOPT_PROXYTYPE, CURLPROXY_HTTP);
curl_setopt($ch, CURLOPT_HTTPPROXYTUNNEL, "true");

**Comment by s3inlc** [comment]
I added server configurations for the telegram proxy configuration and also that the bot token is available to be set in the config. Could you please test out this branch and report back if it works for you: https://github.com/s3inlc/hashtopolis/tree/enhancement/notifications

**Comment by s3inlc** [comment]
Feature was reported to work and changes are now merged into the dev branch.
