### ISSUE TITLE
Allow for client side de-register and re-register

### ISSUE THREAD

**Issue by evilmog** [s3inlc/hashtopolis#457]
Currently I have a lot of transient nodes, I'd like an option in the hashtopolis agent to allow for client side deregistering of a node.

for example add a --deregister to unregister that client on python3 hashtopolis.zip --deregister=yes

I'd also like to specify the --url and --voucher code from the hashtopolis client without creating a json, example python3 hashtopolis.zip --url="https://www.example.com" --voucher="code"

this way I can automate new node spinup and spindown

**Comment by evilmog** [comment]
For the client side de-register to answer your question on another channel, I'd like the client to be able to trigger a register that will be processed server side, so either a command sent to the client or some other trigger that can be scripted without having to login to the website during a spindown script on cloud or after a contest end for example

**Comment by s3inlc** [comment]
As the feature is now included in the release, I think I can close this issue.
