### ISSUE TITLE
-o  --outfile  error

### ISSUE THREAD

**Issue by zl9801** [s3inlc/hashtopolis#472]
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage.
- Current Client version
- Your current Hashcat version
- The exact task command you are trying to run.
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

**Describe your problem in as much detail as possible " It's broke " is not a description.**
agent code:
pInfo.Arguments = hcArgs + " -o \"d:\\zl_xad\\" + DateTime.Now.TimeOfDay.ToString().Replace(":", "_") + "_" + rd.Next(1, 10000) + ".txt \" --potfile-disable --quiet --restore-disable --session=hashtopussy --status --machine-readable --status-timer=" + interval + " --outfile-check-timer=" + interval + " --remove --remove-timer=" + interval + " --separator=" + separator + " -s " + skip + " -l " + size;
-----------------------------------------------------------------------------------------------------
Add parameter “-o” ,  “d:\\zl_xad\\”path under text generation, crack result record, but hashes.php show 0 hacked，no parameters  “-o”  show 3/3 hacked.
Why Hashcat crack success will not be able to pass back the results of the crack?
Just because "-o"?

**Comment by s3inlc** [comment]
I don't really understand what the question is.
So you entered this code having `-o` plus a path in the command line?

**Comment by zl9801** [comment]
Because hashes.php garbled problem, I want to test, Hashcat itself output text is also garbled, so this is just a test, do not do the actual application, I just put the problem to reflect.
