### ISSUE TITLE
Cannot connect to database on Arch Linux

### ISSUE THREAD

**Issue by lavanoid** [s3inlc/hashtopolis#475]
Server version: Latest from the git repo (October 4th, 2018)
Webserver: nginx 1.14.0-1
SQL server: mariadb 10.1.35-1
Installed PHP packages:
```
php 7.2.9-1
php-fpm 7.2.9-1
php-gd 7.2.9-1
php-pear 1:1.10.5-2
php-sqlite 7.2.9-1
```
PHP.ini: https://gist.github.com/lavanoid/91b758edff0e37a6dfe603424cdb3892
Distro: Manjaro GNOME, 64bit

I have installed the required packages that hashtopolis relies on, but I cannot get past the initial setup phase. I have made sure that the database/user/password is correct but it just keeps saying that the connection has failed, yet I can connect to the DB just fine with phpmyadmin.

Screenshot:
![screenshot from 2018-10-04 20-37-30](https://user-images.githubusercontent.com/4705167/46498452-63db8780-c815-11e8-8455-da2ec75fee1d.png)

**Comment by s3inlc** [comment]
This issue seems to be resolved, therefore I'm closing it. Reopen if there is still some problem.
