### ISSUE TITLE
Hashtopolis unable to login to server after upgrade

### ISSUE THREAD

**Issue by satcom886** [s3inlc/hashtopolis#479]
- Server 0.8.0

Problem description: Today I noticed, that I am running server 0.6.0 and there is 0.8.0 available. So i first updated to 0.7.0, then 0.7.1 and finally to 0.8.0. I am now at version 0.8.0 and am unable to login (Wrong username/password/OTP!). Is there anything I can do to reset the username/password, so that I can access my server again?

**Comment by s3inlc** [comment]
There is a script in `src/install/updates/reset.php` where you can either re-generate the salts or reset a users password and salt. So to reset your password, just adjust the user id and the password in the script and thenn call it with `php -f reset.php password`.

I guess you overwrote the encryption salts at some point of the update, correct?

**Comment by winxp5421** [comment]
If you followed the upgrade Documentation you should have a backup copy of your Encryption.class.php file. Try restoring that file. 
https://github.com/s3inlc/hashtopolis/wiki/Upgrading-Hashtopolis

**Comment by satcom886** [comment]
@s3inlc Ok, I got the access back by running the reset script. Thanks for the help. If an issue of simalar kind arises, I will contact you on the forum.
@winxp5421 I read the upgrade docs and the backup procedure is the only thing I skipped.
