### ISSUE TITLE
tasks.php show speed of task

### ISSUE THREAD

**Issue by blazer2x** [s3inlc/hashtopolis#481]
It would be quite useful to see the speed of the task running for a quick glance.

If it is a space issue perhaps the fileisize can be condensed into a tooltip.

The speed can be displayed as

Under progress column
18.71% / 18.65% @ 511.02 kH/s
or
Under agents column
5 @ 511.02 kH/s

**Comment by s3inlc** [comment]
As the feature is now included in the release, I think I can close this issue.
