### ISSUE TITLE
csharp agent - using a different command for CPU info

### ISSUE THREAD

**Issue by satcom886** [s3inlc/hashtopolis#490]
- Server 0.8.0
- Client 0.52.4 (csharp)
- Hashcat 4.2.1
- Command independent

This issue is very simalar to #407
Basically any linux agent with a language different than English does not display the CPU in hashtopolis agent page: 
![snimek z 2018-10-23 22-38-52](https://user-images.githubusercontent.com/28711937/47389699-c2f63300-d715-11e8-9db4-865c69e40176.png)
The circled agents are the ones on Windows. My guess is that the csharp agent also uses lscpu (at least on linux).

**Comment by s3inlc** [comment]
We are aware about the issue that on non-english locales the cpu info might not be readable. Please use the python agent, especially with server version 0.8.0, because currently only the python agent is kept up-to-date and this one also includes using the fix mentioned in issue #407.

**Comment by satcom886** [comment]
Ok, should this issue remain open then?

**Comment by s3inlc** [comment]
I would say no, because the issue is known and fixed on the currently supported client. The csharp agent will later either catch up all the things or it will be definitely discarded.

**Comment by satcom886** [comment]
Ok, thanks for the help. I will move my agents to the Python agent. Closing the issue...
