### ISSUE TITLE
Mask 8-bit full character problem?

### ISSUE THREAD

**Issue by zl9801** [s3inlc/hashtopolis#492]
**Use github issues only for bugs/feature requests - for discussions, general help and questions use the forum: https://hashtopolis.org**
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage.
0.3.2
- Current Client version
0.46
- Your current Hashcat version
4.0.1
- The exact task command you are trying to run.
hashcat64.exe   --hash-type=0  -O  -a 3 ?a?a?a?a?a?a?a?a 

- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

No new task assigned to agent
Getting task
{"action":"task","token":"rO9SCSO6SF"}
{"action":"task","response":"SUCCESS","task":"NONE"}
No new task assigned to agent
Getting task
{"action":"task","token":"rO9SCSO6SF"}
{"action":"task","response":"SUCCESS","task":2218,"attackcmd":"#HL# -O  -a 3 ?a?a?a?a?a?a?a?a",
"cmdpars":" --hash-type=0","hashlist":55,"bench":30,"statustimer":5,"files":[],"benchType":"run
","hashlistAlias":"#HL#"}
Server has assigned client with Task:2218 and Hashlist:55
Downloading hashlist for this task, please wait...
{"action":"hashes","token":"rO9SCSO6SF","hashlist":55}
Getting chunk...
{"action":"chunk","token":"rO9SCSO6SF","taskId":2218}
{"action":"chunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client measure the keyspace for this task
Using F:\xad_hash_agent\1080ti\files\ as working directory
F:\xad_hash_agent\1080ti\hashcat\hashcat64.exe   --hash-type=0  -O  -a 3 ?a?a?a?a?a?a?a?a --ses
sion=hashtopussy --keyspace --quiet
{"action":"keyspace","token":"rO9SCSO6SF","taskId":2218,"keyspace":7737809375}
Getting chunk...
{"action":"chunk","token":"rO9SCSO6SF","taskId":2218}
{"action":"chunk","response":"ERROR","message":"You are not assigned to this task!"}
ERROR
You are not assigned to this task!
Getting task
{"action":"task","token":"rO9SCSO6SF"}
{"action":"task","response":"SUCCESS","task":"NONE"}
No new task assigned to agent
Getting task

**Describe your problem in as much detail as possible " It's broke " is not a description.**

1.Mask 8-bit full character problem，"ERROR"
2.Hashcat Speed test Report, 1080TI, hashcat3.4.0, MD5 speed 32445.9 mh/s, why I 1080TI hashcat4.0. 1 stand-alone speed 15463.4mh/s? This is too different from the speed of the test report?(Hashcat problem,please help me write out the Hashcat command line statement, thank you.)

**Comment by s3inlc** [comment]
You use a REALLY old version (both server and client) of Hashtopolis. To know if this bug still persists in the current version you would definitely to test again on the current release (there were 2115 commits and 472 changed files since then).
And the second point is something which needs either to be discussed in the forum (https://hashtopolis.org) or even better on the forum of hashcat itself, as it is something related to changes to hashcat since version 3.4.0
