### ISSUE TITLE
Feature Request: Identify Pre-Cracked Hashes During Upload

### ISSUE THREAD

**Issue by gtrdlr** [s3inlc/hashtopolis#498]
When using other password cracking solutions (e.g., hashview), a new hashlist uploaded through the GUI will automatically perform a check of the database table to determine if a plaintext value has been previously assigned to the hash value and denote (and notify the user) that hash as 'cracked' without the need for further action.  At that point, it will kick off the first task against only thos ehashes with a remaining 'uncracked' status.  

I would love to see this feature included in a future release of hashtopolis, as a teammate of mine recently let several days pass waiting for a hash to crack before I realized that it already existed in the database despite showing 0/1.  

Fantastic product otherwise!

**Comment by s3inlc** [comment]
This feature is now implemented in the `current-dev` branch and will be included in the next release. On hashlist creation it checks for each hash if is already cracked in any of the others list.
Note that this features needs to be activated in the config (as the current default it is turned off).

**Comment by gtrdlr** [comment]
That is GREAT to hear. Thank you for integrating my recommendation. Much appreciated!

**Comment by s3inlc** [comment]
As the feature is now included in the release, I think I can close this issue.
