### ISSUE TITLE
Feature request: Delete files on agent that doesn't exist on server

### ISSUE THREAD

**Issue by alex90928129** [s3inlc/hashtopolis#502]
Is it possible to create a function that you can use that will check the files on the server in the files-directory with the agent files-directory and then delete the files on the agent that doesn't exist on the server to save space? 

Thanks

**Comment by s3inlc** [comment]
This feature is already implemented since a longer time (agent version 0.1.8 and the according server release). When you delete a file on the server, the agent should automatically retrieve a list of to-delete filenames and should clean them up.

**Comment by alex90928129** [comment]
Oh, I hadn't realised. Maybe I'm too impatient when waiting for the file to be deleted. 
Thanks!
