### ISSUE TITLE
User API createHashlist does not map or default  required brainId

### ISSUE THREAD

**Issue by noncenz** [s3inlc/hashtopolis#504]
Server version: 0.10.0
Other component versions N/A

Calling createHashlist with the following data:
'section': 'hashlist', 
'request': 'createHashlist',
'name': 'my list name', 
'isSalted': False, 
'isSecret': True, 
'isHexSalt': False, 
'separator': ':', 
'format': 0, 
'hashtypeId': 16800, 
'accessGroupId': 1, 
'data':  (encoded hashlist)
'accessKey': (api key)
'useBrain':false
'brainFeatures':0

Call results in error due to "brainId" being empty in $vals in AbstractModelFactory.class.php line 114

There does not seem to be a path to provide brainId in the user API and also no default for it.

**Comment by s3inlc** [comment]
Can you please try if this commit solves the issue? The value `useBrain` should be saved in `brainId`, just the conversion was missing.

**Comment by noncenz** [comment]
That did the trick, thank you!
