### ISSUE TITLE
Using wrong StoredValue in update check leads to Duplicate entry 'version' for key 'PRIMARY' on every page load

### ISSUE THREAD

**Issue by DarkGigaByte** [s3inlc/hashtopolis#506]
https://github.com/s3inlc/hashtopolis/blob/cdc674f4f375115debd556feda4e7f6e4614a2c6/src/install/updates/update.php#L39

I assume its a classic copy+paste error. It should be StoredValue "build" instead of "version" in the mentioned line.

**Comment by s3inlc** [comment]
Thanks for the report and the PR.

**Comment by gsocgsoc** [comment]
Each time you ran the update script it created some entires in the db as well that need to be cleaned up, so you will have duplicates

**Comment by s3inlc** [comment]
Can you explain this more detailed, where do duplicate entries happen you need to clean up? There should only be one entry for `build` and `version` each.

**Comment by gsocgsoc** [comment]
Yeah sorry, if you ran the update script a couple of times like i did you get stuff like this in the db
mysql> select * from Config;

|       99 |               1 | hashcatBrainEnable          | 0                                                                                          |
|      100 |               1 | hashcatBrainHost            |                                                                                            |
|      101 |               1 | hashcatBrainPort            | 0                                                                                          |
|      102 |               1 | hashcatBrainPass            |                                                                                            |
|      103 |               1 | hashlistImportCheck         | 0                                                                                          |
|      104 |               5 | allowDeregister             | 1                                                                                          |
|      105 |               1 | hashcatBrainEnable          | 0                                                                                          |
|      106 |               1 | hashcatBrainHost            |                                                                                            |
|      107 |               1 | hashcatBrainPort            | 0                                                                                          |
|      108 |               1 | hashcatBrainPass            |                                                                                            |
|      109 |               1 | hashlistImportCheck         | 0                                                                                          |
|      110 |               5 | allowDeregister             | 1                                                                                          |
|      111 |               1 | hashcatBrainEnable          | 0                                                                                          |
|      112 |               1 | hashcatBrainHost            |                                                                                            |
|      113 |               1 | hashcatBrainPort            | 0                                                                                          |
|      114 |               1 | hashcatBrainPass            |                                                                                            |
|      115 |               1 | hashlistImportCheck         | 0                                                                                          |
|      116 |               5 | allowDeregister             | 1                                                                                          |
|      117 |               1 | hashcatBrainEnable          | 0                                                                                          |
|      118 |               1 | hashcatBrainHost            |                                                                                            |
|      119 |               1 | hashcatBrainPort            | 0                                                                                          |
|      120 |               1 | hashcatBrainPass            |                                                                                            |
|      121 |               1 | hashlistImportCheck         | 0                                                                                          |
|      122 |               5 | allowDeregister             | 1                                                                                          |
|      123 |               1 | hashcatBrainEnable          | 0                                                                                          |
|      124 |               1 | hashcatBrainHost            |                                                                                            |
|      125 |               1 | hashcatBrainPort            | 0                                                                                          |
|      126 |               1 | hashcatBrainPass            |                                                                                            |
|      127 |               1 | hashlistImportCheck         | 0                                                                                          |
|      128 |               5 | allowDeregister             | 1                                                                                          |
|      129 |               1 | hashcatBrainEnable          | 0                                                                                          |
|      130 |               1 | hashcatBrainHost            |                                                                                            |
|      131 |               1 | hashcatBrainPort            | 0                                                                                          |
|      132 |               1 | hashcatBrainPass            |                                                                                            |
|      133 |               1 | hashlistImportCheck         | 0                                                                                          |
|      134 |               5 | allowDeregister             | 1                                                                                          |
|      135 |               1 | hashcatBrainEnable          | 0                                                                                          |
|      136 |               1 | hashcatBrainHost            |                                                                                            |
|      137 |               1 | hashcatBrainPort            | 0                                                                                          |
|      138 |               1 | hashcatBrainPass            |                                                                                            |
|      139 |               1 | hashlistImportCheck         | 0                                                                                          |
|      140 |               5 | allowDeregister             | 1                                                                                          |
+----------+-----------------+-----------------------------+--------------------------------------------------------------------------------------------+

Haven't checked other tables yet

**Comment by s3inlc** [comment]
ah ok, yeah I see. But I think this problem is, because the update failed. Because as soon as there was a successful update, this should not happen anymore. Can you take a look what is inside the `StoredValue` table?

**Comment by gsocgsoc** [comment]
Sure, i did apply the patch and ran the update again so it looks good.

mysql> select * from StoredValue;
+------------------+------------+
| storedValueId    | val        |
+------------------+------------+
| build            | 0          |
| lastStatCleaning | 1542709671 |
| lastZapCleaning  | 1542709671 |
| version          | 0.10.0     |
+------------------+------------+
4 rows in set (0.00 sec)

**Comment by s3inlc** [comment]
Ok, so you took exact the 0.10.0 release version, correct?
If yes, then it looks good. If not, then in build there should definitely be another number than 0.

**Comment by gsocgsoc** [comment]
Yes, i used 0.10.0, will have a look later to see if it created more duplicates

**Comment by s3inlc** [comment]
Yes, I'll do soon. There is another fix which I want to include. The 0.10.0 is not really dysfunctional, the bug only occurred when it was from an upgrade from an older version.

**Comment by DarkGigaByte** [comment]
Nope, it is also an issue for my fresh installation.

**Comment by s3inlc** [comment]
But then something must've gone wrong with the installation. I also did some clean installations myself with the plain release and there was not an issue.
Anyway, just give me a couple of minutes, release is coming.

**Comment by DarkGigaByte** [comment]
Yeah! :D
