### ISSUE TITLE
Hashtopolis server and client friendly advice

### ISSUE THREAD

**Issue by zl9801** [s3inlc/hashtopolis#518]
If the client has an unknown error, such as: no hash type, definition 10-bit full-character, etc., whether the client can skip the error directly, log, do not appear application error, close the window, and need to cancel the task to the server, the client can restart, if not cancel the task on the server, The client restart will always experience application errors.

**Comment by s3inlc** [comment]
I cannot really follow your explanations. Can you please explain more detailed what you are proposing?

**Comment by zl9801** [comment]
Server Publishing task, if there is an unforeseen error, the client will be incorrectly exited, whether the error can be returned to the server to write to the log, skip this wrong task to continue to perform the following tasks. Because in the case of 8 clients or more, it is depressing to need to adjust the task level or delete the task, and then restart all clients, if an unforeseen error is encountered.

**Comment by winxp5421** [comment]
I think what is being suggested is:
If more than 1 agent has an error on a particular task mark the task as bad and move onto the next available task. This way if a bad task is created agents do not sit idle.

**Comment by winxp5421** [comment]
Duplicate  https://github.com/s3inlc/hashtopolis/issues/537
