### ISSUE TITLE
No task available! - All time.

### ISSUE THREAD

**Issue by hyrris** [s3inlc/hashtopolis#520]
Installed hashtopolis Centos 7 (via guide at forum)
add  hash with 1 md5, create task with it. 
Start agent, and at agent:
...
No task available!
No task available!
No task available!
...

Thank u. 

And another question, i have 1 difficult hash, 2+ servers with 8 gpus, can i brute it (without wordlist, -a 3) with hashtopolis?

**Comment by winxp5421** [comment]
Hey.
Please search for questions like this on the Hashtopolis forum/wiki/faq etc. These questions have been answered dozens of times and github issues are not really the right place to ask general questions like this (which have been answered already couple of times) that have nothing to do with bugs/problems in the hashtopolis software.

**Comment by hyrris** [comment]
Sure? Plz give me link for it, i nothing searched about it.

**Comment by s3inlc** [comment]
https://github.com/s3inlc/hashtopolis/wiki/Getting-Started
https://github.com/s3inlc/hashtopolis/wiki/Frequent-Problems#an-agent-doesnt-get-assigned-to-a-task-even-if-he-has-the-highest-priority
https://github.com/s3inlc/hashtopolis/wiki/Trust-or-Secret-Status

That should do it.

**Comment by s3inlc** [comment]
And please note that such questions are more suitable to be asked in the forum, as issues should be used for bugs only.
