### ISSUE TITLE
Duplicate Hashcat Brain settings in server configuration.

### ISSUE THREAD

**Issue by satcom886** [s3inlc/hashtopolis#524]
- Server 0.10.1
- Python client 0.4.0
- Hashcat 5.1.0
- Command independant
- Debug not needed
**Problem description:**
It seems like the configuration for Hashcat Brain is duplicated in server configuration. Also in order to fill-in the first instance of the configuration, I had to fill in the second one. Changing anything in the first instance has no effect.
![brain-settings](https://user-images.githubusercontent.com/28711937/50562762-353b5300-0d17-11e9-9250-91ecdbcefb29.PNG)

**Comment by s3inlc** [comment]
Is it a fresh installation or was it an upgrade from an older version?
If it was an upgrade, from version you started the upgrade?

**Comment by satcom886** [comment]
It was a upgrade first from 0.9.0 to 0.10.0 and then 0.10.0 to 0.10.1

**Comment by s3inlc** [comment]
Ok, there was a bug in the upgrade procedure from 0.9.0 to 0.10.0 which caused that some configuration values were created multiple times. You can simply delete them manually in the `Config` table, afterwards it should not appear twice anymore.

**Comment by s3inlc** [comment]
Great to hear, I assume I can close the issue now.
