### ISSUE TITLE
Pass additional options to prince processor

### ISSUE THREAD

**Issue by zwned** [s3inlc/hashtopolis#526]
- **hashtopolis**: 0.10.1
- **python agent**: 0.4.0.1
- **hashcat**: 5.1.0
- **command**: #HL# passwords.lst --pw-min=10 --elem-cnt-min=2 --elem-cnt-max=4 --case-permute -r dive.rule
- **debug output**: 
```
CALL: ./../../prince/pp64.bin -s 462861476 -l 10520266 ../../files/passwords.lst | ./hashcat64.bin --machine-readable --quiet --status --remove --restore-disable --potfile-disable --session=hashtopolis --status-timer 5 --outfile-check-timer=5 --outfile-check-dir=../../hashlist_5 -o ../../hashlists/5.out --outfile-format=15 -p "  " --remove-timer=5 ../../hashlists/5 -r ../../files/dive.rule --hash-type=1000 -w 4 -O
```

- **Enhancement Description**: Pass options in attack command field to prince as additional options. Based on Prince section of Task Creation Guidelines on the wiki it sounds like this should already present. However, from from the debug output above this isn't happening. 
  - **Desired output** in this case would be:
```
CALL: ./../../prince/pp64.bin --pw-min=10 --elem-cnt-min=2 --elem-cnt-max=4 --case-permute -s 462861476 -l 10520266 ../../files/passwords.lst | ./hashcat64.bin --machine-readable --quiet --status --remove --restore-disable --potfile-disable --session=hashtopolis --status-timer 5 --outfile-check-timer=5 --outfile-check-dir=../../hashlist_5 -o ../../hashlists/5.out --outfile-format=15 -p "  " --remove-timer=5 ../../hashlists/5 -r ../../files/dive.rule --hash-type=1000 -w 4 -O
```

**Comment by peterezzo** [comment]
I second this request, either in the attackcmd or a separate field. I suppose if it's just stripping out things from attackcmd this would really be an enhancement request against the agent, build_prince_command in hashcat_cracker.py. I think the separate field would need a whole API change?

**Comment by s3inlc** [comment]
In the current-dev branch there is the preprocessor integration available now. This means, any program which is a candidate generator (like prince) can be used with Hashtopolis as long as it supports the --skip/--limit/--keyspace commands. 
As you suggested, when setting a preprocessor, you can enter the separate arguments for the preprocessor task which will be used when calling the preprocessor.
Please try it out from the dev branch and let me know if there are any issues.

**Comment by winxp5421** [comment]
I believe this has been implemented. 
I will now close this issue.
If you feel this issue was closed prematurely please re-open and comment why.

**Comment by s6410** [comment]
Hi,
hashtopolis v. 0.11.0 + repository

I have been testing this and enabled debug-mode on my hashtopolis agent.

I run the following command in hashtopolis:

`#HL# wordlist_Prince.txt -r best64.rule --pw-max=25 --elem-cnt-max=25`

the output I am getting from the agent is the following:

`OUTPUT
CALL: ..\..\prince\pp64.exe -s 370779 -l 25481 ..\..\files\wordlist_Prince.txt | hashcat.exe --machine-readable --quiet --status --remove --restore-disable --potfile-disable --session=hashtopolis --status-timer 5 --outfile-check-timer=5 --outfile-check-dir=..\..\hashlist_29 -o ..\..\hashlists\29.out --outfile-format=15 -p "   " --remove-timer=5 ..\..\hashlists\29 -r ..\..\files\best64.rule --hash-type=16200 -O
started cracking`

It doesn't look like the options for PRINCE are passed to the executable on the client or am I missing something?

**Comment by s3inlc** [comment]
I assume you are still using the setup from the master branch. The feature for passing arguments to prince or other preprocessors is implemented, but not merged into master yet. Check out the dev branch to get the newest features. 
Note that with the new feature then, there is a separate command line for the preprocesor where you can put in such flags (e.g. --pw-max, etc.).

**Comment by s6410** [comment]
Thank you for the clarification! I misunderstood winxp5421's answer as the function being implemented in the master branch. My bad!
