### ISSUE TITLE
Superhashlist num cracked not changing - Hashlists it is comprised of are

### ISSUE THREAD

**Issue by zwned** [s3inlc/hashtopolis#529]
- **hashtopolis**: 0.10.1
- **python agent**: 0.4.0.1
- **hashcat**: 5.1.0
- **Problem Description**: I have a Superhashlist created from two Hashlists which already had some hashes cracked prior to creating the Superhashlist. When running a Supertask against the Superhashlist I can see that the tasks are generating cracks. These cracks are being reflected in the individual Hashlists which the Superhashlist is comprised but not increasing the num cracked on the Superhashlist. Hashtype is NTLM and current task is 8 char brute but this happens regardless of task applied.

An partial export of the relevant table is below:

* Table at time M

hashlistId | hashCount | cracked 
---------- | --------- | ------- 
1 | 1154914 | 978012  
2 | 2654582 | 2067561 
5 | 3809496 | 2986857 

* Table at time N

hashlistId | hashCount | cracked 
---------- | --------- | ------- 
1 | 1154914 | 978119  
2 | 2654582 | 2068421 
5 | 3809496 | 2986857

**Comment by s3inlc** [comment]
Issue is fixed on the current-dev branch. If you want to fix numbers from runs before the update, you can go to Config -> Server and then on the bottom click on `Rebuild Chunk Cache`.
