### ISSUE TITLE
Hash List Details - Display error

### ISSUE THREAD

**Issue by vetronexe** [s3inlc/hashtopolis#530]
Server version:  0.10.1
Client version:  0.4.0.1
Hashcat version:  5.0.0

Task display error on the **hash list details page**.  Under the **task cracking this hashlist** table the % searched displays incorrectly.  Some finished tasks display < 100% and other finished tasks display > 100%.  All tasks in the below snapshot have completed to 100% and there are still remaining hashes in the hashlist that are un-cracked.
![untitled](https://user-images.githubusercontent.com/46457749/50788309-f1b18d80-12b0-11e9-8952-a85b8ba9789a.jpeg)

**Comment by s3inlc** [comment]
issue is fixed on the current-dev branch
