### ISSUE TITLE
Feature request - return ID of new hashlist when "createHashlist" is used

### ISSUE THREAD

**Issue by JirkaV** [s3inlc/hashtopolis#533]
Just a minor thing, but it'd be nice if the caller could get the ID of newly created hashlist in the response for "createHashlist" for immediate use in subsequent API calls. Thank you!

**Comment by evilmog** [comment]
confirmed and works in dev

**Comment by JirkaV** [comment]
Thank you!

**Comment by winxp5421** [comment]
Implemented, Closing feel free to reopen if issues arise.

**Comment by JirkaV** [comment]
Thank you!
