### ISSUE TITLE
Create new config option to return isComplete on listtasks for user-api

### ISSUE THREAD

**Issue by evilmog** [s3inlc/hashtopolis#534]
If we can modify:
```
{
"section": "task",
"request": "listTasks",
"accessKey": "mykey"
}
```
to return 
'isComplete':  for each task that would be awesome

Now I know this can cause performance impacts so either a config option to enable it or another endpoint would work just as well.

Example returned JSON:

```
{
"section": "task",
"request": "listTasks",
"response": "OK",
"tasks": [
{
"taskId": 7587,
"name": "test 2",
"type": 0,
"hashlistId": 1,
"priority": 5,
"isComplete": False
}
```
...truncated...

**Comment by s3inlc** [comment]
Feature is implemented on the current-dev branch and will be included in the next release.
Note that this only is for normal tasks, supertasks will not have such a flag.

**Comment by winxp5421** [comment]
Doing @evilmog 's job and closing this. :P
If you feel this was closed in error.. that sucks
