### ISSUE TITLE
Optimum chunk size & criterias to set it

### ISSUE THREAD

**Issue by 0xL0RD** [s3inlc/hashtopolis#539]
- Your current Server version located at the bottom of any Hashtopolis webpage
v 0.10.1

- Current Client version
python agent, version 0.4.0

- Your current Hashcat version
4.1.0

- The exact task command you are trying to run.
-w4 -O -m110 --hex-salt --hex-charset #HL# -a3 -1 00010203040506070809 ?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1

- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

**Describe your problem in as much detail as possible " It's broke " is not a description.**

I have been reading and searching for info about the relevance of "chunk size" in hashtopolis. I know "they [the agents] should take about the same time" to run each chunk (https://github.com/s3inlc/hashtopolis/wiki/Server-Manual ).

I understand that if I have many agents with a big chunk sizes I will only be able to run few agents (and not full capacity). But I do not understand nor why if chunk size is relevant for anything else.

I have these questions if you could please help me:

**(1)** My first question is: what are the **effects of** bigger-smaller **chunk size**s?

**(2)** When running hashtopolis with many hashes in a list (lest´s say 20 hashes), how does the "chunk size" value affect to **running chunks on other agents** if one crack is found?

Let me explain the question with an exagerated example. Let´s say I am running 100 agents with a big chunk size, like 86400 seconds (= 1 day) with a 20 hashes hashlist. 

**(3)** If one of the agents finds the solution for one hash, all the others agents with THAT hash on their chunck will "waste" one full day trying to find solution for it? or, instead, hashtopolis notifies all the agents of found hashes "as soon as they are found" so they do not waste time?

**(4)** I have noticed that speed is greater at the start of an attach than at the end. I guess the greater the temperature of GPUs the lower the speed. Is chunk size aimed at letting the **GPUs cool down**?

**(5)** What **criterias** should I take into account when setting chunk size? Why is 600 seconds the default chunk size?

Thank you

**Comment by s3inlc** [comment]
First of all, such a topic would've been better suited for the forum (https://hashtopolis.org), so keep this in mind in case of such further questions.

* (1) The effects of smaller chunks is a higher overhead as Hashcat needs some time (depending on # of GPUs, size of Hashlist, etc.) to start up, init the kernel, etc. before it actually starts cracking and therefore you need more time in total to complete the whole task. The effects of larger chunks is basically one important one (especially when you have a heterogeneous cluster). When you have only a small number of chunks it might be that all agents are already finished and one has a large chunk where it still needs a lot of time to complete whereas the others are just idling. Additionally, if one of the agents fails/goes down/etc. it might be that the whole work on the chunk it did might be re-done completely. So if the chunk is larger, the work to do again may be larger than with smaller chunks.
* (2) and (3) This depends on the hash type. If they are unsalted, there is no difference (at least not with 20, only if you have a really large list). In case they are salted hashes, for each found the work gets reduced by this amount (e.g. the first of 20 gets cracked, the remaining part can be completed 5% faster).  When a found is submitted to the server, it will notify all other agents running on the same task about this found (it's called zapping) so they can remove it as well from their list. This is exactly done to avoid this waste of resources if the hashes are salted.
* (4) This is a Hashcat specific behaviour. During the running of the task, the speed may vary. If it's a larger difference it's indeed most likely that some kind of temperature limit kicks in and throttles down the GPUs. The chunk size is currently only determined on the benchmark of the task and does not take any throttling into account. Therefore it might be that a chunk takes longer at a later point if the temperature gets high. Note that ideally you would not even get to this problem if your cooling is good enough ;)
* (5) Hmm, that's a difficult question, I would say there is no general rule for that. It depends a lot on your cluster environment, the task, the hashlist, etc. The default of 600 seconds is used to have a fairly flexible standard handling which works also well on unstable setups (e.g. around the world on distributed setups). If you feel confident enough of your setup (and it ideally is a local environment), normally you can set it higher (e.g. 1 hour).

I hope that answers your questions, if anything is unclear, let me know.

**Comment by 0xL0RD** [comment]
thank you, very well explained.
