### ISSUE TITLE
Server parsed a negative keyspace

### ISSUE THREAD

**Issue by koliha** [s3inlc/hashtopolis#542]
I'm currently experiencing odd issues when I'm using an 8 character keyspace.  I've tried using ?a?a?a?a?a?a?a?a  and -1 ?l?d?s?iu ?1?1?1?1?1?1?1?1.  I can run a 7 or 9 character (identical command +/- a ?1 or ?a) without any issue.

I'm not sure if it's related, but I have a 27 gb wordlist (which I imported before) which I had to cut into 1gb files to import to the current version.  I'm not able to use more than one wordlist at a time with any task.  I had to create 28 individual tasks and then link them together with a supertask.  It's ok and works, but if there is a limit of one wordlist it would be nice to allow users to select one wordlist from the dropdown or check one box (all others disabled) for the list that they want.  I seem to remember using multiple wordlists before, but it's been about a year or so (and a lot of what I've been able to find online all points to one wordlist at a time with hashcat).

Manually running the ./hashcat64.bin commandline from a shell results in:
rob@pimento:/ht/crackers/1$ sudo ./hashcat64.bin --keyspace --quiet -a 3 -1 ?l?d?s?u ?1?1?1?1?1?1?1?1  --hash-type=1000 --hwmon-disable -D1,2
7737809375

The other thing that I've noticed is that the output of this command doesn't match what I see in the task/job.

Using 9 characters (job finished in hashcat w/o issue), manual command:
rob@pimento:/ht/crackers/1$ sudo ./hashcat64.bin --keyspace --quiet -a 3 ?a?a?a?a?a?a?a?a?a  --hash-type=1000 --hwmon-disable -D1,2
735091890625

But in hashcat it states that the keyspace size for this job is:
652483009

Huge difference between the two.

- Your current Server version located at the bottom of any Hashtopolis webpage.
Hashtopolis: 0.10.1+repository 

- Current Client version
5.1.0

- Your current Hashcat version
5.1.0

- The exact task command you are trying to run.
./hashcat64.bin --keyspace --quiet -a 3 -1 ?l?d?s?u ?1?1?1?1?1?1?1?1?1  --hash-type=1000 --hwmon-disable -D1,2

- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.
Error during keyspace measure: Command './hashcat64.osx --keyspace --quiet -a 3 -1 ?l?d?s?u ?1?1?1?1?1?1?1?1  --hash-type=1000 -d' returned non-zero exit status 255.

**Comment by winxp5421** [comment]
Please see https://github.com/s3inlc/hashtopolis/wiki/Frequent-Problems

If you continue to have issues feel free to reopen this issue
