### ISSUE TITLE
Supertask List in Hashlist page does not correctly render or work.

### ISSUE THREAD

**Issue by recrudesce** [s3inlc/hashtopolis#543]
- Your current Server version located at the bottom of any Hashtopolis webpage:  0.10.1
- Current Client version: 0.4.0
- Your current Hashcat version: 5.1.0
- The exact task command you are trying to run.:  Running a Supertask from within the hashlist view
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.:  This does not relate to the client. So N/A.

 - Create Hashlist
 - Scroll to bottom to the "Create supertask:" section
 - Only the top one correctly displays the hashcat version, all others do not (as per screenshot).
![image](https://user-images.githubusercontent.com/6450799/52260043-affe1c00-291c-11e9-9256-67a02a1692c2.png)
 - The drop downs are empty.
 - Clicking "Create Supertask" next to any of the options with empty drop downs generates an "Invalid cracker ID!" error.
 - It is possible, however, to apply a Supertask to a hash via the Supertask page.

**Comment by s3inlc** [comment]
The rendering issue is fixed in the current-dev branch.
