### ISSUE TITLE
running client windows

### ISSUE THREAD

**Issue by pccheck** [s3inlc/hashtopolis#546]
**Use github issues only for bugs/feature requests - for discussions, general help and questions use the forum: https://hashtopolis.org**
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage.
- Current Client version
- Your current Hashcat version
- The exact task command you are trying to run.
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

**Describe your problem in as much detail as possible " It's broke " is not a description.**

**Comment by pccheck** [comment]
D:\>python hashtopolis.zip
Starting client 's3-python-0.4.0.1'...
Collecting agent data...
Login successful!
Hashtopolis Server version: 0.10.1 ()
Client is up-to-date!

exist any tutorial how to use under windows7 client?

**Comment by s3inlc** [comment]
Have you checked out the wiki and the repository for the python agent? There should be everything you need and also all config variables are listed.

As written in the issue template, this is a topic for the forum.
