### ISSUE TITLE
Error occurred: request() got an unexpected keyword argument 'json

### ISSUE THREAD

**Issue by tutorialevideo** [s3inlc/hashtopolis#547]
Hi,
I have a strange error any help on this? using ubuntu 14.04 pip3 installed requests too.

python3 hashtopolis.zip
Starting client 's3-python-0.4.0.1'...
Please enter the url to the API of your Hashtopolis installation:
http://IP.x.x.x./api/server.php
Error occurred: request() got an unexpected keyword argument 'json'
Connection test failed!
Please enter the url to the API of your Hashtopolis installation:

**Comment by hops** [comment]
It looks like an issue due to an old requests version. Please post the output of the following commands.
`$ python3 --version`
`$ python3 -c 'import requests; print(requests.__version__)'`
`$ pip3 list | grep requests`
And last but not least:
`$ python3 hashtopolis.zip --debug`

**Comment by tutorialevideo** [comment]
python3 --version
Python 3.4.3
python3 -c 'import requests; print(requests.__version__)'
2.21.0
pip3 list | grep requests
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
requests   2.21.0
python3 hashtopolis                                                                                                             .zip --debug
Starting client 's3-python-0.4.0.1'...
Cleaning hashcat PID file from crackers/1
Collecting agent data...
{'os': 0, 'token': '6EbJCT3rQl', 'action': 'updateInformation', 'devices': ['Int                                                                                                             el(R) Core(TM) i3-6100 CPU @ 3.70GHz', 'NVIDIA Corporation GP104 [GeForce GTX 10                                                                                                             70] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA C                                                                                                             orporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForc                                                                                                             e GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', '                                                                                                             NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)'], 'uid': '6269db76-d92c-4f                                                                                                             a3-bd8c-92587ae94818'}
Error occurred: request() got an unexpected keyword argument 'json'
Information update failed!
Collecting agent data...
{'os': 0, 'token': '6EbJCT3rQl', 'action': 'updateInformation', 'devices': ['Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)'], 'uid': '6269db76-d92c-4fa3-bd8c-92587ae94818'}
Error occurred: request() got an unexpected keyword argument 'json'
Information update failed!
Collecting agent data...
{'os': 0, 'token': '6EbJCT3rQl', 'action': 'updateInformation', 'devices': ['Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)'], 'uid': '6269db76-d92c-4fa3-bd8c-92587ae94818'}
Error occurred: request() got an unexpected keyword argument 'json'
Information update failed!
Collecting agent data...
{'os': 0, 'token': '6EbJCT3rQl', 'action': 'updateInformation', 'devices': ['Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)', 'NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)'], 'uid': '6269db76-d92c-4fa3-bd8c-92587ae94818'}
Error occurred: request() got an unexpected keyword argument 'json'
Information update failed!

**Comment by MilzoCSP** [comment]
Your python3 version is a little old, circa 2015, I would install more recent version from apt or build from source.

**Comment by hops** [comment]
I can confirm that it must be an issue with Python 3.4 combined with requests.
Both Python 3.4 and Ubuntu 14.04 will be end of life in 2-3 months.
Because of this I will not make an effort to make the agent compatible with it. If you really have to keep using Ubuntu 14.04 your best bet to try and install a more recent version of Python like @MilzoCSP suggested.
The best advice I can give you is to upgrade your Ubuntu.

**Comment by tutorialevideo** [comment]
Thank you for this i will do my best to upgrade. :)
