### ISSUE TITLE
www-data issues with VestaCP

### ISSUE THREAD

**Issue by harmonherring** [s3inlc/hashtopolis#548]
Running my server on Ubuntu 16.04 with Nginx, and I also have VestaCP installed.  Have tried with multiple versions of the server software, including the latest.  

When I go to the initial setup page, I'm told that the www-data user is unable to write to the directory.  I've chown'd just about everything related to the folder.  

The reason I include VestaCP in all of this is because I'm able to get hashtopolis to work on just about any server config that doesn't have VestaCP installed.

Anybody got any ideas?  Thanks

**Comment by winxp5421** [comment]
To be completely honest never even heard of VestaCP.
There is one thing permission wise I can think of though it's possible the Control Panel enables SELinux and that could be blocking the www-data user from writing to the dir. 

I don't have very many options/ideas to give you without installing VestaCP and troubleshooting

**Comment by winxp5421** [comment]
This issue has been open and in the Waiting on user feedback for quite some time. 
Seen as this is something extremely specific about a certain environment i'm going to close this.
If you feel this should be re-opened feel free to do so but, please update with more information.
