### ISSUE TITLE
the hashrate drops dramatically when prompt with "Detected low UTIL value, restart chunk with piping..."

### ISSUE THREAD

**Issue by cdutboy928** [s3inlc/hashtopolis#549]
**Use github issues only for bugs/feature requests - for discussions, general help and questions use the forum: https://hashtopolis.org**
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage.
Hashtopolis: 0.10.1
- Current Client version
's3-python-0.4.0'
- Your current Hashcat version
hashcat-5.1.0
- The exact task command you are trying to run.
-a 0 #HL# 43G.txt
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.
Detected low UTIL value, restart chunk with piping...
**Describe your problem in as much detail as possible " It's broke " is not a description.**
When prompt with 'Detected low UTIL value, restart chunk with piping...', the hashrate will drop from 1.12MH/s to 189kh/s. So the cracking speed drop dramatically! 
And the hashrate will stay at 1.12MH/s when I run "hashcat64.exe -m 2500 hash -w 4 -a 0 43G.txt".
Please help me.

**Comment by hops** [comment]
We might disable the piping feature on straight dictionary attacks in the future.
For now you have to set `"allow-piping": false` in your agent's config file.

**Comment by cdutboy928** [comment]
So the problem will be solved with `"allow-piping": false` ? I will have a try. Thank you.

**Comment by cdutboy928** [comment]
It works! Thank you so much!!!

**Comment by cdutboy928** [comment]
Found that the hashrate is very low when running "-a 1" tasks with `"allow-piping": false` configured on the agent. I need to change it to `"allow-piping": true` when running "-a 1" tasks, or are there any other solutions? Thanks a lot.

**Comment by s3inlc** [comment]
There are some cases of tasks, where it is worth to use the piping feature. E.g. when you have a very small wordlist and a lot of rules or in cases of -a1 it might be faster if your right hand wordlist is pretty small.
