### ISSUE TITLE
[dev branch] Health check, invalid health check id

### ISSUE THREAD

**Issue by TheWorkingDeveloper** [s3inlc/hashtopolis#550]
Health check requested by server!
Retrieving health check settings...
Starting check ID 2
Error on sending health check results: {'message': 'Invalid health check id!', 'action': 'sendHealthCheck', 'response': 'ERROR'}

This ID does exist and is assigned to the client.
Please note this is on the current-dev branch.

**Comment by s3inlc** [comment]
Can you please re-produce the error with debug logging enabled to get more information?

**Comment by s3inlc** [comment]
The issue is fixed on the current-dev branch.
