### ISSUE TITLE
hashcat getting rid of 32-bit binaries

### ISSUE THREAD

**Issue by hops** [s3inlc/hashtopolis#552]
It seems like with the upcoming release there won't be any 32-bit binaries anymore, see: https://github.com/hashcat/hashcat/commit/68d6d36761e7f5ddb3b58cb90b6a89e8fe9e088a
This commit also renames the binary from hashcat64.ext to hashcat.ext which I believe will cause the agent to fail.
This issue is mainly a reminder for myself and/or @s3inlc

**Comment by s3inlc** [comment]
Agent is updated to be able to handle both variants with and without the 32/64 in the filename. It will search for hashcat.<ext> first and fall back to the old naming scheme if there is no such file.

Included in release 0.5.0: https://github.com/s3inlc/hashtopolis-agent-python/releases/tag/v0.5.0
