### ISSUE TITLE
API to assign an agent to a task

### ISSUE THREAD

**Issue by tosiara** [s3inlc/hashtopolis#556]
Running latest https://github.com/s3inlc/hashtopolis/commit/577b53f0dc6804658ff6d896efc634d501630985
Hashtopolis: 0.10.1+repository

I'm looking for API call to assign an agent a task. There is `taskUnassignAgent` which unassignes an agent from his current task. But how to get reverse action - assign agent ID to a task ID?

Thanks

**Comment by s3inlc** [comment]
Feature is added to the current-dev branch and will be included in the next release.

Please note that in case you assign an agent to a task but there is another task with a higher priority, it will get re-assigned automatically to the task with the highest priority.

**Comment by tosiara** [comment]
Thanks!
