### ISSUE TITLE
Mask API Keys not belonging to a user

### ISSUE THREAD

**Issue by evilmog** [s3inlc/hashtopolis#565]
If you could enable an option to mask api keys not belonging to a user and have that set via a file on the fs and not via the webui it would be greatly appreciated.

Each api key has a user associated to it,  some environments have multiple admins and it would be handy to ensure that only the user to whom an api key belongs can see that api key in full.

**Comment by s3inlc** [comment]
The feature is added in the current-dev branch, please close if this issue is resolved.

**Comment by s3inlc** [comment]
I'm going to close the issue, the feature was tested and working. If this is not the case, please re-open.
