### ISSUE TITLE
Cracked count and left count not changing on SuperHashlists after import pre-cracked hashes

### ISSUE THREAD

**Issue by Therindor** [s3inlc/hashtopolis#569]
- Hashtopolis: 0.11.0
- hashtopolis client 0.5.0
- hashcat v5.1.0

Similarly with Issue #529, Superhashlists cracked counts and left counts are not changed after import pre-cracked hashes. Individual hashlists that the superhashlist is comprised of do however update, so it would make sense if the superhashlist also does this.

**Comment by s3inlc** [comment]
As you said, it was similar to issue #529 and seems to be fixed now in the current master branch. Therefore I close this issue, please re-open there is still a problem.
