### ISSUE TITLE
Deleting a task may take very long time

### ISSUE THREAD

**Issue by tosiara** [s3inlc/hashtopolis#572]
Hi,

I have had a long running task. After it has completed I tried to delete it. It took more than 15 minutes. During that mysql was using close to 100% of CPU and the entire Hashtopolis was unresponsive.

This was the waiting query:
```
mysql> SHOW FULL PROCESSLIST;
+-----+---------+-----------+---------+---------+------+----------+-------------------------------------+
| Id  | User    | Host      | db      | Command | Time | State    | Info                                |
+-----+---------+-----------+---------+---------+------+----------+-------------------------------------+
| 110 | ha      | localhost | ha      | Query   |  998 | updating | DELETE FROM Speed WHERE taskId='110'|
| 282 | root    | localhost | NULL    | Query   |    0 | starting | SHOW FULL PROCESSLIST               |
+-----+---------+-----------+---------+---------+------+----------+-------------------------------------+
2 rows in set (0.01 sec)
```
I think something needs to be optimized here. Either purge old records in smaller batches or run this delete task asynchronously somehow

Hope this help

**Comment by s3inlc** [comment]
Sorry about the delay in answering this. Indeed you are right that there was something not optimized, the indexes on taskId and agentId were missing.

Are you able to reproduce deleting such a task with a lot of speed measurements? If yes, it would be nice if you could check out the current-dev branch and see if this has improved now.

**Comment by tosiara** [comment]
I will and let you know

**Comment by s3inlc** [comment]
I'm going to close the issue, the feature was tested and working. If this is not the case, please re-open.
