### ISSUE TITLE
[FEATURE PROPOSAL] Use system-wide Hashcat?

### ISSUE THREAD

**Issue by satcom886** [s3inlc/hashtopolis#574]
The precompiled binaries available on hashcat.net are X86 only. Using them on ARM (or any other CPU architecture) is impossible (or simply not worth it, like emulating X86 hardware with QEMU, which brings performance loss). Would it be possible to use the version that is installed system-wide (like from a package manager)? I think this would only work for Linux clients, since in Windows you would need to manually add Hashcat to PATH to "install" it.

**Comment by vetronexe** [comment]
You can compile your own hashcat from source and host on the same web server your hashtopolis is running on.  Update the cracker url settings under cracker - binaries to where you are going to serve the archive containing the compiled files from.  This will allow you to have several versions compiled for whatever architecture that is supported by hashcat.

**Comment by satcom886** [comment]
Thanks, that did not hit me!

**Comment by winxp5421** [comment]
I believe this was answered and a solution was found.
If you feel this issue was closed in error feel free to re-open and update us.

**Comment by satcom886** [comment]
I still feel like we should have the option to use the system's installation of Hashcat. The problem with using multiple cracker binaries is that you can't have the different architectures working on one task.

**Comment by satcom886** [comment]
Few other solutions that come to mind:

## Allow multiple architectures per cracker binary with automatic architecture detection.
 - The client would send it's detected architecture to the server.
 - The server would have a hard-coded list of valid architectures.
 - The con of this one is that there are many architectures and hunting down each one would be problematic.

## Allow multiple architectures per cracker binary with manual architecture assignment.
 - Instead of hard-coding the architectures, allow the user to specify them.
 - E.g. Crackers -> Architectures (specify architectures here), Crackers -> Binaries -> hashcat -> add version (add a dropdown that allows to choose the version's architecture) and Agents -> agent1 (add a dropdown to choose the Agent's architecture).
 - Now the Agent chooses the version of the binary that matches it's architecture.
 - If someone only uses one architecture (say `x86_64`), they could ignore the architectures completely and just use something like "Default".

## Combination of the first 2 options
 - The client would detect and report it's architecture to the server. If this architecture is new, it would be added to the *architectures* list and the Agent would be assigned that arch. If the architecture already exists in *architectures*, just set the Agent's architecture to that.
 - Also allow manually setting architectures in case the wrong architecture is detected.

## Choose the Cracker version in the Agent properties instead of the Task properties
 - This would also allow multiple architectures to be assigned to one task but would probably be inconvenient because when a new version of Hashcat is released, it would have to be set for each Agent separately.

Personally I like the second and third options the most. I don't know if I'm making any sense here...
