### ISSUE TITLE
Force use the client's system (native) hashcat implementation

### ISSUE THREAD

**Issue by cyro666** [s3inlc/hashtopolis#577]
Hi!

Would it be possible to implement this feature?

A switch where you can force set the hashcat version to the machine's native installation. Essentially I have a few machines that don't work properly with the official hashcat releases, but if I compile a dynamically linked hashcat using client's system OpenCL libraries, it works.

The problem is, (if I understand correctly) it is only possible to use the hashcat version that is supplied by the client. I want to be able to call the client's natively installed hashcat in `/usb/bin/hashcat` (also callable simply with `hashcat`, since it is in `PATH`). 

I did this manually with a workaround, by changing the supplied hashcat binary to a symlink to /usr/bin/hashcat. But it would be nice if I wouldn't have to do this workaround.

**Comment by satcom886** [comment]
Hi! I already made this suggestion here: #574
