### ISSUE TITLE
Python agent: unhandled exception during subprocess causes agent to die

### ISSUE THREAD

**Issue by tosiara** [s3inlc/hashtopolis#578]
Hashtopolis: 0.10.1+repository
Agent: s3-python-0.5.0 
Cracker: custom cracker
Action: get keyspace

I accidentally made a typo in custom cracker file name. As a result my agent got an unhandled exception and went down:
```
b'{"action":"getChunk","response":"SUCCESS","status":"keyspace_required"}'
'..\crackers\6\custom.exe' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "hashtopolis.zip\__main__.py", line 338, in <module>
  File "hashtopolis.zip\__main__.py", line 207, in loop
  File "hashtopolis.zip\htpclient\generic_cracker.py", line 119, in measure_keyspace
  File "C:\Python37\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '..\crackers\6\custom.exe keyspace #HL# ' returned non-zero exit status 1.
```
Actual behavior: agent dies
Expected behavior: should log error and keep running

Adding try/catch around subprocess call would be a great enhancement

**Comment by tosiara** [comment]
Steps to repro:
1. Create test executable and name it `test.exe`
2. Add it to 7z archive and upload somewhere
3. Add custom cracker and give it a name `custom`
4. Assign a custom cracker task to an agent
5. As soon as agent picks a task it will download the custom cracker, extract and try to run `custom.exe`. Since file was named `test.exe` agent will not find it and die

**Comment by s3inlc** [comment]
Thanks for the issue. Can you please verify with the newest current-dev commit of the agent repository that this case does not happen again.
