### ISSUE TITLE
Small speed when use Hashtopolis!

### ISSUE THREAD

**Issue by kivik92** [s3inlc/hashtopolis#579]
**Use github issues only for bugs/feature requests - for discussions, general help and questions use the forum: https://hashtopolis.org**
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage.
- Current Client version
- Your current Hashcat version
- The exact task command you are trying to run.
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

**Describe your problem in as much detail as possible " It's broke " is not a description.**
Hi
Hashtopolis: 0.11.0
Client version 0.5.0
Hashcat 5.1.0
-a0 #HL wordlist.tx
Debug clietn: hashcat64.exe --keyspace --quiet -a 0 
Thx for your beautiful software,but I have some problem with it.
I installed it on my vps server (Ubuntu 18_04) all is fine, all work very well, but I have some problem with speed, When I use local hashcat my GPUs give me 3500 KH/s
But when I use hashtopolis with basic command as -a 0 #HL wordlis.txt speed is 650 KH\s.
Whai I must do that my speed when I use hashtopolis will be as I use hashcat local on my PC.
P.S.
Sorry for my English!

**Comment by winxp5421** [comment]
1. I don't know how large your wordlist is
2. I don't know what hash type you are attacking

This looks like a classic not supplying enough work to keep the GPU's busy. 
A couple of things you can try.

- Switch to the other benchmarking type  (Runtime Benchmark, Speed test)
- Supply more work with rules or Hybrid attack.

This is not really a bug and questions / remarks/ problems like this should be directed to the hashtopolis forum. https://hashtopolis.org
