### ISSUE TITLE
Runner service not starting due to missing DB connection file

### ISSUE THREAD

**Issue by zwned** [s3inlc/hashtopolis#583]
- **Server Version**: Hashtopolis: 0.11.0+repository
- **Client Version**: s3-python-0.5.0
- **Hashcat version**: 5.1.0.7

Current runner.zip from (https://github.com/s3inlc/hashtopolis/tree/master/src/inc/runner/runner.zip) is looking for db.conf (specified in htpserver/HTDatabase.py). However after a fresh install this file did not exist. It was called conf.php. I ended up copying inc/conf.php to inc/db.php to get the service running.

Running `python3 runner.zip status` returns `Service is running.` now which is good, but Im still seeing `Service runner status: Service is not running. ` under Config > Server > Multicast

**Comment by s3inlc** [comment]
Thanks for reporting this issue. It seems that for some reason the built zip which was sent with hashtopolis was not updated with the new config path, as it was correct in the runner repository.
I now updated the zip, so it uses conf.php as it should. Please verify and close this issue if it is fixed.
