### ISSUE TITLE
Prince wordlist assignment

### ISSUE THREAD

**Issue by s6410** [s3inlc/hashtopolis#592]
- Hashtopolis 0.11.0 + 106 (current dev)
- Agent: python 0.5.1
- Hashcat: V5.1.0-1474-gd315f614+
- pp64.exe "wordlist" | hashcat.exe "parameters"

When I choose a wordlist, it is automatically added to the "Command Line" text box. I then have to cut it out from there and paste it to the prince parameters text box otherwise pp64.exe is run without a wordlist. The debug then shows:

`CALL: pp64.exe --keyspace` which doesn't return any result.

Perhaps adding another column of checkboxes for PRINCE so that the wordlist chosen there is not added to the hashcat command line but the Prince parameter text box?

**Comment by s3inlc** [comment]
I implemented the feature now and it will be shortly merged into the current-dev branch. There are two columns of checkboxes now, one for the normal command and one for the preprocessor command.
