### ISSUE TITLE
Agent binaries - wrong folder "static"

### ISSUE THREAD

**Issue by s6410** [s3inlc/hashtopolis#593]
Hashtopolis 0.11.0 + 106 (current dev)
Agent: python 0.5.1
Hashcat: V5.1.0-1474-gd315f614+

When updating the agent binary on the hashtopolis server it tells me to put the hashtopolis.zip-file in the "static" folder. When doing this an endless loop of update on the agent is created as the agent is never updated.

Putting the agent binary in the "bin" folder solves the problem.

**Comment by s3inlc** [comment]
So is this written somewhere in the documentation which needs to be updated? (that the zip should be put in the static folder)

**Comment by s6410** [comment]
It is written here:
Config --> Agent BInaries --> Click on Edit --> Filename (placed in "static" folder)
binaries.php

**Comment by s3inlc** [comment]
thanks
