### ISSUE TITLE
Support for new --outfile-data from hashcat

### ISSUE THREAD

**Issue by derlange2k** [s3inlc/hashtopolis#594]
Hi all,

i can't use hashtopolis with the new --outfile-data option in hashcat. This is the new feature:

https://github.com/hashcat/hashcat/commit/13675d2965418be7d4129066cffb5a6b1964a24b

Would it be possible to add support for this in hashtopolis? Thank you.

**Comment by hops** [comment]
This is already tracked and fixed in #584
Use the current-dev branch of the agent: https://github.com/s3inlc/hashtopolis-agent-python/tree/current-dev

**Comment by AlexanderKgr** [comment]
updated agent and now i receive the following error on agents page on hashtopolis
![image](https://user-images.githubusercontent.com/25532758/74144028-9e70e380-4c04-11ea-8031-374e64314c92.png)

**Comment by s3inlc** [comment]
@AlexanderKgr what hashcat version are you running with it, which hashtopolis server version?

**Comment by AlexanderKgr** [comment]
hashcat version latest beta (amd gpu with issue on latest stable), and hashtopolis version 0.11.0

**Comment by s3inlc** [comment]
ok, so is it 0.11.0 release version or from the current-dev branch?

Also did you check that the agent was correctly updated and it is then still running the correct version from the dev branch?

**Comment by AlexanderKgr** [comment]
it is the 0.11.0 release version for the hashtopolis server and the agent is the current dev branch - git cloned it today

**Comment by s3inlc** [comment]
Ok, I mean ideally if the agent runs on dev, the server ideally should do so as well. But in that case this would not be relevant, so it should be fine.

Can you send a snippet of the debug output of the agent, especially where it tries to run the corresponding task (ideally also including where it reads out the hashcat version). Please mask sensitive parts of the output as needed.

**Comment by AlexanderKgr** [comment]
> Ok, I mean ideally if the agent runs on dev, the server ideally should do so as well. But in that case this would not be relevant, so it should be fine.
> 
> Can you send a snippet of the debug output of the agent, especially where it tries to run the corresponding task (ideally also including where it reads out the hashcat version). Please mask sensitive parts of the output as needed.

can you help me with the snippet of the debug output of the agent? i don't know how to do it

**Comment by s3inlc** [comment]
Just start the agent with `python3 hashtopolis.zip --debug` or if you have it extracted, start with `python3 __main__.py --debug`.

**Comment by AlexanderKgr** [comment]
`Got task with id: 14
{'action': 'downloadBinary', 'token': '7Yj5gtrhc4', 'type': 'cracker', 'binaryVersionId': '5'}
http://192.168.66.214:80 "POST /api/server.php HTTP/1.1" 200 153
b'{"action":"downloadBinary","response":"SUCCESS","url":"https:\\/\\/hashcat.net\\/beta\\/hashcat-5.1.0%2B1658.7z","name":"hashcat","executable":"hashcat.bin"}'
{'action': 'getHashlist', 'token': '7Yj5gtrhc4', 'hashlistId': 2}
http://192.168.66.214:80 "POST /api/server.php HTTP/1.1" 200 98
b'{"action":"getHashlist","response":"SUCCESS","url":"getHashlist.php?hashlists=2&token=7Yj5gtrhc4"}'
http://192.168.66.214:80 "GET /getHashlist.php?hashlists=2&token=7Yj5gtrhc4 HTTP/1.1" 200 271
Downloading: [===========================================================================================================]
{'action': 'checkClientVersion', 'token': '7Yj5gtrhc4', 'version': '0.5.0', 'type': 'python'}
http://192.168.66.214:80 "POST /api/server.php HTTP/1.1" 200 67
b'{"action":"checkClientVersion","response":"SUCCESS","version":"OK"}'
Client is up-to-date!
Got cracker binary type hashcat
{'action': 'getChunk', 'token': '7Yj5gtrhc4', 'taskId': 14}
http://192.168.66.214:80 "POST /api/server.php HTTP/1.1" 200 63
b'{"action":"getChunk","response":"SUCCESS","status":"benchmark"}'
Benchmark task...
CALL: ./hashcat.bin --machine-readable --quiet --progress-only --restore-disable --potfile-disable --session=hashtopolis -p "   " ../../hashlists/2 -a 3 ?d?d?d?d?d?d?d?d  --hash-type=5600  -o ../../hashlists/2.out
{'action': 'sendBenchmark', 'token': '7Yj5gtrhc4', 'taskId': 14, 'type': 'speed', 'result': '100000:220.31'}
http://192.168.66.214:80 "POST /api/server.php HTTP/1.1" 200 64
b'{"action":"sendBenchmark","response":"SUCCESS","benchmark":"OK"}'
Server accepted benchmark!
{'action': 'downloadBinary', 'token': '7Yj5gtrhc4', 'type': 'cracker', 'binaryVersionId': '5'}
http://192.168.66.214:80 "POST /api/server.php HTTP/1.1" 200 153
b'{"action":"downloadBinary","response":"SUCCESS","url":"https:\\/\\/hashcat.net\\/beta\\/hashcat-5.1.0%2B1658.7z","name":"hashcat","executable":"hashcat.bin"}'
{'action': 'getChunk', 'token': '7Yj5gtrhc4', 'taskId': 14}
http://192.168.66.214:80 "POST /api/server.php HTTP/1.1" 200 93
b'{"action":"getChunk","response":"SUCCESS","status":"OK","chunkId":6,"skip":0,"length":100000}'
Start chunk...
CALL: ./hashcat.bin --machine-readable --quiet --status --restore-disable --session=hashtopolis --status-timer 5 --outfile-check-timer=5 --outfile-check-dir=../../hashlist_2 -o ../../hashlists/2.out --outfile-format=15 -p " " -s 0 -l 100000 --potfile-disable --remove --remove-timer=5 ../../hashlists/2 -a 3 ?d?d?d?d?d?d?d?d  --hash-type=5600
started cracking
HC error: Invalid --outfile-format value specified.
{'action': 'clientError', 'token': '7Yj5gtrhc4', 'taskId': 14, 'chunkId': 6, 'message': 'Invalid --outfile-format value specified.'}
http://192.168.66.214:80 "POST /api/server.php HTTP/1.1" 200 45
b'{"action":"clientError","response":"SUCCESS"}'
finished chunk
`


here is the output of client with debug option

**Comment by s3inlc** [comment]
You are missing the output of `CALL: ./hashcat.bin --version` which tells me that you are not running the dev agent. Either you are still on the master branch after cloning, or the newest updates were not pulled.

**Comment by AlexanderKgr** [comment]
thanks for replying.
installed dev version of client and no i have another issue
![image](https://user-images.githubusercontent.com/25532758/74221947-e69f0d00-4cbb-11ea-8f5f-af0fa73b7d01.png)

**Comment by hops** [comment]
Most likely there's a new beta of hashcat and therefore the download link changed.
@AlexanderKgr I'm closing this issue as Github issues are only intended to be used for bug reports and feature requests, not to ask for support.
For support either head over to the forum at https://hashtopolis.org or our Discord at https://discord.gg/S2NTxbz
