### ISSUE TITLE
Clarify and adapt to input and output format of mode 16800/16801

### ISSUE THREAD

**Issue by s3inlc** [s3inlc/hashtopolis#603]
The separator of the modes was changed from * to : and also the way it's printed when found needs to be considered.

**Comment by s3inlc** [comment]
The features to handle the PMKID variants are implemented now.

@beecushman as you were interested in these modes as well, if you could try these out as well, to make sure that it not only works for me, that would be great. The code is in the branch `enhancement/pmkid`.

**Comment by beecushman** [comment]
Thanks for making the changes to handle the new outputs. I created and tested a PMKID today and it looks to be working great!

![image](https://user-images.githubusercontent.com/20655306/74703185-3b152180-51c1-11ea-83c9-d318e1f1fff1.png)

**Comment by s3inlc** [comment]
Thanks for reporting back, I'll merge the changes soon.
