### ISSUE TITLE
Cant search for hashes

### ISSUE THREAD

**Issue by iMoD1998** [s3inlc/hashtopolis#616]
Hi

When searching for a hash this happens:

`Column 'hashlistId' in where clause is ambiguous in /var/www/hashtopolis/src/dba/AbstractModelFactory.class.php:607\nStack trace:\n
#0 /var/www/hashtopolis/src/dba/AbstractModelFactory.class.php(607): PDOStatement->execute(Array)\n
#1 /var/www/hashtopolis/src/dba/AbstractModelFactory.class.php(638): DBA\\AbstractModelFactory->filterWithJoin(Array)\n
#2 /var/www/hashtopolis/src/dba/models/HashFactory.class.php(56): DBA\\AbstractModelFactory->filter(Array, false)\n
#3 /var/www/hashtopolis/src/inc/handlers/SearchHandler.class.php(72): DBA\\HashFactory->filter(Array)\n
#4 /var/www/hashtopolis/src/inc/handlers/SearchHandler.class.php(21): SearchHandler->search()\n
#5 /var/www/hashtopolis/src/search.php(21): SearchHandler->handle('search')\n
#6 {main}\n  thrown in /var/www/hashtopolis/src/dba/AbstractModelFactory.class.php on line 607, referer: https://domain.com/search.php`

**Comment by Undercoverdog** [comment]
Hi, I also have the problem. I tried install on 2 different Devices. I got the same error.
Is your hashtopolis now working correctly? (sorry for my English)

**Comment by s3inlc** [comment]
Please test if the changes in the issue/hash-search branch (https://github.com/s3inlc/hashtopolis/tree/issue/hash-search) fix this issue. If yes, let me know so I can merge it.

**Comment by iMoD1998** [comment]
Still seems to be broken.

`Column 'hashlistId' in where clause is ambiguous in /var/www/hashtopolis/src/dba/AbstractModelFactory.class.php:607\nStack trace:\n#0 /var/www/hashtopolis/src/dba/AbstractModelFactory.class.php(607): PDOStatement->execute(Array)\n#1 /var/www/hashtopolis/src/dba/AbstractModelFactory.class.php(638): DBA\\AbstractModelFactory->filterWithJoin(Array)\n#2 /var/www/hashtopolis/src/dba/models/HashFactory.class.php(56): DBA\\AbstractModelFactory->filter(Array, false)\n#3 /var/www/hashtopolis/src/inc/handlers/SearchHandler.class.php(76): DBA\\HashFactory->filter(Array)\n#4 /var/www/hashtopolis/src/inc/handlers/SearchHandler.class.php(21): SearchHandler->search()\n#5 /var/www/hashtopolis/src/search.php(21): SearchHandler->handle('search')\n#6 {main}\n  thrown in /var/www/hashtopolis/src/dba/AbstractModelFactory.class.php on line 607, referer: https://domain.com/search.php`

**Comment by s3inlc** [comment]
Sorry my fault. I only fixed it on one of the two queries, so it was now failing on the second.
In the branch the fix should now work perfectly.

**Comment by iMoD1998** [comment]
Yep that fixed it, awesome 👍
