### ISSUE TITLE
Agent not passing Cracked Hashes to Server

### ISSUE THREAD

**Issue by kivik92** [s3inlc/hashtopolis#622]
**Use github issues only for bugs/feature requests - for discussions, general help and questions use the forum: https://hashtopolis.org**
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Hashtopolis: 0.12.0 commit 11758c2 branch master 
- Current Client version s3-python-0.6.0
- Your current Hashcat version - 5.1.0
- The exact task command you are trying to run --a 0 #HL# --hwmon-disable wordlist.txt
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client. -
Sending 1 cracks...
{'action': 'sendProgress', 'token': 'BjXyYbLZso', 'chunkId': 13020, 'keyspaceProgress': 722412810, 'relativeProgress': 9040, 'speed': 1051244, 'state': 5, 'cracks': [['4473dd4c94f482825e26923a3239b512:f0b429545714:742f68d504c7:home_sweet_home', 'HelloWorld123', '7361766368656e6b6f313233', '722818059']]}
https://hashtopolis.manibrain.com:443 "POST /api/server.php HTTP/1.1" 200 80
b'{"action":"sendProgress","response":"SUCCESS","cracked":0,"skipped":1,"zaps":[]}'
Progress: 90.40% Speed:   1.05MH/s Cracks: 1 Accepted: 0 Skips: 1 Zaps: 0

**Describe your problem in as much detail as possible " It's broke " is not a description.**
Describe your problem in as much detail as possible " It's broke " is not a description.
I 've created a Hashlist with hash type WPA/WPA2 and format HCCAPX / PMKID, then I've uploaded a HCCAPX file and it found 1 hashes.
Then I've created a simple Super Task for cracked my hashlist
Then the normal process, task assigned, agent downloads, execute Hashcat and crack 5 hashes and generate this output file.
I added notification via Telegram and recive Hashlist 'Fixed_Error_Pass_'  was cracked completely, BUT I in the GUI comand center I don't see anything cracked hashes, but in the log of agent it is show, that my Hashlit cracked, but Don't send information to the server.
Plz HELP!!!

**Comment by s3inlc** [comment]
I will try to reproduce the error when I get the time.
Note that the 5.1.0 version of hashcat is fairly old and it is confirmed that hashtopolis works with the newer beta releases of hashcat regarding the WPA hashes. There was a change of format how hashcat prints founds. So as a quick way to get it working, I just recommend to use the newest hashcat beta versions.

**Comment by kivik92** [comment]
Hi
Thx for quick answer
I used this hashtype: 2500, 
WPA/WPA2 | HCCAPX / PMKID
And added file as .hccapx

**Comment by kivik92** [comment]
> I will try to reproduce the error when I get the time.
> Note that the 5.1.0 version of hashcat is fairly old and it is confirmed that hashtopolis works with the newer beta releases of hashcat regarding the WPA hashes. There was a change of format how hashcat prints founds. So as a quick way to get it working, I just recommend to use the newest hashcat beta versions.
> 
> Can you please exactly state which hash mode you were running?

And can you send me URL or other information where I can get new beta release of hashcat

**Comment by s3inlc** [comment]
https://hashcat.net/beta

**Comment by kivik92** [comment]
> https://hashcat.net/beta

Thx
Check now How It works

**Comment by kivik92** [comment]
Very Thx
It is help me
