### ISSUE TITLE
dispatched - searched bug

### ISSUE THREAD

**Issue by makopolo9** [s3inlc/hashtopolis#624]
Hello

I try to play with the system,
I put some hashes in the system after a while the Dispatched got 100% and the searched got 300% 
all the agent except from one leave that task and the task not finished

**Comment by s3inlc** [comment]
I'm aware that sometimes it happens that the searched value is way off and going over 100% which definitely is a bug. I haven't tried to be able to consistently reproduce it, if you have a case where you can make it happen each time with a specific task/number of agents/etc., please let me know

**Comment by SherlockNL** [comment]
This has been fixed in https://github.com/s3inlc/hashtopolis/pull/680, and has recently been merged to the master branch.

**Comment by s3inlc** [comment]
Thanks for the notification, so I'm going to close the issue.

**Comment by cpt-kernel** [comment]
Still a known issue. I've seen this twice today cracking NTLM with a single agent. Dispatched is 100% and searches is 600%

![image](https://user-images.githubusercontent.com/23063172/107604389-097d3d80-6bfe-11eb-8457-e66104b36853.png)
