### ISSUE TITLE
Changing group assignment of hash list is not visible

### ISSUE THREAD

**Issue by s6410** [s3inlc/hashtopolis#627]
Hashtopolis: Latest stable release

When changing the group that a hash list is assigned to it never changes from Default Group in the webgui but the change _is_ actually done as agents that are not part of the new group won't have access to the hash list anymore.

The value that should change is "Member of access group", it should reflect the change in "Access group" drop down menu.

**Comment by s3inlc** [comment]
I was able to reproduce it, can you please test if the changes in the branch `issue/hl-access-group` actually fix it also for you?

**Comment by s6410** [comment]
I will try as soon as I can set up a testing environment. Thanks!

**Comment by s3inlc** [comment]
Any update on this?

**Comment by s6410** [comment]
Hi! Late reply, sorry! It works
