### ISSUE TITLE
Prince with Hashcat rule, missing space in call

### ISSUE THREAD

**Issue by backi83** [s3inlc/hashtopolis#629]
Hey S3inlc,

the hashcat call using prince and rule fails because of a missing space in command:

**CALL:** ..\..\preprocessor\1\pp64.exe --skip 0 --limit -1605  --elem-cnt-min=2 --elem-cnt-max=5 --pw-min=8 ..\..\files\silen.dic | hashcat64.exe --machine-readable --quiet --status --remove --restore-disable --potfile-disable --session=hashtopolis --status-timer 5 --outfile-check-timer=5 --outfile-check-dir=..\..\hashlist_22 -o ..\..\hashlists\22.out --outfile-format=15 -p " " --remove-timer=5 ..\..\hashlists\22-r ..\..\files\leetspeak.rule  --hash-type=5600 --force -D 1
**started cracking**
**HC error: No hashes loaded.**

Direct call offers as expected:
Hash '..\..\hashlists\22-r': Separator unmatched

**Task details**
Attack command:  -r leetspeak.rule #HL#
Preprocessor Settings: --elem-cnt-min=2 --elem-cnt-max=5 --pw-min=8 silen.dic
Agent command: --force -D 1

I tried to add a space in front of the "-r" in the attack command or reorder "-r file" to the end of the command, without success.

**Comment by hops** [comment]
I just tested this issue and there a bug in the agent code. The parsing of the attack command seems to be flawed when a preproccesor is used. Of course we should fix this but for now use this workaround.
If you use `#HL# -r leetspeak.rule` instead of ` -r leetspeak.rule #HL#` as your attack command the agent will do the correct thing.

**Comment by hops** [comment]
A fix has been push to this branch: https://github.com/s3inlc/hashtopolis-agent-python/tree/fix/update_files
@backi83 If possible could you give it a test run to see if this fixed it for you?
You'd have to checkout that branch and run the agent with
```
$ python3 __main__.py
```

**Comment by backi83** [comment]
I can confirm that both, workaround and fix are working. Thank you very much!
