### ISSUE TITLE
Available outfile-format in hashcat 6.0 differs from hashcat 5.1

### ISSUE THREAD

**Issue by icoisel** [s3inlc/hashtopolis#635]
Conducting some tests with hashtopolis 0.12.0 and the beta version hashcat 6.0, I got an error:

`Invalid --outfile-format value specified`

It appears that the outfile formats from hashact 6.0 is more limited than those of hashcat 5.1 as they only contains the following ones:

  1 | hash[:salt]
  2 | plain
  3 | hex_plain
  4 | crack_pos
  5 | timestamp absolute
  6 | timestamp relative

Hashtopolis is crafting a hashcat command with the outfile format 15 triggering the hashcat error. I didn't identify any place in the GUI to modify the expected outfile format. 

Should this be solved at the hashtopolis level or should it be raise to hashcat devs to (re-)include the missing outfile format?

**Comment by s3inlc** [comment]
The new outfile format is already implemented, but there was a bug causing it not to recognize the 6.0.0 version string properly. This was fixed in s3inlc/hashtopolis-agent-python#12 this morning.
