### ISSUE TITLE
Hashlists doesnt sync

### ISSUE THREAD

**Issue by Undercoverdog** [s3inlc/hashtopolis#638]
I have some sha1 Hashlists, with partly the same hashes.
When I crack a hash, which is also in the other Lists, why it doesnt get the crack too?
Pls fix that

**Comment by s3inlc** [comment]
Hashtopolis is not designed to have a global hash storage to do cross-referencing if hashes from other hashlists are found.
Ideally you should make sure that you don't have the same hashes in multiple hashlists, or is there a specific reason for this?

If you want to be sure that they are updated, you can group all your sha1 hashlists as one superhashlist and run tasks on this. This would make sense anyway as there is not more work to be done with more hashes, if you keep them each in separate lists, you would run the same attacks multiple times and waste resources.
