### ISSUE TITLE
Keyspace measure failed, when use -a 3 mode!

### ISSUE THREAD

**Issue by kivik92** [s3inlc/hashtopolis#639]
**Use github issues only for bugs/feature requests - for discussions, general help and questions use the forum: https://hashtopolis.org**
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage.
**Hashtopolis Server version: 0.12.0 (commit 11758c2 branch master)**
- Current Client version
**client 's3-python-0.6.0'**
- Your current Hashcat version
**hashcat-6.0.0+4.7**
- The exact task command you are trying to run.
**'hashcat.exe --keyspace --quiet -a 3 ?a?a?a?a?a #HL#  --hash-type=5600 '**
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.
**Error during keyspace measure: Command 'hashcat.exe --keyspace --quiet -a 3 ?a?a?a?a?a #HL#  --hash-type=5600 ' returned non-zero exit status 4294967295.
{'action': 'clientError', 'token': 'aEaOKr25r4', 'taskId': 4925, 'chunkId': None, 'message': 'Keyspace measure failed!'}**

**Describe your problem in as much detail as possible " It's broke " is not a description.**
Hi!
Whne I using command for brute-force attack, for example **-a 3 ?a?a?a?a**, I have always the same error _"Error during keyspace measure"_?
Anybody can help me?
Thx!

**Comment by kivik92** [comment]
> **Use github issues only for bugs/feature requests - for discussions, general help and questions use the forum: https://hashtopolis.org**
> **Before you submit an issue please include the following information if you do not your issue will be closed.**
> 
> * Your current Server version located at the bottom of any Hashtopolis webpage.
>   **Hashtopolis Server version: 0.12.0 (commit [11758c2](https://github.com/s3inlc/hashtopolis/commit/11758c2ae9fe6375f2205afacab6c0117871b271) branch master)**
> * Current Client version
>   **client 's3-python-0.6.0'**
> * Your current Hashcat version
>   **hashcat-6.0.0+4.7**
> * The exact task command you are trying to run.
>   **'hashcat.exe --keyspace --quiet -a 3 ?a?a?a?a?a #HL#  --hash-type=5600 '**
> * Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.
>   **Error during keyspace measure: Command 'hashcat.exe --keyspace --quiet -a 3 ?a?a?a?a?a #HL#  --hash-type=5600 ' returned non-zero exit status 4294967295.
>   {'action': 'clientError', 'token': 'aEaOKr25r4', 'taskId': 4925, 'chunkId': None, 'message': 'Keyspace measure failed!'}**
> 
> **Describe your problem in as much detail as possible " It's broke " is not a description.**
> Hi!
> Whne I using command for brute-force attack, for example **-a 3 ?a?a?a?a**, I have always the same error _"Error during keyspace measure"_?
> Anybody can help me?
> Thx!

Anybody can help me?

**Comment by Momro** [comment]
I unfortunately experience the same issue. The hashlist works fine with wordlist and rules, but not with bruteforce.

Attack Command: #HL# -a 3 ?a?a?a?a?a?a?a?a?a?a?a

Error Message in Web Frontend: "Keyspace measure failed!"

Environment: Hashtopolis: 0.12.0 commit d9f7af5 branch master

The task stayes at 0% (or does not even start), and in the details, it says "Keyspace dispatched: [Purge]"

**Comment by s3inlc** [comment]
@Momro in your case the reason for the error is because your task is too large. ?a with length 11 would mean that you have 95^11 combinations to test which is more than 100 times larger than what you can store in an unsigned 64-bit integer. Hashcat uses unsigned 64-bit integers, therefore it cannot handle such a large number.
Further, even with the fastest algorithms you can find on Hashcat, you would never accomplish such a task in reasonable time, it's just massively too big.

**Comment by s3inlc** [comment]
@kivik92 does it only fail on tasks with brute-force mode (-a 3)? 
The debug output you provided, was there specifically the placeholder `#HL#` contained in the command it called?
When you call the command which is shown in the debug log outside of Hashtopolis (running in the correct hashcat version folder in `crackers/<id>/`), what does Hashcat give as an error then?

**Comment by kivik92** [comment]
@s3inlc 
Thx for your attention
I have updated all agents and crackers, and All ok
Thx

**Comment by kivik92** [comment]
I am sorry, but I have still problem yet...
I have already done, what You said:
- First run this command _"-a 3 #HL# -w 4 --hwmon-disable -i ?d?d?d?d?d?d?d?d?d?d?d?d"_ on hashtopolis and I recived the error from my Agents _"errored: Keyspace measure failed!"_
**BUT**
When I run thihs command via CLI hashcat 6.0.0 (the same version of my crakers on hashtopolis)
_.\hashcat.exe -a 3 -m 2500 HASHLIST.hccapx -w 4 --hwmon-disable  -i ?d?d?d?d?d?d?d?d?d?d?d?d_, I haven't any error and All is fine
What's a problem of it???

**Comment by kivik92** [comment]
Anybody help me ?

**Comment by kivik92** [comment]
@s3inlc Help me Plz!

**Comment by s3inlc** [comment]
> @kivik92 does it only fail on tasks with brute-force mode (-a 3)?
> The debug output you provided, was there specifically the placeholder `#HL#` contained in the command it called?
> When you call the command which is shown in the debug log outside of Hashtopolis (running in the correct hashcat version folder in `crackers/<id>/`), what does Hashcat give as an error then?

The first question of this is still not answered. And also when you compare that it's running fine with hashcat 6.0.0, did this happen on the exact agent where it errors or was this somewhere else? Also on this new example you use -i (--increment), this was not shown on the first commands, if this was also the case there, the solution is clear. --increment does not work with Hashtopolis, as it's just wrapping multiple tasks.

**Comment by kivik92** [comment]
> > @kivik92 does it only fail on tasks with brute-force mode (-a 3)?
> > The debug output you provided, was there specifically the placeholder `#HL#` contained in the command it called?
> > When you call the command which is shown in the debug log outside of Hashtopolis (running in the correct hashcat version folder in `crackers/<id>/`), what does Hashcat give as an error then?
> 
> The first question of this is still not answered. And also when you compare that it's running fine with hashcat 6.0.0, did this happen on the exact agent where it errors or was this somewhere else? Also on this new example you use -i (--increment), this was not shown on the first commands, if this was also the case there, the solution is clear. --increment does not work with Hashtopolis, as it's just wrapping multiple tasks.

Hi @s3inlc 
About first question:  "The first question of this is still not answered" Can You explain what I must do, because I don't uderstandt, which output I must show You
About "did this happen on the exact agent where it errors or was this somewhere els" - This error happen on all my agent, which connected to hashtopolis server, when I use these commands:
"-a 3 ?d?d?d
-a 3 ?d?d?d?d?d?d?d?d?
etc.."
About "Also on this new example you use -i (--increment), this was not shown on the first commands, if this was also the case there, the solution is clear. --increment does not work with Hashtopolis" - Yes I know it, I had mistake when I wrote post I used this command -a 3 #HL# -w 4 --hwmon-disable -i ?d?d?d?d?d?d?d?d?d?d?d?d

**Comment by kivik92** [comment]
Hi 2 all!
The problem fixed - I have many agents, and I must set in task this task is only for one agent!
Thx
Sorry...

**Comment by connected201** [comment]
problem is in --keyspace parameter that is automatically execute when agent run hashcat
