### ISSUE TITLE
LUKS Headers when creating a new hashlist

### ISSUE THREAD

**Issue by klango** [s3inlc/hashtopolis#656]
- Your current Server version located at the bottom of any Hashtopolis webpage.
Hashtopolis: 0.12.0
- Your current Hashcat version
6.0.0
- The exact task command you are trying to run.
importing a 2MB LUKS Header
**Describe your problem in as much detail as possible " It's broke " is not a description.**
When adding a new hashlist with hashtype 14600 LUKS I import a standar 2MB LUKS Header in binary. 
Hashtopolis creates the list but it doesnt seem to work, as in "Hashes" it shows zero and the task wont run.
As if the header wint be interpreted as the hash to be attacked.
Any known issues with LUKS?

**Comment by s3inlc** [comment]
I assume that the binary part was too long for the current limit of the length for binary hashes. I will increase the max length from `MEDIUMTEXT` to `LONGTEXT`, where 2MB shouldn't be an issue anymore.
Sorry about the delay, just let me know if that was the issue, or if there is anything else still not working.

**Comment by winxp5421** [comment]
Closing this issue as it should be fixed. If you feel this is a mistake please reopen and update us.

**Comment by klango** [comment]
Hello,
so I did test and now I get the error 'Required file does not exist' when trying to upload the header.img file. The file is locally on my Desktop.
Using this same header file works on hashcat 
/opt/hashcat-6.1.1/hashcat.bin -a 0 -m 14600 headers.img Dictionary.txt

**Comment by klango** [comment]
> Closing this issue as it should be fixed. If you feel this is a mistake please reopen and update us.

Hello, reopening this.
so I did test and now I get the error 'Required file does not exist' when trying to upload the header.img file. The file is locally on my Desktop.
Using this same header file works on hashcat
/opt/hashcat-6.1.1/hashcat.bin -a 0 -m 14600 headers.img Dictionary.txt
