### ISSUE TITLE
Archive task problem?

### ISSUE THREAD

**Issue by zl9801** [s3inlc/hashtopolis#657]
**Use github issues only for bugs/feature requests - for discussions, general help and questions use the forum: https://hashtopolis.org**
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage.
0.8.0
- Current Client version
- Your current Hashcat version
- The exact task command you are trying to run.
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

**Describe your problem in as much detail as possible " It's broke " is not a description.**
After the task is archived, how to continue running the task again?

**Comment by s3inlc** [comment]
For such questions ideally the forum should be used, as it's technically not an issue. 
After a task is archived, there is no functionality on the UI so far to un-archive it again. But in the database itself it's just a flag which you could set back to 0 to let the task show up normal again.
Also please be aware that 0.8.0 is a fairly old version of Hashtopolis, updating is heavily recommended.
