### ISSUE TITLE
blank page - browser

### ISSUE THREAD

**Issue by jepunband** [s3inlc/hashtopolis#660]
hello, 

after setting up hashtopolis , i'm getting a blank screen on the browser.
Apache and PHP is working all configured correctly. I can setup and run wordpress locally with the current setup, so i know it is working. Hashtopolis on the other hand is not showing anything on the browser.

**Comment by s3inlc** [comment]
Please check for any error in the Apache2 error log. Most likely there is an error causing the blank page.

**Comment by jepunband** [comment]
hi error was :

[Fri Sep 11 11:50:07.372895 2020] [php7:warn] [pid 3272] [client ::1:59306] PHP Warning:  require_once(PEAR.php): failed to open stream: No such file or directory in /var/www/html/hashtopolis/src/inc/Auth_Yubico.class.php on line 13, referer: http://localhost/hashtopolis/
[Fri Sep 11 11:50:07.372943 2020] [php7:error] [pid 3272] [client ::1:59306] PHP Fatal error:  require_once(): Failed opening required 'PEAR.php' (include_path='.:/usr/share/php') in /var/www/html/hashtopolis/src/inc/Auth_Yubico.class.php on line 13, referer: http://localhost/hashtopolis/
[Fri Sep 11 11:50:09.460796 2020] [php7:warn] [pid 3273] [client ::1:59308] PHP Warning:  require_once(PEAR.php): failed to open stream: No such file or directory in /var/www/html/hashtopolis/src/inc/Auth_Yubico.class.php on line 13, referer: http://localhost/hashtopolis/
[Fri Sep 11 11:50:09.460843 2020] [php7:error] [pid 3273] [client ::1:59308] PHP Fatal error:  require_once(): Failed opening required 'PEAR.php' (include_path='.:/usr/share/php') in /var/www/html/hashtopolis/src/inc/Auth_Yubico.class.php on line 13, referer: http://localhost/hashtopolis/


so fixed it by :

     `apt install php-pear`

**Comment by s3inlc** [comment]
Thanks for the feedback. PHP pear is listed in the server prerequisites already, so I'm closing this issue.
