### ISSUE TITLE
Preprocessors config page in 0.12 does not work

### ISSUE THREAD

**Issue by n00btotal** [s3inlc/hashtopolis#669]
I'm using hashtopolis 0.12.0+repository

Fresh install.

I'm trying to configure "Preprocessors" (clicking "Config" -> "Preprocessors") but there is a server error.

When I check the apache error logs it says "Uncaught error: Undefined class constant 'PREPROCESSOR_ACCESS' in ... src/inc/templating/Statement.class.php(24) ... etc etc..

I tried to get the preprocessing going with 0.12 but no luck. Seems like I need to access that Config -> Preprocessor page? 

Note: This is an offline system. So I changed the URL to preprocessor in the database to get the download to work.

My offline 0.11 system works with PRINCE-task 👍

**Comment by hops** [comment]
I think this got fixed with commit 12f7ae6
One solution would be to use the master branch which also includes various other bug fixes. If you're not comfortable with running bleeding edge software you can checkout the commit 12f7ae6

**Comment by n00btotal** [comment]
Great! Thank you! Preprocessing works fine now after I updated to
commit a247df9 branch master
