### ISSUE TITLE
Problem CLient not download binary

### ISSUE THREAD

**Issue by kelevra-81** [s3inlc/hashtopolis#684]
Hi guys someone can help me, i have updated the binary hashcat-6.1.1 and the client give a message such as Download of cracker binary failed! 
 
Thanks

**Comment by s3inlc** [comment]
To help you we need a bit of information, the template should've given you an idea what you should provide.
Make sure that the client can reach the URL you provided for the hashcat binary.

**Comment by kelevra-81** [comment]
Yes the client can access. Maybe can.be a problem the permissions of the hashcat file? The path is http://192.168.0.100/var/www/hashtopolis/files/hashcat-6.1.1.7z

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by s3inlc** [comment]
The path most likely is wrong. Depending how you configured your apache2 server (DocumentRoot), typically you would not provide the full path (as you wouldn't set DocumentRoot to /). 
Are you really sure the client can access this path? Did you test that you can download the file with that link?

**Comment by kelevra-81** [comment]
No check if i can download the file i Will try

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by kelevra-81** [comment]
The server is well because i could get the old binary only change the hashcat 5xx to hashcat 6.1.1

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by s3inlc** [comment]
Note that the `files` folder in Hashtopolis typically also is protected, so it would not be accessible for direct downloads. You should place the 7z in the `static` folder.

You haven't yet confirmed, that on the client you are able to access that download link you provided (http://192.168.0.100/var/www/hashtopolis/files/hashcat-6.1.1.7z).... you can do for example by running on the client: `wget http://192.168.0.100/var/www/hashtopolis/files/hashcat-6.1.1.7z`

**Comment by kelevra-81** [comment]
i probe the wget he give a 404 error not found

**Comment by s3inlc** [comment]
> The path most likely is wrong. Depending how you configured your apache2 server (DocumentRoot), typically you would not provide the full path (as you wouldn't set DocumentRoot to /).
> Are you really sure the client can access this path? Did you test that you can download the file with that link?

As mentioned, this must be an issue with your URL, you have to adjust it to match for what you have configured in apache2.

**Comment by kelevra-81** [comment]
<Directory /usr/share>
        AllowOverride None
        Require all granted
</Directory>

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

#<Directory /srv/>
#       Options Indexes FollowSymLinks
#       AllowOverride None
#       Require all granted
#</Directory>
look at this my apache2.conf maybe the path of the file is srv

**Comment by s3inlc** [comment]
It's most likely just /var/www...
I would guess your URL needs to be http://192.168.0.100/hashtopolis/files/hashcat-6.1.1.7z

**Comment by s3inlc** [comment]
And be aware, because you set `AllowOverride None` you basically have the directories unprotected. Which means that everyone being able to access your server, could potentially access your wordlists/rules and potentially also mess up your installation.

**Comment by kelevra-81** [comment]
python hashtopolis.zip
Starting client 's3-python-0.6.0'...
Collecting agent data...
Login successful!
Hashtopolis Server version: 0.12.0 ()
Client is up-to-date!
Got task with id: 182
Download of cracker binary failed!

**Comment by s3inlc** [comment]
Running in debug mode would help to see something.

**Comment by kelevra-81** [comment]
how can i run debug mode

**Comment by kelevra-81** [comment]
i have change the 7z in this path  http://192.168.0.100/hashtopolis/hashcat-6.1.1.7z and i have the same error

**Comment by s3inlc** [comment]
> how can i run debug mode

```
$ python3 hashtopolis.zip --help
usage: python3 hashtopolis.zip [-h] [--de-register] [--version]
                               [--number-only] [--disable-update] [--debug]
                               [--voucher VOUCHER] [--url URL]

Hashtopolis Client v0.5.0

optional arguments:
  -h, --help         show this help message and exit
  --de-register      client should automatically de-register from server now
  --version          show version information
  --number-only      when using --version show only the number
  --disable-update   disable retrieving auto-updates of the client from the
                     server
  --debug, -d        enforce debugging output
  --voucher VOUCHER  voucher to use to automatically register
  --url URL          URL to Hashtopolis client API
  ```

**Comment by kelevra-81** [comment]
yes thank you 

http://192.168.0.100:80 "POST /api/server.php HTTP/1.1" 200 163
b'{"action":"downloadBinary","response":"SUCCESS","url":"http:\\/\\/192.168.0.100\\/hashtopolis\\/hashcat-6.1.1.7z","name":"hashcat","executable":"hashcat-6.1.1.7z.exe"}'
http://192.168.0.100:80 "HEAD /hashtopolis/hashcat-6.1.1.7z HTTP/1.1" 404 0
Download of cracker binary failed!

**Comment by s3inlc** [comment]
> i have change the 7z in this path http://192.168.0.100/hashtopolis/hashcat-6.1.1.7z and i have the same error

Did you move the 7z outside of the files directory for that URL? (As you removed the files/ subfolder from the link)
With the information you provided so far, these are all just guesses. I wrote quite some notes what you need to keep in mind, but at the end you either have to do a little research on what you would need to check or give enough information to allow me to help more efficiently.

**Comment by s3inlc** [comment]
> yes thank you
> 
> http://192.168.0.100:80 "POST /api/server.php HTTP/1.1" 200 163
> b'{"action":"downloadBinary","response":"SUCCESS","url":"http:\/\/192.168.0.100\/hashtopolis\/hashcat-6.1.1.7z","name":"hashcat","executable":"hashcat-6.1.1.7z.exe"}'
> http://192.168.0.100:80 "HEAD /hashtopolis/hashcat-6.1.1.7z HTTP/1.1" 404 0
> Download of cracker binary failed!

Did you also test with `http://192.168.0.100/hashtopolis/files/hashcat-6.1.1.7z`? (the link I proposed)

**Comment by kelevra-81** [comment]
yes i have same error

Got task with id: 182
{'action': 'downloadBinary', 'token': 'qkbV5wF2dN', 'type': 'cracker', 'binaryVersionId': '2'}
http://192.168.0.230:80 "POST /api/server.php HTTP/1.1" 200 170
b'{"action":"downloadBinary","response":"SUCCESS","url":"http:\\/\\/192.168.0.230\\/hashtopolis\\/files\\/hashcat-6.1.1.7z","name":"hashcat","executable":"hashcat-6.1.1.7z.exe"}'
http://192.168.0.230:80 "HEAD /hashtopolis/files/hashcat-6.1.1.7z HTTP/1.1" 404 0
Download of cracker binary failed!

**Comment by s3inlc** [comment]
Then I just have to assume that you placed the hashcat 7z at the wrong place.

Also you have not set the hashcat basename correctly, this should only be `hashcat` and not `hashcat-6.1.1.7z`

**Comment by kelevra-81** [comment]
i think so but i dont know where is the correct place

**Comment by s3inlc** [comment]
There is no wrong or right place. But you should be aware about how you derive an apache2 path from a file location, and then just place it at a place which is accessible and adjust the URL to that.

Just in case, the easiest is always to just set the URL to the official hashcat download link from hashcat.net, unless there is a specific reason not to do so.

**Comment by s3inlc** [comment]
http://192.168.0.100/hashtopolis/files/hashcat-6.1.1.7z -> place in /var/www/hashtopolis/files/
http://192.168.0.100/hashtopolis/hashcat-6.1.1.7z -> place in /var/www/hashtopolis/
http://192.168.0.100/hashtopolis/static/hashcat-6.1.1.7z -> place in /var/www/hashtopolis/static

And if this does not work, there is something wrong with your setup/apache2.

**Comment by kelevra-81** [comment]
i have change the 7z in folder html and i run ok

**Comment by kelevra-81** [comment]
thank for your help friends thank you very much

merry christmas

**Comment by s3inlc** [comment]
Thanks.

Please use Discord or the Forum for such issues the next time, as the issues on github should mainly be used for bugs/features/enhancements.
