### ISSUE TITLE
I cant start crack

### ISSUE THREAD

**Issue by LandetCoronet82** [s3inlc/hashtopolis#688]
hi i'm new to hashtopolis and i need help to start with that i see that error when i try run a task 
Error during keyspace measure: Command 'hashcat.exe --keyspace --quiet  -a 3   --hash-type=0 ' returned non-zero exit status 4294967295. Output:
and agent pause
![Zrzut ekranu 2021-01-01 132027](https://user-images.githubusercontent.com/73692038/103438544-310edc80-4c34-11eb-9630-808731d0266e.png)

**Comment by LandetCoronet82** [comment]
[client.log](https://github.com/s3inlc/hashtopolis/files/5758904/client.log)

**Comment by jarlethorsen** [comment]
1. What is the attack you are trying to run?
2. If you start the agent with debugging enabled, it will provide more info.

**Comment by LandetCoronet82** [comment]
[client.log](https://github.com/s3inlc/hashtopolis/files/5760646/client.log)

**Comment by jarlethorsen** [comment]
This time you are not specifying the attack mode... (only option -a followed by the mask)

Try changing the attack to: ```-a3 #HL# ?a?a?a```

**Comment by LandetCoronet82** [comment]
ok its working 
but how to increment properly in hashtopolis

**Comment by winxp5421** [comment]
Github Issues should be for actual issues with the software not Support based things.
Support can be found on Discord, IRC, or Forum.

Your question can be answered by reading the documentation. 
I suggest you give the supporting documentation a good read.
https://github.com/s3inlc/hashtopolis/wiki/Frequent-Problems
