### ISSUE TITLE
Bug: Can't Change SuperTask Priority

### ISSUE THREAD

**Issue by JohnTar22** [s3inlc/hashtopolis#711]
Hi There,
after upgrading to latest version (git pull inside hashtopolis folder) i can't change supertask priority. it's stuck on the predefined priority that was set on the creation of the supertask.
i'm keep getting " Invalid task ID! " on a red bar on the upper part of the webpage,

i can change the priority using mysql but it is a very dirty workaround.
any help is much appreciated.
John.

**Comment by zyronix** [comment]
Hi John,

Could you describe on which page you are trying to set the priority? Is this in the general overview page?
<serverip>/hashtopolis/tasks.php?

Or is it on a different page?

Could you also descibe the exact commit number you are currently running on? You can get this by running: git rev-parse HEAD

**Comment by zyronix** [comment]
Ah check, nvm. I though this was already merged:

https://github.com/s3inlc/hashtopolis/pull/703

Known issue, @s3inlc could you merge #703 ?

**Comment by JohnTar22** [comment]
if it's still relevant 240220172bd9c9a68f644f08e2611ec6eaa9de01.
and yes i'm trying to change from the general tasks.php page.
thanks a lot.

**Comment by s3inlc** [comment]
My bad, didn't realize that this was already present to be merged to fix. I hope the bug is fixed now.

**Comment by JohnTar22** [comment]
i can confirm that it's fixed now! thanks again. 
can be closed.

**Comment by s3inlc** [comment]
great, thanks for the feedback!
